### ISSUE TITLE
Not receiving any messages

### ISSUE THREAD

**Issue by darookee** [windkh/node-red-contrib-telegrambot#1]
Hi!

I have a hard time getting this to work reliably. The bot does not receive any messages most of the time. I already started node-red with `DEBUG=node-telegram-bot-api node-red` to get the output of the telegram-bot-api. The message seems to get through to the api, but seems to not get forwarded to node-red.

I'm using this flow to test:
```json
[{"id":"d0608650.2f9f78","type":"telegram bot","z":"bfd70105.4029","botname":"r_testbot"},{"id":"65566071.9aa9a","type":"telegram command","z":"bfd70105.4029","name":"/test","command":"/test","bot":"d0608650.2f9f78","x":203,"y":413,"wires":[["eae6a77a.151958","c050a0c0.3faf6"],["c050a0c0.3faf6"]]},{"id":"eae6a77a.151958","type":"telegram sender","z":"bfd70105.4029","name":"","bot":"d0608650.2f9f78","x":512,"y":409,"wires":[]},{"id":"c050a0c0.3faf6","type":"debug","z":"bfd70105.4029","name":"","active":true,"console":"false","complete":"true","x":479,"y":531,"wires":[]}]
```

The debug pane stays empty, but the node-red log displays the incoming message:

```
  node-telegram-bot-api polling with options: {"qs":{"offset":1,"timeout":10},"url":"https://api.telegram.org/botXXXXAPIKEYXXX/getUpdates"} +303ms
  node-telegram-bot-api polling data [{"update_id":109933319,"message":{"message_id":36,"from":{"id":XXXXX,"first_name":"Da","username":"Rookee"},"chat":{"id":XXXX,"first_name":"Nils","username":"darookee","type":"private"},"date":1454063974,"text":"/test 44
4"}}] +774ms
  node-telegram-bot-api updated offset: 109933319 +3ms
  node-telegram-bot-api Process Update {"update_id":109933319,"message":{"message_id":36,"from":{"id":XXXXX,"first_name":"Nils","username":"darookee"},"chat":{"id":XXXXX,"first_name":"Nils","username":"darookee","type":"private"},"date":1454063974,"text":"/test 4
44"}} +3ms
  node-telegram-bot-api Process Update message {"message_id":36,"from":{"id":XXXXX,"first_name":"Nils","username":"darookee"},"chat":{"id":XXXXX,"first_name":"Nils","username":"darookee","type":"private"},"date":1454063974,"text":"/test 444"} +3ms
  node-telegram-bot-api polling error: {} +5ms
  node-telegram-bot-api setTimeout for 300 miliseconds +3ms
```

After looking further into telegram-bot-api I'm not sure if the message is actually passed to the event handler, which should happen [here](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L79) and should also produce a coresponding line in the debug log...

**Comment by windkh** [comment]
Hi, thank you.
I am running a bot for several days now and discovered similar issues. In addition to your problem mine sends/receives  the same message twice or even more times. I will forward this issue to the underlying telegram-bot-api developer.

**Comment by darookee** [comment]
Thanks!

**Comment by windkh** [comment]
see
https://github.com/yagop/node-telegram-bot-api/issues/69

**Comment by windkh** [comment]
I will set a breakpoint there to see where the message gets lost... will take some time

**Comment by windkh** [comment]
@darookee 
```
    node-telegram-bot-api` polling error: {} +5ms
```
The polling error is not printed. I can see it in the debugger, but it is not visible in the log-line, maybe because of the format specifier %j [here](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegramPolling.js#L42)

Could you change the modifier or break into the debugger to see what error you got?

**Comment by darookee** [comment]
I used the good ol' `console.log` and got this: 
```
[TypeError: Object /test sdf has no method 'startsWith']
```
Which seems to come from [this](https://github.com/windkh/node-red-contrib-telegrambot/blob/master/telegrambot/99-telegrambot.js#L145). I added a TelegramInNode and removed the TelegramCommandNode and still got the same error after deploying, twice. After restarting node-red I got the message sent back to me without any error.

It looks like the events are not properly removed when removing nodes...

**Comment by darookee** [comment]
I just did another test. I added a new TelegramCommandNode and connected it to the existing TelegramSendNode, along with the TelegramInNode. Now I get no error and the message comes back twice...
Seems like the function from the first node added is called everytime...

**Comment by windkh** [comment]
Every TelegramCommandNode is a receiver node with its own message handler. The command node simply filters out the command at the beginning of the message and passes the remaining message the the output. 
But the message should never be undefined as botMsg.text is checked right two lines above. 
hm...

**Comment by darookee** [comment]
The problem may be that I'm using node v0.10.29... I'll try to update while wondering why it is that old to begin with... I'll report back!

**Comment by darookee** [comment]
Now using node v0.12.6 (on a raspberry pi...) I get this error: `[TypeError: undefined is not a function]` with the command node. It seems to break at the [same line](https://github.com/windkh/node-red-contrib-telegrambot/blob/master/telegrambot/99-telegrambot.js#L145) as before, just with a different message :-/

**Comment by windkh** [comment]
I am running Node 4.2.1, but startsWith should be a common function. Which version of node-red-contrib-telegrambit do you use?

**Comment by windkh** [comment]
Note that the configuration node creates an instance of the underlying API. If you have several configuration nodes laying around they will all start polling right after start up. It does not depend if they are used by any other node.

**Comment by windkh** [comment]
Whenever the nodes are deployed, a new polling timer ist started. This leads to more and more timers running at the same time for the same token. The running instances need to be stopped before the new ones are started. As a workaround the node-process needs to be restarted after every deployment.

**Comment by windkh** [comment]
> I just did another test. I added a new TelegramCommandNode and connected it to the existing TelegramSendNode, along with the TelegramInNode. Now I get no error and the message comes back twice...
Seems like the function from the first node added is called everytime...

The new version stops the polling timers of the nodes on redeploy now. The messages should not occur twice anymore.

**Comment by windkh** [comment]
@darookee
did you made any progress with the "startsWith" problem?

**Comment by darookee** [comment]
Duplicate messages after deploying are gone, thanks!

I think this can be closed, .startsWith does not work with node.js 0.10.x and 0.12.x. I tried the same configuration on another machine using node.js 4.x and it just worked without problems. So I just have to install node.js 4.x on the RPi...

**Comment by windkh** [comment]
Thanks alot for the input, I will add this to the readme, maybe I will replace the line with some other code in one of the nex releases.

**Comment by darookee** [comment]
There is a [polyfill](https://github.com/mathiasbynens/String.prototype.startsWith) but I don't think that this would be worth it. On the other hand, the node-red min node.js version is 0.10... :-)

**Comment by windkh** [comment]
`
message.startsWith 
`
can be replaced with 
`
if(message.slice(0, command.length) == command){
`
to get it running in older node versions

**Comment by darookee** [comment]
The new version works without any errors, thanks! :-)
