### ISSUE TITLE
example sendMediaGroup is not working

### ISSUE THREAD

**Issue by Raainman** [windkh/node-red-contrib-telegrambot#100]
I'm trying to get sendMediaGroup to work, but I failed. I'm running NodeRed on a raspberry, so the example given does not run out of the box, since it contains C:\. I tried to change the code to the following, and manually created files to exist in the tmp dir, but Telegram is refusing.

400 Bad Request: File must be non-empty

Single photo sending is working perfectly
```
// sendMediaGroup example: send  between 2 and 10 media.
// Note that type can also be video.
// and the caption property is optional.
// see https://core.telegram.org/bots/api#inputmediaphoto
// see https://core.telegram.org/bots/api#inputmediavideo

msg.payload.type = "mediaGroup";
msg.payload.content = [
    {
        type : "photo",
        media : "/tmp/1.jpg",
        caption : "Photo 1"
    },
    {
        type : "photo",
        media : "/tmp/2.jpg",
        caption : "Photo 2"
    }
];

return msg;

```

**Comment by Raainman** [comment]
[{"id":"ff21c681.f09c08","type":"telegram sender","z":"20dd0618.f5c70a","name":"","bot":"f6c9cbd2.006338","x":721,"y":1091,"wires":[[]]},{"id":"606f8ad5.8b03a4","type":"telegram command","z":"20dd0618.f5c70a","name":"","command":"/send","bot":"f6c9cbd2.006338","strict":false,"x":290,"y":1100,"wires":[["68398870.4c4a78"],[]]},{"id":"68398870.4c4a78","type":"function","z":"20dd0618.f5c70a","name":"create media group","func":"// sendMediaGroup example: send  between 2 and 10 media.\n// Note that type can also be video.\n// and the caption property is optional.\n// see https://core.telegram.org/bots/api#inputmediaphoto\n// see https://core.telegram.org/bots/api#inputmediavideo\n\nmsg.payload.type = \"mediaGroup\";\nmsg.payload.content = [\n    {\n        type : \"photo\",\n        media : \"/tmp/1.jpg\",\n        caption : \"Photo 1\"\n    },\n    {\n        type : \"photo\",\n        media : \"/tmp/2.jpg\",\n        caption : \"Photo 2\"\n    }\n];\n\nreturn msg;","outputs":1,"noerr":0,"x":505,"y":1091,"wires":[["ff21c681.f09c08"]]},{"id":"f6c9cbd2.006338","type":"telegram bot","z":"","botname":"RainNodeRedbot","usernames":"","chatids":"14955879","baseapiurl":"","updatemode":"polling","pollinterval":"500","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]

**Comment by windkh** [comment]
I will check that

**Comment by Raainman** [comment]
Never mind I got it now ... goofup on my side. File size was zero .
