### ISSUE TITLE
is forwardMessage supported?

### ISSUE THREAD

**Issue by youleaf** [windkh/node-red-contrib-telegrambot#101]
I want to implement a bot like [livegrambot](https://telegra.ph/What-is-Livegram-Bot-03-17)

Basically I want my bot to forward messages to a chat/group using the telegram bot api [forwardMessage](https://core.telegram.org/bots/api#forwardmessage) method, and I want members of such chat/group to be able to reply to such messages using the "reply" button.

I noticed that the command forwardMessage is not in the list  of Sender Node supported direct commands described at https://flows.nodered.org/node/node-red-contrib-telegrambot.

Is this feature supported? node-telegram-bot-api supports the [forwardMessage method](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#telegrambotforwardmessagechatid-fromchatid-messageid-options--promise). Is there a reason this method is not implemented in node-red-telegrambot?  Am I missing something?

thank you in advance!

**Comment by windkh** [comment]
Hi @youleaf 
there is no special reason why this is not supported by now.
I will try to add this feature with one of the next releases.

**Comment by windkh** [comment]
Version 7.1.2 contains the feature
