### ISSUE TITLE
Idea to improve Command Node

### ISSUE THREAD

**Issue by bonastreyair** [windkh/node-red-contrib-telegrambot#103]
I'm not very used to `JavaScript` so the things I tested were all in `Node-RED`. I tried to Fork the repo to create a PR but I get a little bit lost within the code. I hope I can explain myself.

The main idea is that whenever you use the command node, let's say a command that expects you to answer, it is quite difficult to manage it with the actual node. Now the responses of the command node appear in the `Error Output` of all command boxes, and you have to handle and make use of global context variables to enable just one. If a node does not expect any answer the second output still exists.

Why not handle all this tedious work inside the same node with a simple check-box in the following cases:
- there is no expected response --> the command node only has one output, for information messages like `/help`
- there is an expected response --> activate the response only on that command node and not on the rest of nodes. I would even disable it from the input telegram node (configurable via another check-box in the input node)

Since the bot can speak to many users, I'm taking into account that maybe one user is asking for a command, and another user is making another command and that should not interfere.

Also I'm taking into consideration if you start with a command and you start a new command, it resets everything just like `BotFather` does.

## New settings just when initialised
![Screenshot 2020-04-05 at 20 14 26](https://user-images.githubusercontent.com/37800834/78506482-12011e00-777a-11ea-904c-1fe44f28316f.png)
#### first global variable setup - function
```js
settings = {
    pending_cmds: {}
};

global.set("telegram", settings);
```

## Example without response
![Screenshot 2020-04-05 at 21 20 44](https://user-images.githubusercontent.com/37800834/78507902-55ac5580-7783-11ea-8cef-35e16f176711.png)
```js
has_a_response = false;  // Check-box configuration
```
## Example with response
![Screenshot 2020-04-05 at 21 21 19](https://user-images.githubusercontent.com/37800834/78507935-6f4d9d00-7783-11ea-80fe-f96d04155bd3.png)
```js
has_a_response = true;  // Check-box configuration
```
### command handling
```js
/* This should be integrated in the same command node */
has_a_response = true;  // Check-box configuration true or false
cmd = msg.originalMessage.text;
settings = global.get("telegram");

// Reset other running commands
for (var key of Object.keys(settings.pending_cmds[msg.originalMessage.from.username])) {
    settings.pending_cmds[msg.originalMessage.from.username][key] = false;
}

if (has_a_response) {
    // Sets pending command to true for a specific username
    settings.pending_cmds[msg.originalMessage.from.username][cmd] = true;
    global.set("telegram", settings)
}

return msg;
```

### response handling
```js
/* This should be integrated in the same command node */
has_a_response = true;  // Check-box configuration true or false
cmd = "/md_text";  // Name of the command

if (has_a_response) {
    settings = global.get("telegram");
    waiting_for_cmd = settings.pending_cmds[msg.originalMessage.from.username][cmd]
    if (waiting_for_cmd) {
        node.send(msg);
    }
    // Resets pending command to false for a specific username
    settings.pending_cmds[msg.originalMessage.from.username][cmd] = false;
    global.set("telegram", settings);
}
```

I'm attaching my flows so that you can understand the full idea working with global context (which I know it is not the way, and that is why I poste this idea). I have created some subflows to handle the idea easily. Also I added color [#0088cc](https://www.lockedownseo.com/social-media-colors/#telegram) which is the official HEX color of Telegram. 😉 

[node_red_json_flow.txt](https://github.com/windkh/node-red-contrib-telegrambot/files/4434608/node_red_json_flow.txt)

Hope you like it and easily integrate it 😄 .

**Comment by windkh** [comment]
I will have a look at it... when I find some time.
Long time ago I wanted to integrate something like that, but I was not sure if somebody would need it. So I postponed that until now.

**Comment by windkh** [comment]
Well, I think that the second output could be easily deactivated when no response is of interest:
I will add this very soon.

The second thing, handling the states of the different incoming requests, is a little bit more tricky.
Right now you have full control over everything but at the same you are responsible for the tedious work. If I would apply a certain pattern here I could break existing implementations. Right now I am stuck in what to do here as I can not see the long term consequences... changes to that node need to stay somehow compatible. Nevertheless I see your point ... let me think about that idea some more days.

**Comment by bonastreyair** [comment]
Great! Looking forward for the new release!

That is true, "full control" but more tedious work to do. If major changes, then you should jump to v8.0.0, right? Tell me if I could be of any help, I'm now in the same side as you as I have just submitted the [node-red-contrib-teachable-machine](https://flows.nodered.org/node/node-red-contrib-teachable-machine) on my own 💪. 

For example you could create a checkbox that enables this feature (not by default) so that it doesn't break older implementations?

**Comment by windkh** [comment]
version 7.2.1: second command node output can be disabled now: next step will be the integrated response handling.

**Comment by windkh** [comment]
version 8.0.0 contains the feature
I went back to the former color as the genuine telegram color is a bit too bad to read with black node texts

**Comment by bonastreyair** [comment]
Wow! So quick! Awesome!
Thanks! Yeah original color is a bit too dark...
