### ISSUE TITLE
The request package is deprecated!

### ISSUE THREAD

**Issue by Victormatheus819** [windkh/node-red-contrib-telegrambot#104]
Please, replace or update  the deprecated package in our 7.2.0 version on  NODE_RED

**Comment by windkh** [comment]
What exactly is deprecated?

**Comment by bonastreyair** [comment]
> Please, replace or update the deprecated package in our 7.2.0 version on NODE_RED

Are you referring to this request issue? 
[Request’s Past, Present and Future #3142](https://github.com/request/request/issues/3142)

This deprecation even appears when you install `Node-RED` for the first time.

**Comment by windkh** [comment]
hm I thought upgrading to a new version would be enough but it sounds like request is stopped without any successor. Or should we go to bent?
https://github.com/mikeal/bent

**Comment by windkh** [comment]
As long as the underlying library makes use of the request package I can not do anything about this.

**Comment by bonastreyair** [comment]
That's what I though, if your dependant libraries use `request` package, you can't do anything... 😅
