### ISSUE TITLE
Can't send messages after upgrading group to supergroup.

### ISSUE THREAD

**Issue by vindolin** [windkh/node-red-contrib-telegrambot#105]
I changed the permissions of one of the group user and that triggered an upgrade of the group to a supergroup.

I used @get_id_bot to get the new group chat id and changed the ChatIds bot setting in node red and deployed but I continue to get the same error message.

`"Error: ETELEGRAM: 400 Bad Request: group chat was upgraded to a supergroup chat"`

**Comment by windkh** [comment]
Try to make your bot admin in the superhroup

**Comment by vindolin** [comment]
Thank you, I tried that and it didn't work.
I even made a complete new group (no supergroup) and used the new group chat id.
Same error message.

**Comment by vindolin** [comment]
Turned out, I put the chatId into the message payload of a function node and forgot about it :(
Sorry for the false report!

**Comment by windkh** [comment]
Kein problem
