### ISSUE TITLE
I can't send mediaGroup

### ISSUE THREAD

**Issue by Andorium** [windkh/node-red-contrib-telegrambot#110]
I can't send mediaGroup. I get an error.

![image](https://user-images.githubusercontent.com/46258470/82388074-18a9d300-9a52-11ea-8aad-f4909d0c23ed.png)

![image](https://user-images.githubusercontent.com/46258470/82388005-e39d8080-9a51-11ea-8db3-5ec93e348003.png)

`[{"id":"7efbf86f.e52008","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"5e9f516e.15436","type":"function","z":"7efbf86f.e52008","name":"sendMediaGroup","func":"// sendMediaGroup example: send  between 2 and 10 media.\n// Note that type can also be video.\n// and the caption property is optional.\n// see https://core.telegram.org/bots/api#inputmediaphoto\n// see https://core.telegram.org/bots/api#inputmediavideo\n\nmsg.payload.type = \"mediaGroup\";\n\nmsg.payload.content = [\n    {\n        type : \"photo\",\n        media : \"c:\\\\temp\\\\1.jpg\",\n        caption : \"Photo 1\"\n    },\n    {\n        type : \"photo\",\n        media : \"c:\\\\tmp\\\\2.jpg\",\n        caption : \"Photo 2\"\n    }\n];\n\nreturn msg;","outputs":1,"noerr":0,"x":450,"y":220,"wires":[["2a50b142.4318ae","942b9a78.462978"]]},{"id":"cb8ffa13.514b08","type":"telegram receiver","z":"7efbf86f.e52008","name":"","bot":"5ed562d2.c8e09c","saveDataDir":"","filterCommands":false,"x":250,"y":180,"wires":[["5e9f516e.15436"],[]]},{"id":"2a50b142.4318ae","type":"telegram sender","z":"7efbf86f.e52008","name":"","bot":"5ed562d2.c8e09c","x":650,"y":260,"wires":[["5aba8832.dc4e28"]]},{"id":"d569d03a.588e3","type":"catch","z":"7efbf86f.e52008","name":"","scope":null,"uncaught":false,"x":280,"y":360,"wires":[["83ea8aa8.e3f4e8"]]},{"id":"83ea8aa8.e3f4e8","type":"debug","z":"7efbf86f.e52008","name":"cach all","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":440,"y":360,"wires":[]},{"id":"942b9a78.462978","type":"debug","z":"7efbf86f.e52008","name":"sendmsg","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":640,"y":160,"wires":[]},{"id":"5aba8832.dc4e28","type":"debug","z":"7efbf86f.e52008","name":"respmsg","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":820,"y":300,"wires":[]},{"id":"5ed562d2.c8e09c","type":"telegram bot","z":"","botname":"cashflowteacher_bot","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":true,"sockshost":"185.29.126.17","socksport":"45786","socksusername":"SelAndorium","sockspassword":"Z0k1AdA","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":true}]`

**Comment by windkh** [comment]
Hm I will try to reproduce it... seems that some proxy blocked.

**Comment by windkh** [comment]
I can not reproduce that error
