### ISSUE TITLE
How to send into two chatids= into two groups at the same time?

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#111]
i want to send the same message into two differnt groups.

i lookuped up all the issues and the readme.md and found no hint.
how to set up two receiving group ids? for the same mesage?
two times the sender node? or can i specify two receiving chat-ids at the same time?

any hint greatly appreciateted to approach this. thankx
tozett

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/sendtomanychats.json

**Comment by windkh** [comment]
You can specify an array of ids

**Comment by ozett** [comment]
GREAT! 

thanks for the fingertip!
👍

**Comment by ozett** [comment]
just a little observation:
when i put two different chat-IDs into a json-array to send one message to two differnent  groups it works fine. when i check both groups, they received this one message. all look correct.

when i check the node-red debug-log, than i dont have there two confirmations with the different chat-ids. instead i have two confirmation messages with the same chat-id (wich is the last element in the array). maybe a bug?


![image](https://user-images.githubusercontent.com/5937811/83905834-a67c0280-a762-11ea-9a48-105d05595aa7.png)

**Comment by windkh** [comment]
Thanks ... that seems to be an error

**Comment by ozett** [comment]
👀

**Comment by windkh** [comment]
fixed in 8.2.0
