### ISSUE TITLE
Some problems with socks5

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#112]
Hi, to change really the socks server I need to restart node red, deply is not enough.
Also, when there are problems with socks server, deploy takes lot of time and returns "Error stopping node: Close timed out"

There would be welcome to have an option to test suddenly if socks5 is working, outputs on NR log to notice it doesn't work takes some time unfortunately

**Comment by windkh** [comment]
What do younmean with „change“?
The ip adress?

**Comment by windkh** [comment]
The delay is probably a network timeout... if the server does not respond then you will always end up in this timeout. The only thing you could do is lowering this timeout

**Comment by Barabba11** [comment]
thank you for support )
to change the socks server I need to restart NR, if I just deploy the changes it still use the socks IP server that was before

**Comment by windkh** [comment]
Ah I see... will check that.... tomorrow

**Comment by Barabba11** [comment]
Thank you a lot, I'm in Russia and I can't access the telegram api server, do you know if there is any way to overcome it? Maybe using Webhook?
If I've to use forcely a socks5, do you know a reliable server? Thank you

**Comment by windkh** [comment]
I guess you can use any kind of proxy... there are plenty of free ones available in the internet. Another idea is to use a vpn connection to some other country. Only a few ideas from my side but to be honest I only used proxies for testing not for a real bot...

**Comment by Barabba11** [comment]
I remeber one year ago when I tested this module I've found after several tries a Proxy, but now it takes me time and I still can't find one that works. I have a tool in Windows to check if the proxy works, but with module for some reasons not, maybe it doesn't support https that Telegram seems to pretend as it listen on :443
Unfortunately free proxy servers die after some hours, I'm looking for one connected to ddns so the IP can change according to the server.. maybe a generous soul had made a proxy for Telegram only.. as the messages require so small amout of bytes.. maybe there is possible to open it for everybody and only for api telegram. Do you know anything about it?
There is any other way? What about Webhook?

**Comment by Barabba11** [comment]
If you want to test at this time I've found one working: 142.93.170.92:1080

**Comment by Barabba11** [comment]
Do you have news? I've another small request, the module produces a big log in the NR console, and I haven't selected verbose in the settings. As I have some messages to send it would be better to don't log them, is it possible? Thank you

**Comment by windkh** [comment]
I am busy (at work) ... create a new issue for that and append the log you have

**Comment by Barabba11** [comment]
Sorry for disturb, sure take your time :)
Ok I open it

**Comment by Barabba11** [comment]
To disable socks today didn't request me to restart NR, so probably the problem still on change the socks proxy IP

**Comment by windkh** [comment]
I guess the timeout occurs when the bot is not really polling but polling should be stopped during redeploy.
see config node self.telegramBot.stopPolling().then(setStatusDisconnected);
