### ISSUE TITLE
Logs take lot of space on console

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#113]
Hi! the module produces a big log in the NR console, and I haven't selected verbose in the settings. As I have some messages to send it would be better to don't log them, leaving space for error messages ony, is it possible? Thank you

**Comment by windkh** [comment]
can you please specify what log messages are produced? Maybe you could paste the output here?

**Comment by Barabba11** [comment]
Hi! Any chances to correct this please? ) My logs are exploding. Thank you :)

**Comment by windkh** [comment]
Can you please paste your output here???

**Comment by Barabba11** [comment]
yes, for every message I received I have a log on consolle, I would prefer to don't have nothing or maybe just a line with chadID and the content of the message.

26 Jul 15:19:48 - [info] Starting flows
26 Jul 15:19:48 - [info] Started flows
26 Jul 15:21:31 - [info] [debug:c410c6fb.5d903]
{
  payload: {
    chatId: 956528929,
    messageId: 26,
    type: 'message',
    content: 'Ciao'
  },
  originalMessage: {
    message_id: 26,
    from: {
      id: 956528929,
      is_bot: false,
      first_name: 'Barabba',
      last_name: 'Extreme',
      language_code: 'it'
    },
    chat: {
      id: 956528929,
      first_name: 'Barabba',
      last_name: 'Extreme',
      type: 'private'
    },
    date: 1595766090,
    text: 'Ciao'
  },
  _msgid: 'e81b7c9b.103fd'
}

**Comment by windkh** [comment]
That is strange...

**Comment by Barabba11** [comment]
I apologize, this output is from debug node :( sorry I've just realize it now.
What about the polling issue?  Thanks for your kind support

**Comment by windkh** [comment]
I just wanted you to point into that direction....
