### ISSUE TITLE
Typo on 839 line in 99-telegrambot.js

### ISSUE THREAD

**Issue by tjunussov** [windkh/node-red-contrib-telegrambot#114]
On 839 line there code
`messageId: botMsg.message.message_id,`
must be
`messageId: botMsg.message_id,`

**Comment by windkh** [comment]
I will check this. What error was caused?

**Comment by windkh** [comment]
Hm yes you are right. I will fix it. Thanks for reporting!

**Comment by windkh** [comment]
fixed in version 8.3.0
