### ISSUE TITLE
Possible to introduce MTProxy support

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#117]
Hi! Thanks for kind support :) 
I'm living in Russia and here unfortunately we have the ban for the Telegram IP used by Telegram API, we need a proxy. Unfortunately Socks5 proxy are few and if you're lucky to find one working (with https) they usually arsn't stable, within 24h they die. 
It seems much more used and maybe reliable MTProxy, is it possible please to introduce it? Thanks

Ideally the best solution will be to indicate an url where the module download (update periodically) a list of updated Proxies, and when the used one it is not more working (timeout) it will try with the next one.. and cycle again

**Comment by Barabba11** [comment]
I?ve found about this 2 projects, bebe there is some useful code already ready there..
https://github.com/TelegramMessenger/MTProxy
https://github.com/zerobias/telegram-mtproto

**Comment by windkh** [comment]
MTProxy is as far as I know only available for clients that connect to the telegram server for pulling messages. That is not the same as the bot api...

**Comment by windkh** [comment]
Btw why is the telegram access blocked in russia?

**Comment by dvv** [comment]
It's not anymore )

**Comment by windkh** [comment]
Really?

**Comment by dvv** [comment]
Yep. Couple of days ago. Tested.

**Comment by windkh** [comment]
Yippieh! Thanks

**Comment by Barabba11** [comment]
Wow, they heard me, yes it works. I was waiting this for years, and I hope they will not change ideas. Thank you
