### ISSUE TITLE
Unable to connect, always ENOENT error

### ISSUE THREAD

**Issue by DotOnedotNL** [windkh/node-red-contrib-telegrambot#118]
I'm using node-red 1.1.2 with node.js 10.21.0. in a docker container
Both polling and webhook method return ENOENT error.
If I manually test the connection everything looks fine and I receive the expected response from Telegram.

**Polling error:**
node-red     | 15 Jul 10:32:31 - [warn] [telegram bot:be03dea.cd23d2] Unknown error. Trying again.
node-red     | 15 Jul 10:32:32 - [warn] [telegram bot:be03dea.cd23d2] EFATAL: Error: connect ENOENT /botXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY/getUpdates

**webhook error:**
node-red     | Unhandled rejection RequestError: Error: connect ENOENT /botXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY/setWebHook?certificate&url=https%3A%2F%2Ftelegram.domain.nl%3A8443%2FXXXXXXXXXX%3AYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
node-red     |     at new RequestError (/data/node_modules/request-promise-core/lib/errors.js:14:15)
node-red     |     at Request.plumbing.callback (/data/node_modules/request-promise-core/lib/plumbing.js:87:29)
node-red     |     at Request.RP$callback [as _callback] (/data/node_modules/request-promise-core/lib/plumbing.js:46:31)
node-red     |     at self.callback (/data/node_modules/request/request.js:123:22)
node-red     |     at Request.emit (events.js:198:13)
node-red     |     at ClientRequest.self.clientErrorHandler (/data/node_modules/request/request.js:244:10)
node-red     |     at ClientRequest.emit (events.js:198:13)
node-red     |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
node-red     |     at TLSSocket.emit (events.js:198:13)
node-red     |     at emitErrorNT (internal/streams/destroy.js:91:8)
node-red     |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
node-red     |     at process._tickCallback (internal/process/next_tick.js:63:19)

If I run a request using curl from within the docker container the response is correct:

**curl command:**
automation# docker exec -ti node-red /bin/bash
bash-5.0$
bash-5.0$ curl https://api.telegram.org/botXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY/getUpdates
{"ok":true,"result":[{"update_id":<ID>,
"message":{"message_id":7,"from":{"id":<ID>,"is_bot":false,"first_name":"firstname","last_name":"lastname","username":"username","language_code":"en"},"chat":{"id":<id>,"first_name":"firstname","last_name":"lastname","username":"username","type":"private"},"date":1594757153,"text":"test"}},{"update_id":451099358}]}

Webhook listener is working, when connecting to the physical machine interface I receive the expected response as well:

bash-5.0$ curl --tlsv1.2 -v -k https://192.168.1.60:8443/
*   Trying 192.168.1.60:8443...
* TCP_NODELAY set
* Connected to 192.168.1.60 (192.168.1.60) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=NL; ST=<state>; L=<town>; O=<org>; CN=telegram.<domain>; emailAddress=info@<domain>
*  start date: Jul 15 06:30:13 2020 GMT
*  expire date: Jul 13 06:30:13 2030 GMT
*  issuer: C=NL; ST=<state> L=<town>; O=<org>; CN=telegram.<domain>; emailAddress=info@<domain>
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> Host: 192.168.1.60:8443
> User-Agent: curl/7.67.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Wed, 15 Jul 2020 14:52:39 GMT
< Connection: keep-alive
< Content-Length: 0
<
* Connection #0 to host 192.168.1.60 left intact
bash-5.0$

Any help would be appreciated.

**Comment by windkh** [comment]
no idea... I have never seen this before

**Comment by DotOnedotNL** [comment]
Would there be anything else I can test.
It’s very strange that curl from within the container works as expected

**Comment by windkh** [comment]
Maybe you can try to use the http node within a flow... does that work?

**Comment by DotOnedotNL** [comment]
yes, I get the expected response in h http node when doing post.
I could set/delete a web as well as poll the status

**Set web hook**
"{"ok":true,"result":true,"description":"Webhook was set"}"

**Delete web hook**
"{"ok":true,"result":true,"description":"Webhook was deleted"}

**Poll result**
{"ok":true,"result":[{"update_id":451099358,
"message":{"message_id":8,"from":{"id":4<id>,"is_bot":false,"first_name":"xxxxxx","last_name":"xxxxxxx","username":"xxxxxx
.....

**Comment by windkh** [comment]
What fields did you use in the config node?

**Comment by DotOnedotNL** [comment]
For polling I used the Bot-name and token field only

For the webhook config I also added the domain name to connect to and the self-signed certificate
Both configs have the verbose logging enabled as well.

<img width="625" alt="Screenshot 2020-07-16 at 08 10 49" src="https://user-images.githubusercontent.com/19171666/87633787-4d799400-c73c-11ea-82a4-2782ea94d2b3.png">

**Comment by windkh** [comment]
Have you tried without certificate?

**Comment by windkh** [comment]
Running the bot with empty bot host works?

**Comment by DotOnedotNL** [comment]
Just tried.

If the certificate, the bothost or both are removed it will fallback to polling mode which returns the error as shown before.

**Comment by DotOnedotNL** [comment]
Also did a reinstall of the telegram node and removed all config, starting from scratch just to be sure.
to no avail, errors are still the same and connecting manually works.

**Comment by DotOnedotNL** [comment]
Not the I'd like to work but just to verify, I used a socks5 proxy and then at least polling works.

Setting the webhook works as well but certificate verification throws an error.
Not going to worry about it now, first try to solve the direct connection problem.

**Comment by DotOnedotNL** [comment]
Still haven't the faintest idea why this is happening.
All connections/posts, either from a http node or using curl are working from both inside and outside the container.
As soon as the connection is initiated from the Telegram node it fails with an ENOENT error.

**Comment by HenroRitchie** [comment]
Hi

I have the same issue. My exact error is: `Error: EFATAL: Error: connect ENOENT /bot***...***/sendMessage`. This is only on version 8.2.0. The exact same setup works fine on version 8.1.0.

Just doing a post to the group using the http nodes work fine.

**Comment by windkh** [comment]
Ok then I will check out what changed in 8.2 thanks

**Comment by windkh** [comment]
> Hi
> 
> I have the same issue. My exact error is: `Error: EFATAL: Error: connect ENOENT /bot***...***/sendMessage`. This is only on version 8.2.0. The exact same setup works fine on version 8.1.0.
> 
> Just doing a post to the group using the http nodes work fine.

In Version 8.2.0 the message object is cloned just right before sinding it away. I don't have any idea why this should be the root cause of the problem, but is anyone able to reproduce that error and willing to replace a few lines of code just to crosscheck that the problem is caused by those changes?

see also 
https://github.com/windkh/node-red-contrib-telegrambot/commit/041e129df032d3a648228709b14dc3f2e065d865

**Comment by DotOnedotNL** [comment]
I did a quick check reverting back  and use

                            msg.payload.chatId = chatId;
                             this.processMessage(chatId, msg, nodeSend, nodeDone);

doesn't make any difference.
I still get a fatal connection error

**Comment by windkh** [comment]
Did you also revert cloning the message object?

**Comment by DotOnedotNL** [comment]
Was away for a couple of days. will do some more testing this week

**Comment by windkh** [comment]
Any news?

**Comment by Hypfer** [comment]
I'm experiencing the same issue with `node-red-contrib-telegrambot@9.4.3`.
It was solved by manually adding the `request` module to the package.json of my node-red setup and running npm install.

Something seems to be broken regarding dependencies

**Comment by windkh** [comment]
Hm do you think that I should add request as dependency in my package.json then?

**Comment by Hypfer** [comment]
That shouldn't be required since the telegram bot lib does already depend on it:

https://github.com/yagop/node-telegram-bot-api/blob/master/package.json#L41

Very strange

**Comment by windkh** [comment]
So any suggestions?
