### ISSUE TITLE
sendInvoice

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-telegrambot#119]
new function

**Comment by windkh** [comment]
added alpha to 8.3.2 in github (not npm)

**Comment by windkh** [comment]
anyone tested this?

**Comment by windkh** [comment]
Test successful, waiting for example flow

**Comment by i-khanhandlethis** [comment]
sendInvoice works, but I am unable to receive the pre_checkout_query. Payment platform is setup correctly. 
Are there any existing methods to receive the pre_checkout_query?/

Perhaps the pre_checkout_query can be added to the events node 
Thanks!

**Comment by windkh** [comment]
@i-khanhandlethis yes you are right. I will add this. There is also a shippingQuery event. Do you need that one, too?
Could you do me a favour and test it for me? And maybe you could provide an example flow so that we have an example in the package?

**Comment by windkh** [comment]
added events in version 8.6.3. Please confirm.

**Comment by i-khanhandlethis** [comment]
Alright thank you. Will get back once I’m done testing

**Comment by i-khanhandlethis** [comment]
Hi! I am unable to test the latest update until the change has been pushed to node red. Currently github and NPM versions are at 8.6.4 and the node red version is at 8.6.1

**Comment by i-khanhandlethis** [comment]
Hi, I have been testing the nodes, and I can get a response from the pre checkout query event, and the shipping query event. 
However, I am not sure what fields to put pre_checkout_query under, and where to put ok:true.
I can successfully approve payment by inputting
`msg.url = "https://api.telegram.org/bot[bot api key]/answerPreCheckoutQuery?chat_id="+msg.payload.chatId+"&pre_checkout_query_id="+msg.payload.preCheckOutQueryId+"&ok=True"`
into a http request node, but it does not work when I put the two required fields under msg.payload.content or msg.payload.options. 

I tried to do the same for answering shipping query but it does not work too.

I will check out the source code to see how the library parses the fields into a http request once I have time to spare to figure this out. Wanted to give you an update for now. Thanks!

**Comment by windkh** [comment]
did you test the latest version yet?

**Comment by i-khanhandlethis** [comment]
Yes, testing was done with latest version. I have yet to look into the source code

**Comment by windkh** [comment]
Can you provide a flow so that I can add some documentation?

**Comment by windkh** [comment]
Hi @i-khanhandlethis, I want to close this issue... can you please provide an example flow?

**Comment by windkh** [comment]
closed for inactivity
