### ISSUE TITLE
sendVoice sends as file

### ISSUE THREAD

**Issue by psyntium** [windkh/node-red-contrib-telegrambot#12]
When sending buffered OGG to telegram, it sends as file, instead of voice.

msg.payload.type = "voice";
msg.payload.content = bufferredOgg;

bufferredOgg obtained from Watson Text to Speech. When the file sent by telegram is downloaded, the audio play normally on VLC.

**Comment by windkh** [comment]
Sorry for delay. What do you suggest?
Downloading the file and converting it via watson text to speech to a bufferedOgg?

**Comment by dvv** [comment]
@psyntium https://core.telegram.org/bots/api#sending-files "Sending by URL"

"To use sendVoice, the file must have the type audio/ogg and be no more than 1MB in size. 1–20MB voice notes will be sent as files."

Not your case?

**Comment by windkh** [comment]
@dvv
I asume that he wanted to point out an error when sending voice files, but I don't know how to reproduce this.

**Comment by dvv** [comment]
Mmm. I just see that "1–20MB voice notes will be sent as files" and ask _whether it is his case_.

**Comment by psyntium** [comment]
hi.. sorry for the late reply as well..
The voice file is short.. 3-5 seconds max. So I dont think it will be more than 1MB (which I may be mistaken). Previously it was working fine. So I'm not sure what changed. I will try it again and let u know the result.

**Comment by psyntium** [comment]
Ok it seems to be working now. I'll close this then. Maybe it was telegram issue, or the TTS formatting that went wrong. anyway, thanks for all your support! appreciate it
