### ISSUE TITLE
examples flows not available at https://flows.nodered.org/node/examples/...

### ISSUE THREAD

**Issue by stefan242** [windkh/node-red-contrib-telegrambot#120]
However, in the last line I can read:

"All example flows can be found in the examples folder of this package."
Please direct all example flow links to THIS sentence.

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/tree/master/examples

**Comment by windkh** [comment]
I don‘t understand your problem

**Comment by stefan242** [comment]
On https://flows.nodered.org/node/node-red-contrib-telegrambot you show screenshots of flows and link to the correspondig flow file.
However all links point to https://flows.nodered.org/node/examples/<filename>.json and cannot be found: 

> 404 - Thing not found

**Comment by windkh** [comment]
Well, the links are in the readme.md of the github root folder pointing to the relative subdir. I did not publish anything on flows.nodered.org...
