### ISSUE TITLE
[Bug]: package seems to require global installation 

### ISSUE THREAD

**Issue by namtab00** [windkh/node-red-contrib-telegrambot#121]
```
PS C:\Dev\product-node-red> node -v ; npm -v
v12.16.2
6.14.5
```

Installation via npm (not globally) via:
`npm install node-red-contrib-telegrambot@^8.4.0 --save`

installs the package locally in node_modules, but then causes node-red to hang on loading nodes:

![image](https://user-images.githubusercontent.com/995900/90626148-d80d5180-e21a-11ea-8de2-44689da73ecc.png)

![image](https://user-images.githubusercontent.com/995900/90626816-afd22280-e21b-11ea-9e5f-b1fb2d8302a8.png)

Installation via the Palette Manager yields error:

![image](https://user-images.githubusercontent.com/995900/90625529-050d3480-e21a-11ea-907d-c073b912f10e.png)

![image](https://user-images.githubusercontent.com/995900/90625553-0fc7c980-e21a-11ea-995c-003f49d1e0a2.png)

Log:
```
-----------------------------------------------------------
2020-08-19T10:46:45.094Z Install : node-red-contrib-telegrambot 8.4.0

2020-08-19T10:46:45.110Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-telegrambot@8.4.0
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
2020-08-19T10:46:49.733Z [out] + node-red-contrib-telegrambot@8.4.0
2020-08-19T10:46:49.733Z [out] added 85 packages from 134 contributors in 3.72s
2020-08-19T10:46:49.756Z rc=0
```
node-red-contrib-telegrambot seems to depend on deprecated packages:

- request-promise@4.2.6
- request@2.88.2
- har-validator@5.1.5

Please see https://github.com/request/request/issues/3143

**Comment by windkh** [comment]
Yes I know, but replacing request is not a 5minutes task.

**Comment by windkh** [comment]
Installation generates the following input, but succeeds from within the pallet manager in the side bar

![image](https://user-images.githubusercontent.com/10910767/92332725-224a5b80-f080-11ea-9467-d4e3dd34c802.png)

**Comment by windkh** [comment]
can not reproduce that installation hangs.

**Comment by windkh** [comment]
closed as not reproducible and due to inactivity.
