### ISSUE TITLE
Allow command regex

### ISSUE THREAD

**Issue by jsBlackBelt** [windkh/node-red-contrib-telegrambot#122]
Hi,

I'd like to use command regex. 
The reason is that I want to support commands of the form `/toggle_type_key` so `/toggle_ac_room` will toggle ac in room and `/toggle_fan_lounge` will toggle lounge fan.
Since this is dynamic in nature, it is not feasible to create specific command nodes for all permutations.

Currently, the command node only accepts a hard coded string as the command to react to.

**Comment by windkh** [comment]
Hi @jsBlackBelt I could implement that, but why do you not call it using an argument
`/toggle fan_lounge` and `/toggle ac_room`
You would only need one command and a function or switch node. You can already do this.

**Comment by jsBlackBelt** [comment]
Because it is not clickable.
The way I use it is:
/what_is_on
Which reaponds with:
/toggle_ac_room
/toggle_fan_lounge

And I can click on either to make it run

**Comment by jsBlackBelt** [comment]
![SmartSelect_20200825-200510_Telegram](https://user-images.githubusercontent.com/7566666/91205653-92ff8880-e70e-11ea-96af-1bccb8de6337.jpg)

**Comment by jsBlackBelt** [comment]
Having the ability to respond to a command of the form `^\/toggle_.*$` with a function node that routes by the msg payload to the relevant service call, would be ideal! :)

**Comment by windkh** [comment]
Hm ok I see. The better way to achieve your use case would be an keyboard with buttons. Have you seen the example?

**Comment by jsBlackBelt** [comment]
Yes, I saw it and am using it on another scenario - specifically for turning on devices.
I can use the keyboard for this as well, but the "what_is_on" list might be long that's why I prefer to use message text with clickable commands.

How complicated it is to implement command regex?

**Comment by windkh** [comment]
Hm should be no big deal, but I want to avoid sideeffects with existing flows

**Comment by jsBlackBelt** [comment]
You could add another command type: regex and so existing flows currently using str will not be affected while regex type will use the new code that handles regex.

This  (no longer maintained and less feture-rich) alternative does exactly that.
https://github.com/scraton/node-red-contrib-telegrambot-home/blob/master/nodes/command/command.js

**Comment by windkh** [comment]
I will avoid introduction of a new node, but maybe I will add a checkbox in the configuration „use regex“

**Comment by jsBlackBelt** [comment]
I didn't mean a new node. But you can allow users to name the command as string or as regex, a checkbox will work, or a dropdown selector

**Comment by windkh** [comment]
I will implement it...

**Comment by jsBlackBelt** [comment]
Thanks!

**Comment by windkh** [comment]
see version 8.7.0

**Comment by jsBlackBelt** [comment]
🤘
Thank you! Will test it out asap!

**Comment by twocolors** [comment]
@windkh 
thx for support regex, you not think if "use regex" replace remainingText to number match (Group)

example: 
^\/toggle_.*\s(.*)$ - number 1

like
<img width="484" alt="Screenshot 2020-11-16 at 23 27 26" src="https://user-images.githubusercontent.com/207796/99304438-6b2e4580-2863-11eb-897b-63aab6105cfb.png">

**Comment by twocolors** [comment]
@windkh thx for support regex, you not think if "use regex" replace remainingText to number match (Group)

example: 
^\/toggle_.*\s(.*)$ - number 1

like
<img width="464" alt="Screenshot 2020-11-16 at 23 29 42" src="https://user-images.githubusercontent.com/207796/99304656-b2b4d180-2863-11eb-895a-07aa119e5384.png">

**Comment by twocolors** [comment]
hm or replace match[1] , all command will like
```
^(\/toggle_.*)\s(.*)$ - > /toggle_test mimi -> ' mimi'
```

**Comment by windkh** [comment]
@twocolors ... sorry I have no clue what you want to tell me.

**Comment by twocolors** [comment]
when we use regex in a command, we get a remainingText with the beginning of the command
```
^ (\ / toggle _. *) \ s (. *) $ -> /toggle_test mimi
```

I suggest replacing the first match with ""  , to get clean remainingText without command

```
var remainingText;
                                if (isDirectCommand) {
                                    remainingText = message.replace(command2, "");
                                }
                                else {
                                    remainingText = message.replace(command, "");
                                }

if (isRegExMatch) {
  var match = regex.exec(message);
  if (match[1].startsWith("/")) {
    remainingText = message.replace(match[1], "");
  } 
}
```

**Comment by windkh** [comment]
Ah ok I see your point.... yes that would make sense

**Comment by jsBlackBelt** [comment]
So we would be getting both, the command and the remainingText, separate?

**Comment by windkh** [comment]
@jsBlackBelt... no only the remaining text as @twocolors wants the command being removed completely. Do you need the command string?

**Comment by jsBlackBelt** [comment]
Well, yeah.
Otherwise how would you determine /toggle_something from /toggle_anotherthing?

**Comment by windkh** [comment]
Indeed that was what I thought initially. I could add another property with the regex matches to not harm existing implementations

**Comment by jsBlackBelt** [comment]
I feel the command and any remainingText should be passed in whole so to not break axisting usages. Separating it in the command handling code is simple enough.

**Comment by twocolors** [comment]
@jsBlackBelt you are right, but why is now if not use "regexp" separator and command remove ?

**Comment by jsBlackBelt** [comment]
If you remove the command, you eliminate the possibility of using regex on commands without remaining text.

On the other hand, returning both commnd and remaining text and delegating the handling node to do whatever applies opens up possibilities instead of eliminating them, and also does not break existing flows.

**Comment by windkh** [comment]
A regex command could contain address information. A standard static command string does not

**Comment by twocolors** [comment]
I suggest deleting the command if it match[1] and start /

```
^\/toggle_.* mimino -> /toggle_ac_room mimino
^(\/toggle_.*) mimino -> mimino
```

**Comment by jsBlackBelt** [comment]
And your suggestion is exactly what will break existing functionality. Considering the alternative is really simple, I see no reason to introduce a breaking change

**Comment by windkh** [comment]
agreed

**Comment by twocolors** [comment]
@jsBlackBelt why breaks? you example 
```
^\/toggle_.*$
```
not change.

On the other hand, you have more experience and know better.

**Comment by windkh** [comment]
I will add an option for removing the command if regex is enabled. Makes it not breaking existing code but a little bit more complex when it comes to understand the usage of the node.

**Comment by windkh** [comment]
added flag in version 8.9.3
