### ISSUE TITLE
Option saveDataDir: How does it works?

### ISSUE THREAD

**Issue by StephanStS** [windkh/node-red-contrib-telegrambot#125]
In the description there is an option saveDataDir.
In the Configuration Node there is no property to set this value.
How can it be set?

BTW: I have forked the node and will work on some documentation rework/enhancement. I then will issue a pull request if I am finished.

**Comment by windkh** [comment]
It is a property in the receiver node

**Comment by windkh** [comment]
Yes the description should be under the receiver node instead of the configuration node... I will fix this

**Comment by StephanStS** [comment]
I am working on the docu rework, so you can lean back and wait for my pull request of Readme.md.

**Comment by windkh** [comment]
So what are you going to rework? I am curious...

**Comment by StephanStS** [comment]
I want to do some enhancements to the documentation: Beautifications, clearifications, typos, etc.
No big changes.

**Comment by windkh** [comment]
Thanks in advance...

**Comment by StephanStS** [comment]
As an example compare
https://github.com/eschava/node-red-contrib-hourglass/tree/01ac5646ba5ffa9d95dcecfca11f5d666676847e
with
https://github.com/eschava/node-red-contrib-hourglass
:-)

**Comment by Barabba11** [comment]
Precious work!

**Comment by StephanStS** [comment]
You can "follow" the work on https://github.com/StephanStS/node-red-contrib-telegrambot.

**Comment by ozett** [comment]
do you keep all the config-information in this over-long readme.md?
difficult to scroll and jump from top to bottom because all infos only on this one page..

why dont you do this (like most others) in a structured wiki on github?

**Comment by StephanStS** [comment]
I am not familiar with a structured wiki, so the only think I can do would be to insert an table of contents on the top of the page. 

In another case (node-red-contrib-finite-statemachine) we divided the Readme.md into a short version and a longer Manual.md. This could also be an option.
@windkh: What is your proposal to go on?

**Comment by windkh** [comment]
> do you keep all the config-information in this over-long readme.md?
> difficult to scroll and jump from top to bottom because all infos only on this one page..
> 
> why dont you do this (like most others) in a structured wiki on github?

Well, because it grew over time and moving it into a wiki is time consuming.... if anyone would do this I would be glad

**Comment by windkh** [comment]
> I am not familiar with a structured wiki, so the only think I can do would be to insert an table of contents on the top of the page.
> 
> In another case (node-red-contrib-finite-statemachine) we divided the Readme.md into a short version and a longer Manual.md. This could also be an option.
> @windkh: What is your proposal to go on?

Just add your changes to the existing readme... maybe I will open a wiki in future
