### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by StephanStS** [windkh/node-red-contrib-telegrambot#126]
### Function of configuration property "Server URL" in the configuration node?
The documentation does not tell enough about the Configuration Node property *Server URL*.
The description is: *The API Base URL can be changed for testing or when using a proxy.*
What does this mean resp. how can this be used?

### Sender node
Does the sender node only needs the input `msg.payload` properties 
- chatId
- type
- content?
I assume that the incoming `msg` is repeated to the node's output and - in case of an error - another property `error` is added. Is that right?

I would takeover this in the Readme.md.

**Comment by windkh** [comment]
This is the server url of the telegram server (https://api.telegram.org). If you would install another instance of a telegram server somewhere else (e.g. on premise) you could then use this property to connect to that server instead the global one.

**Comment by windkh** [comment]
> ### Function of configuration property "Server URL" in the configuration node?
> The documentation does not tell enough about the Configuration Node property _Server URL_.
> The description is: _The API Base URL can be changed for testing or when using a proxy._
> What does this mean resp. how can this be used?
> 
> ### Sender node
> Does the sender node only needs the input `msg.payload` properties
> 
> * chatId
> * type
> * content?
>   I assume that the incoming `msg` is repeated to the node's output and - in case of an error - another property `error` is added. Is that right?
> 
> I would takeover this in the Readme.md.

Well, the received message is cloned and can be directly reused by the sender node.
Content heavily depends on the type of message.
I believe if would be best to make a table with an example content and a description for every message type.

**Comment by StephanStS** [comment]
Sender node: Another option could be to describe inputs and outputs at every of the 5 nodes (and possibly add a screenshot of a msg debug output as an example to show the msg structure).
I will do this for one node an then you can review this basic description structure whether we want to have this for all 5 nodes.

**Comment by StephanStS** [comment]
Do you mean a table which describes the logic within the function getMessageDetails(botMsg)?
E.g. a table with these coloumns:
- text: chatId, messageId, type (= "message"), content (text)
- photo: chatId, messageId, type (= "photo"), content (photo[index].file_id with index = different photo sizes), caption, date, blob (= true), photos (???), mediaGroupId
- audio: chatId, messageId, type (= "audio"), content (file_id), cation, date, blob (= true)
...

**Comment by windkh** [comment]
Yes exactly

**Comment by StephanStS** [comment]
@windkh: In the Readme.md there could be another flow added.
Pls could you look at my GitHub branch ([dynamic authorization flow](examples/dynamicauthorization.json)) and check for 'xxx' in the text to find the position where I'd like to have a flow. You may post the desired flow here and I will do the rest (screenshot, etc.).

For the rest I hope that I am finished for the first time.
Possibly I will redo some of the screenshots for a bit more beautification.

After this I will issue a pull request and afterwards try to add the table like described above.

**Comment by windkh** [comment]
Just make a pull request and then I can see the final result. You can still alter the changes after you made the pull request so don't worry.

**Comment by StephanStS** [comment]
You can see a sneak preview there: https://github.com/StephanStS/node-red-contrib-telegrambot.
Actually I am working at the table and some screenshot beautifications, afterwards I do the pull request.

**Comment by Barabba11** [comment]
Really well done!

**Comment by windkh** [comment]
> You can see a sneak preview there: https://github.com/StephanStS/node-red-contrib-telegrambot.
> Actually I am working at the table and some screenshot beautifications, afterwards I do the pull request.

Do not forget to enter yourself in the credits list of the readme.md

**Comment by StephanStS** [comment]
I am working on the table and have some questions:

- Is there a reason why there is no *date* element in case of type **message**? All other types contain a date
- *date* element:
  - Are all date elements are mandatory or optional? 
  - Are there differences in receive and send? E.g.: Receive - *date* is always set, Send - *date* is optional
- *video_note*
  - In 99-telegrambot.js the *caption* element listed. 
  - In https://core.telegram.org/bots/api#sendvideonote there is no caption option
  - What is correct?
- How is the format of `content: botMsg.location` in case of "location"? 
  - In the api there are two floats: latitude and longitude. How is the formatting of the content field?

See the table *Tab.1* in https://github.com/StephanStS/node-red-contrib-telegrambot. There you should see the background of my questions. Otherwise we also could do a quick phone call (in german language) to clearify this.

**Comment by windkh** [comment]
> I am working on the table and have some questions:
> 
> * Is there a reason why there is no _date_ element in case of type **message**? All other types contain a date
> * _date_ element:
>   
>   * Are all date elements are mandatory or optional?
>   * Are there differences in receive and send? E.g.: Receive - _date_ is always set, Send - _date_ is optional
> * _video_note_
>   
>   * In 99-telegrambot.js the _caption_ element listed.
>   * In https://core.telegram.org/bots/api#sendvideonote there is no caption option
>   * What is correct?
> * How is the format of `content: botMsg.location` in case of "location"?
>   
>   * In the api there are two floats: latitude and longitude. How is the formatting of the content field?
> 
> See the table _Tab.1_ in https://github.com/StephanStS/node-red-contrib-telegrambot. There you should see the background of my questions. Otherwise we also could do a quick phone call (in german language) to clearify this.

message date:
Yes date is missing in message, I will add this.


video_note:
yes seems to be a copy paste error. The documentation says
'Optional. Caption for the animation, audio, document, photo, video or voice, 0-1024 characters'

location: 
see https://core.telegram.org/bots/api#location
