### ISSUE TITLE
Receiver doesn't filter restricted commands

### ISSUE THREAD

**Issue by joeyave** [windkh/node-red-contrib-telegrambot#133]
Telegram Receiver handles commands in groups (such as `@help/@SomeBot`) as an ordinary message.

**Comment by windkh** [comment]
Then activate strict mode. See config node:

`
Strict in group chats flag: To avoid that the bot handles commands that are not directly sent to it using the long notation (e.g. /foo@YourBot) you can set the "strict" mode in the options of the command node. In this case the bot only accepts the full command notation in group chats.

`
