### ISSUE TITLE
Payload.messageId information when using -Event node- with -Callback Query- parameter

### ISSUE THREAD

**Issue by vovadpua** [windkh/node-red-contrib-telegrambot#136]
Good afternoon. Sorry for my bad english. I recently updated node-red-contrib-telegrambot to version 8.7.1 and found such a frustrating moment for me.
When I use -Event node- in version 8.7.1 and want to get -Callback Query- when I click on a button on the built-in keyboard, it no longer returns the payload.messageId parameter, although in version 6.0.0 I can get the payload.messageId value.
Is it possible to return this value back when receiving a message from -Event node- with the -Callback Query- parameter

I use this information when the bot receives data from the user about pressing the keyboard and the bot after clicking the button deletes this message with the keyboard.

Thank you very much for your work.

**Comment by windkh** [comment]
Hi @vovadpua I did not intend to remove the messageId ... so thanks for reporting this.
Can you reproduce that with one of the example flows that are shipped with the package?
If not, please provide an example flow so that I can reproduce that.
Maybe the underlying lib changed its behaviour... I will try to fix it as soon as possible.

**Comment by vovadpua** [comment]
Thanks for your quick answer. Here is a small code taken from your examples with the addition of the "close" function, when you click on the "close" button in version 6.0.0 it is executed correctly, but in the new version 8.7.1 messageId is not available.



` [{"id":"4a52823a.0b717c","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"5217fabc.762f44","type":"debug","z":"4a52823a.0b717c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":510,"y":100,"wires":[]},{"id":"1590f205.372e7e","type":"catch","z":"4a52823a.0b717c","name":"","scope":null,"x":260,"y":100,"wires":[["5217fabc.762f44"]]},{"id":"f8f1177e.f386e8","type":"telegram event","z":"4a52823a.0b717c","name":"","bot":"45a15ccb.8c3894","event":"callback_query","autoanswer":true,"x":280,"y":160,"wires":[["7ffb69d7.ffe338","4b911cb1.656614"]]},{"id":"34856fb4.95731","type":"telegram sender","z":"4a52823a.0b717c","name":"show inline keyboard","bot":"45a15ccb.8c3894","x":820,"y":240,"wires":[[]]},{"id":"2b3b4dcf.736b12","type":"function","z":"4a52823a.0b717c","name":"inline keyboard message","func":"var opts = {\n  reply_to_message_id: msg.payload.messageId,\n  reply_markup: JSON.stringify({\n    \"inline_keyboard\": [[\n                {\n                    \"text\": \"Yes\",\n                    \"callback_data\": \"FOO YES\"            \n                }, \n                {\n                    \"text\": \"No\",\n                    \"callback_data\": \"FOO NO\"            \n                },\n                {\n                    \"text\": \"Close\",\n                    \"callback_data\": \"Close\"            \n                }]\n            ]\n  })\n};\n\nmsg.payload.content = 'Are you sure?';\nmsg.payload.options = opts;\n\nreturn [ msg ];\n","outputs":"1","noerr":0,"x":550,"y":240,"wires":[["34856fb4.95731"]]},{"id":"bf7f8141.c3da5","type":"telegram command","z":"4a52823a.0b717c","name":"/foo","command":"/foo","bot":"45a15ccb.8c3894","strict":false,"x":250,"y":240,"wires":[["2b3b4dcf.736b12"],[]]},{"id":"7ffb69d7.ffe338","type":"function","z":"4a52823a.0b717c","name":"set  answer options","func":"var show_alert = false; // you can set this to true to open a dialog with the answer in the client.\n\n// msg.payload.content contains the callback data from the keyboard.\n// You may change this value here.\nmsg.payload.options = show_alert;\n\nreturn [ msg ];\n","outputs":"1","noerr":0,"x":530,"y":160,"wires":[["8eee149d.464a88","45f03f47.35466"]]},{"id":"8eee149d.464a88","type":"telegram sender","z":"4a52823a.0b717c","name":"answer callback query","bot":"45a15ccb.8c3894","x":820,"y":160,"wires":[[]]},{"id":"45f03f47.35466","type":"debug","z":"4a52823a.0b717c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":820,"y":100,"wires":[]},{"id":"4b911cb1.656614","type":"function","z":"4a52823a.0b717c","name":"Close","func":"\n\n    \n   if (msg.payload.content == 'Close') {msg.payload.type = 'deleteMessage';\n    msg.payload.content = msg.payload.messageId\n   \n    return  msg;}\n\nreturn msg;","outputs":1,"noerr":0,"x":530,"y":200,"wires":[["8eee149d.464a88"]]},{"id":"45a15ccb.8c3894","type":"telegram bot","z":"","botname":"wv Bot","usernames":"vovadpua","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}] `
