### ISSUE TITLE
Commands stop listening after deploy

### ISSUE THREAD

**Issue by philosoma** [windkh/node-red-contrib-telegrambot#137]
Hey, thanks for this node!

I have a problem with commands. Using your example for /help and a list, it all works well until I make changes to Node Red and click deploy (modified flows option). The command /help is then ignored until full flow deploy or a Node Red restart. Not doing anything fancy yet. Sometimes another command will work. Even starting a new project with a command node and debug, deploying again stops commands outputting anything.

Also, very minor, unticking 'has response output' correctly shows only 1 output, but if you refresh the page two are shown.

Thanks for any help!

**Comment by windkh** [comment]
You should always do a full deploy to avoid problems with partial deploys.

I will try to reproduce the has response output problem. Thanks for reporting.

**Comment by philosoma** [comment]
But I love my partial deploys! Maybe it's time to set up a second Node Red as a playground.

Thanks for looking in to the output problem!

**Comment by windkh** [comment]
Well, I just tried to reproduce your partial deploy problem. However I failed.

What browser do you use and what version of the telegram bot nodes?

**Comment by philosoma** [comment]
Sometimes it deploys fine and I can't reproduce it. Other times it fails on deploy, even on flows not using your node. I am using Chrome Version 86.0.4240.183 which is latest, Node Red at 1.2.3 on a Pi 4 (all updated) and Telegrambot is 8.7.1.

I will try Firefox and I'll get another Node Red going in a docker and report back.

**Comment by philosoma** [comment]
I did setup another Node-RED, only a few nodes copied over, could not reproduce the issue. Strangely my main install has been working all today even after at least 100 deploys (none of them full).
