### ISSUE TITLE
Using the restrictChatMember method to selectively block permissions

### ISSUE THREAD

**Issue by vovadpua** [windkh/node-red-contrib-telegrambot#138]
Good afternoon, I ask for your help, I have not found the answer to this question anywhere else. I want to make the chat bot an administrator, I added the bot to the super group administrators, I use the restrictChatMember method, set the ChatPermissions for can_send_messages, true, but the bot blocks all permissions. Please tell me what the structure of the message should be in order to selectively block the chat user, for example, allow only to write messages.
I tried different options, but all permissions are blocked at once.

For example code like this:

```
var options = {
    until_date: Math.round(((new Date()).getTime() + 60000) / 1000),
    ChatPermissions : {can_send_message: true,
    can_invite_users: true}
   
}

var payload = {
    chatId: -134543807833,
    type: "restrictChatMember",
    content: 1154459671,
    options: options
}

msg.payload = payload

return msg
```

**Comment by windkh** [comment]
I will answer asap... which is tomorrow

**Comment by vovadpua** [comment]
Thank you very much, I will wait for your reply.

**Comment by windkh** [comment]
I would do it like this

`
var options = {
    permissions : {can_send_message: true,
    can_invite_users: true},
    until_date: Math.round(((new Date()).getTime() + 60000) / 1000),
}

var payload = {
    type: "restrictChatMember",
    chatId: <supergroupid here>,
    content: <userid here>,
    options: options
}

msg.payload = payload;

return msg;
`
However I could not test it completely as I instructed the bot to remove me (as I am the only one in the group with the bot) and then I got an exception:
"ETELEGRAM: 400 Bad Request: can't remove chat owner"

**Comment by vovadpua** [comment]
Unfortunately, all the same, it is impossible to make selective blocking, to restrict only some functions, for example, to write messages to the supergroup. Method itself works "restrictChatMember" works, but telegram does not receive permissions data.  It is logical that Telegram does not allow you to blame yourself, since you are an administrator. This indicates that the "restrictChatMember" method works, but it does not receive permissions data. May I ask you again when you have time to see the execution of this method. If you need a user for testing, you can add me to your supergroup and try to block only some functions, for example, block writing messages. My nickname in telegram @vovadpua
Thanks again for your work and would appreciate it if you come back to this question.

**Comment by windkh** [comment]
sure i will try again

**Comment by windkh** [comment]
Here the full permission options:

'''
var options = {
    permissions : {
        can_send_messages : false,
        can_send_media_messages : false,
        can_send_polls : false,
        can_send_other_messages : false,
        can_add_web_page_previews : false,
        can_change_info : false,
        can_pin_messages : false,
        can_invite_users: true },
    until_date: Math.round(((new Date()).getTime() + 60000) / 1000),
}

var payload = {
    type: "restrictChatMember",
    chatId: <super group id here>,
    content: <user id here>,
    options: options
}

msg.payload = payload;

return msg;
'''
