### ISSUE TITLE
Caption doesn´t work in "send photo"

### ISSUE THREAD

**Issue by kaypohl** [windkh/node-red-contrib-telegrambot#14]
This is my function:
`msg.payload = {chatId : 31911111, type : 'photo', content : msg.payload, caption : 'Es hat geklingelt'}
return msg;`

I got the photo but without caption. I'm doing something wrong here ?

Kay

**Comment by windkh** [comment]
I guess caption is not passed through right now. I will add a caption parameter soon.

**Comment by kaypohl** [comment]
That would be great. Thanks

**Comment by windkh** [comment]
You can already achieve this with the current version by setting the caption in the options:

Please try the following:
```
msg.payload = {chatId : 31911111, type : 'photo',  content : msg.payload} 
msg.payload.options = {caption : 'Es hat geklingelt'};
return msg;

```

I will adapt the sender node to be able to set the caption the way you intended to.

**Comment by kaypohl** [comment]
It works great. Thanks for your support.

Kay

**Comment by kaypohl** [comment]
Do you think about adding posibility for emotion icons in Telegram for Node Red ?

**Comment by windkh** [comment]
What do you exactly need? 
Emojis are transfered as text message. You can already send em the only thing you have to know is the encoding:
Hallo ☹️

see https://apps.timwhitlock.info/emoji/tables/unicode

**Comment by kaypohl** [comment]
When i try to add an emoji as text it doesn´t work. I don´t know about the encoding. I try w

`msg.payload = {chatId : 319975309, type : 'photo', content : msg.payload, caption : 'Es hat geklingelt'}
msg.payload.options = {caption : 'Es hat geklingelt \xF0\x9F\x94\x94'};
return msg;
`
I try to get a bell emoji in my text.

**Comment by windkh** [comment]
Fixed in 2.2.0

**Comment by windkh** [comment]
Simply send a bell to the bot and have a look in the debug tab what you received. Copy that into your message.

**Comment by kaypohl** [comment]
Thats works. Thanks again
