### ISSUE TITLE
deletion of the whole msg content

### ISSUE THREAD

**Issue by WollexD** [windkh/node-red-contrib-telegrambot#141]
https://github.com/windkh/node-red-contrib-telegrambot/blob/5b2d043144e8525efd360e3689fc309a8fab3e09/telegrambot/99-telegrambot.js#L1778

Hello everyone, is there a special reason why the entire content of msg is overwritten in this program line? 
Thereby, it is unfortunately not possible to pass values ​​through this node.

For example a set: msg.test = 1
is no longer available after the reply node.

Can you please make that possible. 
thank you

**Comment by windkh** [comment]
I will clone the message for you, should not be a big thing....

**Comment by windkh** [comment]
in version 8.8.0 you can pass the options like:

```
var message = msg.payload.sentMessageId;

var options = {
    disable_notification: true
}

var payload = {
    type: "pinChatMessage",
    chatId: chatId,
    content: message,
    options : options
}

msg.payload = payload;

return msg;
```

**Comment by WollexD** [comment]
Hello Karl, 
do you know until when it will be updated on the Node-Red site?
https://flows.nodered.org/node/node-red-contrib-telegrambot
Thank You
