### ISSUE TITLE
send message error handling

### ISSUE THREAD

**Issue by DarkPark** [windkh/node-red-contrib-telegrambot#142]
Is there a way to handle errors in the Sender Node?
The catch node is not triggered and Sender Node is not producing any payload.
Please advise.

**Comment by windkh** [comment]
I guess this issue is a duplicate

**Comment by windkh** [comment]
fixed in version 8.9.9

**Comment by windkh** [comment]
A message containing the exception and the causing message object is printed using node.error.

**Comment by windkh** [comment]
I could add a second output which would be triggered in case of an exception. So the question is if you want to handle the error in the sender on your own or if you would like to abort the whole flow?

**Comment by windkh** [comment]
Then I will implement an optional second output

**Comment by windkh** [comment]
Please check version 8.9.1
![TelegramBotErrorHandling](https://user-images.githubusercontent.com/10910767/100551844-a711d380-3283-11eb-900a-83f0c0a063b2.png)

**Comment by DarkPark** [comment]
I'm testing with empty content and unfortunately neither second output nor catch node is triggered.

**Comment by windkh** [comment]
That is ok

**Comment by DarkPark** [comment]
But the message was not sent. It's not a normal situation and it would be nice to be able to react.

Besides I see that the second output has data even when there are no errors.

**Comment by windkh** [comment]
Right now empty content is ignored... no content = nothing to send. The 2nd output should not send anything. I will check that

**Comment by windkh** [comment]
> Besides I see that the second output has data even when there are no errors.

@DarkPark I can not reproduce that. On my machine only one output is triggered. Can you please recheck?

**Comment by windkh** [comment]
> But the message was not sent. It's not a normal situation and it would be nice to be able to react.

A warning is issued in this case. I don't dare to change that behavior to not break existing bots.

**Comment by DarkPark** [comment]
I'm very sorry but can't reproduce it either.
Thank you for your work :)
