### ISSUE TITLE
Setting the webhook does not work

### ISSUE THREAD

**Issue by Diddlik** [windkh/node-red-contrib-telegrambot#146]
I'm trying to set up the bot with webhook, but after deploy i get the error message and it switches to pooling. 

environment:
- Node-Red installed as Addon in Home Assistant
- Home Assistant can be reached from outside via https: https://ha.mydomain.com
- Node-Red has the following address from outside: https://ha.mydomain.com/aaa7bt54_nodered

Can somebody help me to setup it?

![grafik](https://user-images.githubusercontent.com/6010713/100928375-6796f180-34e6-11eb-95de-e997bb26f273.png)

**Comment by windkh** [comment]
I can not see a cert! Please read the tip at the bottom and the readme.

**Comment by Diddlik** [comment]
But Home Assistant and Addons are behind reverse proxy, do I need in this case cert?

**Comment by windkh** [comment]
Hier Herr Schaf ;)
https://github.com/windkh/node-red-contrib-telegrambot#webhook-mode

Ich denke am Zertifikat kommst nicht vorbei

**Comment by windkh** [comment]
Vielleicht auch so
https://github.com/windkh/node-red-contrib-telegrambot/pull/93

**Comment by Diddlik** [comment]
Gefüllt habe ich 100 mal gelesen, ich gehe das noch ein mal durch. Irgendwo habe ich Denkfehler. 

Danke ;)

**Comment by windkh** [comment]
Was kommt für ein Fehler?

**Comment by Diddlik** [comment]
msg : string[75]
"Configuration data for webhook is not complete. Defaulting to polling mode."

**Comment by windkh** [comment]
openssl req -newkey rsa:2048 -sha256 -nodes -keyout PRIVATE.key -x509 -days 365 -out PUBLIC.pem -subj "/C=NG/ST=Lagos/L=Lagos/O=SchafBot/CN= https://ha.mydomain.com/aaa7bt54_nodered"

**Comment by windkh** [comment]
Einfach cert erstellen

**Comment by windkh** [comment]
Ich glaube ich erstelle noch ein makecert.bat das man einfach aufrufen kann

**Comment by Diddlik** [comment]
Bin Stück weiter gekommen, aber jetzt kommt in dem Log:

`Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook: Failed to resolve host: No address associated with hostname
    at /config/node-red/node_modules/node-telegram-bot-api/src/telegram.js:284:15
    at tryCatcher (/config/node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/config/node-red/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/config/node-red/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/config/node-red/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/config/node-red/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/config/node-red/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/config/node-red/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/config/node-red/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/config/node-red/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)`

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/makecert.bat

your bot host should be ha.mydomain.com/aaa7bt54_nodered without https://

**Comment by windkh** [comment]
I updated the readme and added that makecert.bat under examples to ease creation of the cert. Good luck!

**Comment by Diddlik** [comment]
Was ich noch heraus fand. Der Port wird am Ende angehäng und nicht direkt nach dem domain.
Etwa so: https://ha.mydomain.com/aaa7bt54_nodered:443/token, somit ist es nicht erreichbar. Sollte es nicht:
https://ha.mydomain.com:443/aaa7bt54_nodered/token sein?
var botUrl = "https://" + this.botHost + ":" + this.publicBotPort + "/" + this.token;

**Comment by windkh** [comment]
An sowas habe ich nicht gedacht bin immer von einer Domain ohne Anhängsel ausgegangen

**Comment by Diddlik** [comment]
Das Problem hat man min Anhängsel wenn man Node_red in Home Asisstant oder in CCU3 bei HomeMatic IP nutzt. 
Es wird immer als subfolder definiert.
Ich mache morgen in nginx die Anpassung, so dass Red-Node direkt als subdomain wird. Als workaround sollte es gehen

**Comment by windkh** [comment]
> Was ich noch heraus fand. Der Port wird am Ende angehäng und nicht direkt nach dem domain.
> Etwa so: https://ha.mydomain.com/aaa7bt54_nodered:443/token, somit ist es nicht erreichbar. Sollte es nicht:
> https://ha.mydomain.com:443/aaa7bt54_nodered/token sein?
> var botUrl = "https://" + this.botHost + ":" + this.publicBotPort + "/" + this.token;

ich werde das demnächst richten... wäre schön, wenn du das dann ausprobieren könntest.

**Comment by Diddlik** [comment]
Ich habe es direkt in dem Bot COde angepasst, jetzt wir der Webhook link richtig generiert:

![grafik](https://user-images.githubusercontent.com/6010713/100984187-aa8ab080-354a-11eb-947b-cec69c1011db.png)

**Comment by windkh** [comment]
Kannst dazu einen pull request machen?
