### ISSUE TITLE
Why can't forward the message to the chat where it comes from?

### ISSUE THREAD

**Issue by doucreator** [windkh/node-red-contrib-telegrambot#149]
Hello!
I am developing a bot where you can see the chat history with a client. To display history, I take the message IDs and then just forward them. But in your library it is not possible to do this. There is a condition that does not allow you to forward the message to yourself.
![image](https://user-images.githubusercontent.com/1189977/105335610-d6511b00-5c0a-11eb-9ff8-eb298dc232f4.png)

In my opinion, this is not correct, because the API Telegram allows you to do this.
The **copyMessage** method could solve this problem, but unfortunately it is not implemented here. Are you planning to add a **copyMessage** method?

Thank you!

**Comment by windkh** [comment]
I can have a look at it.

**Comment by windkh** [comment]
I added copyMessage and allowed to forward to the chat where it comes from.
Hint: don't build endless loops!

**Comment by windkh** [comment]
Version 9.1.0 should fix this

**Comment by doucreator** [comment]
It's grate! Thanx!

**Comment by windkh** [comment]
Let me know if it works for you... if not we can reopen this issue.
