### ISSUE TITLE
Feature Request: Send Message by username instead of chatId alternatively

### ISSUE THREAD

**Issue by OliverWieland** [windkh/node-red-contrib-telegrambot#150]
I want to send my messages by username.

My proposal:
The data from the bot's api includes the user name, so I suggest to save a lookup table with chatId and username.
In the payload.chatId of the telegram sender node will be differentiated if the type of the content is numeric or string. If it's numeric, the content will be used as chatId. If it is a string, it is a usernam and the chatId will be determined through a search in the lookup table.

Alternative proposal:
The sender's payload will be extended by a new key named 'userName'. Either 'userName' or 'chatId' ha to be set. If both are set, one of both has a higher priority (don't know which makes more sense).

**Comment by windkh** [comment]
I would have implemented that years ago if Telegram would support that. Don't ask me why but there is no way to resolve a chatId by username. Sorry but this is not possible.

**Comment by OliverWieland** [comment]
@windkh 
I was thinking of something like this:

`diff --git a/telegrambot/99-telegrambot.js b/telegrambot/99-telegrambot.js
index c7c8279..f8563ef 100644
--- a/telegrambot/99-telegrambot.js
+++ b/telegrambot/99-telegrambot.js
@@ -502,6 +502,19 @@ module.exports = function (RED) {
             self.commands.push(command);
         }
 
+        this.chatIdByUsername = function(username){
+            // ToDo: return chatId if username is in lookup table or null
+            
+            // This is just a test 
+            if (username == "testuser") return 123456789;
+            return null;
+        }
+
+        this.storeUser = function(chatid, username) {
+            // ToDo: store and username lookup table
+            return;
+        }
+
     }
     RED.nodes.registerType("telegram bot", TelegramBotNode, {
         credentials: {
@@ -659,6 +672,8 @@ module.exports = function (RED) {
                         var msg = { payload: messageDetails, originalMessage: botMsg };
 
                         if (node.config.isAuthorized(node, chatid, username)) {
+                            // store the user in the lookup table
+                            node.config.storeUser(chatid, username);
                             // downloadable "blob" message?
                             if (messageDetails.blob) {
                                 var fileId = msg.payload.content;
@@ -1786,6 +1801,20 @@ module.exports = function (RED) {
             node.status({ fill: "green", shape: "ring", text: "connected" });
 
             if (msg.payload) {
+                if (msg.payload.userName) {
+                    if(!Array.isArray(msg.payload.userName)){
+                        msg.payload.chatId = node.config.chatIdByUsername(msg.payload.userName);
+                    } else{
+                        var userNames = msg.payload.userName;
+                        var length = userNames.length;
+                        var chatIds = [];
+                        for (var i = 0; i < length; i++) {
+                            chatIds.push(node.config.chatIdByUsername(msg.payload.userName));
+                        }
+                        msg.payload.chatId = chatIds;
+                    }
+
+                }
                 if (msg.payload.chatId) {
                     if(!Array.isArray(msg.payload.chatId)){
                         var chatId = msg.payload.chatId;
`

It is not ready, because I don't know what is the best practice to store the lookup table in a node red node. But principally this works (except for storing the data).

**Comment by windkh** [comment]
So you want to configure a local lookup table for your own to be able to resolve the username. 
There are several ways how that can be implemented.
Can you describe the use-case why you need this, so that I better understand. Right now I do not really see the point why this is needed as every received message contains the user name anyway.

**Comment by OliverWieland** [comment]
The use-case is, that I have a few users. Everyone of them can select in the Dashboard which notifications he/she wants to receive, but a normal user doesn't know his/her id, bit his/her username.
Of course I could store this lookup table in my NodeRed-Application, but I thought, it would be nice to have that in the telegram nodes itself.
