### ISSUE TITLE
broadcast instead of polling?

### ISSUE THREAD

**Issue by fmarzocca** [windkh/node-red-contrib-telegrambot#151]
Hi,

I am wishing to use this module to broadcast messages from my application, but I don't want it to "poll" on the bot,to avoid interferences with other applications on that same bot.

Is it possible to disable the polling?

Thanks

**Comment by windkh** [comment]
I see your point: if there is no receiver there should be no need for polling. Maybe I will add an additional option: off 
Right now this is not possible as the configuration node immediately attempts to poll or connect via webhook.

**Comment by fmarzocca** [comment]
Thank you for trying to introduce this new feature!
Looking forward to it.

**Comment by windkh** [comment]
Version 10.0.2 supports this. Sorry for delay but I did not forget to implement it in the end :)

**Comment by fmarzocca** [comment]
> Version 10.0.2 supports this. Sorry for delay but I did not forget to implement it in the end :)

Thanks!
