### ISSUE TITLE
Callback_Query doesn't appear to work for me

### ISSUE THREAD

**Issue by alecdesantis** [windkh/node-red-contrib-telegrambot#152]
Hello!  I'm not sure if this is a real issue/bug but I'm not sure the best place to ask.  If there's a better place, feel free to point me to that direction.

I have tried getting the callback_query to work but it does not appear to be receiving anything (at least, the debug node doesn't show anything).  I am able to send a message to the group with the inline keyboard, but when I select an option (click one of the buttons), nothing appears to push into node red.  A small loading circle appears on the button for a few seconds, then disappears.  

I have already regenerated the bot token (based on a suggestion from one of the other issues you have closed already), restarted node-red and restarted Telegram.  I'm using using this in Home Assistant.

Here's the example I was trying to get to work.  Again, this works up until sending the button response back to the callback_query node.  Hopefully it's something easy to fix that I'm doing wrong :)

`[{"id":"7beefb94.d15ab4","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":410,"y":100,"wires":[]},{"id":"f584ee7c.d2df1","type":"catch","z":"b00e4200.8f9fe","name":"","scope":null,"x":260,"y":100,"wires":[["7beefb94.d15ab4"]]},{"id":"6e9ae1c2.72cb6","type":"telegram event","z":"b00e4200.8f9fe","name":"","bot":"7718cb42.42f534","event":"callback_query","autoanswer":true,"x":280,"y":170,"wires":[["89d54986.81c428","e778006f.dc578","59c89d71.e2a204"]]},{"id":"3583555e.04ab8a","type":"telegram sender","z":"b00e4200.8f9fe","name":"show inline keyboard","bot":"7718cb42.42f534","haserroroutput":false,"outputs":1,"x":690,"y":330,"wires":[["c812bd48.f9482"]]},{"id":"44f90bf.a7c3af4","type":"function","z":"b00e4200.8f9fe","name":"inline keyboard message","func":"var opts = {\n reply_to_message_id: msg.payload.messageId,\n reply_markup: JSON.stringify({\n \"inline_keyboard\": [[\n {\n \"text\": \"Yes\",\n \"callback_data\": \"FOO YES\" \n }, \n {\n \"text\": \"No\",\n \"callback_data\": \"FOO NO\" \n },\n {\n \"text\": \"Close\",\n \"callback_data\": \"Close\" \n }]\n ]\n })\n};\n\nmsg.payload.content = 'Are you sure?';\nmsg.payload.options = opts;\n\nreturn [ msg ];\n","outputs":"1","noerr":0,"initialize":"","finalize":"","x":450,"y":330,"wires":[["3583555e.04ab8a"]]},{"id":"4e9f30ff.593cc","type":"telegram command","z":"b00e4200.8f9fe","name":"/foo","command":"/foo","bot":"7718cb42.42f534","strict":false,"hasresponse":false,"useregex":false,"removeregexcommand":false,"outputs":1,"x":250,"y":330,"wires":[["44f90bf.a7c3af4","7a7fa491.6d2eec"]]},{"id":"89d54986.81c428","type":"function","z":"b00e4200.8f9fe","name":"set answer options","func":"var show_alert = true; // you can set this to true to open a dialog with the answer in the client.\n\n// msg.payload.content contains the callback data from the keyboard.\n// You may change this value here.\nmsg.payload.options = show_alert;\n\nreturn [ msg ];\n","outputs":"1","noerr":0,"initialize":"","finalize":"","x":490,"y":150,"wires":[["7999ad7e.2dd554","a90022b2.f07cc"]]},{"id":"7999ad7e.2dd554","type":"telegram sender","z":"b00e4200.8f9fe","name":"answer callback query","bot":"7718cb42.42f534","haserroroutput":false,"outputs":1,"x":730,"y":170,"wires":[[]]},{"id":"a90022b2.f07cc","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":670,"y":120,"wires":[]},{"id":"e778006f.dc578","type":"function","z":"b00e4200.8f9fe","name":"Close","func":"\n\n \n if (msg.payload.content == 'Close') {msg.payload.type = 'deleteMessage';\n msg.payload.content = msg.payload.messageId\n \n return msg;}\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":490,"y":210,"wires":[["7999ad7e.2dd554"]]},{"id":"7a7fa491.6d2eec","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":390,"y":390,"wires":[]},{"id":"d4e795b2.809978","type":"telegram receiver","z":"b00e4200.8f9fe","name":"","bot":"7718cb42.42f534","saveDataDir":"","filterCommands":false,"x":290,"y":500,"wires":[["6e1c08ce.9fdd38"],[]]},{"id":"6e1c08ce.9fdd38","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":480,"y":500,"wires":[]},{"id":"59c89d71.e2a204","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":340,"y":240,"wires":[]},{"id":"c812bd48.f9482","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":880,"y":330,"wires":[]},{"id":"7718cb42.42f534","type":"telegram bot","botname":"@HomeNotifierBot_bot","usernames":"[redacted]","chatids":"[redacted]","baseapiurl":"","updatemode":"polling","pollinterval":"500","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]`

**Comment by windkh** [comment]
Hi, I won‘t have time today to check this out, but just to be sure: did you try one of the examples in the example folder?
Then you can try with a different bot token to make sure that there is no problem with that.
...
I will have a look at your flow as soon as I have some time...

**Comment by alecdesantis** [comment]
Hi, not a problem!  I appreciate you looking at it when you get a chance.  The code I posted above were based on the older example.  I just re-did the flow by importing the new example through node-red and experienced the same thing.  I get the message in telegram with the buttons, and when I click the button in the inline keyboard, it has the little loading circle but nothing appears in node red.

Here is the code from the example imported from the example folder.
`[{"id":"f7c18f49.063c4","type":"telegram sender","z":"b00e4200.8f9fe","name":"","bot":"7718cb42.42f534","haserroroutput":false,"outputs":1,"x":800,"y":630,"wires":[[]]},{"id":"f97878f7.de1bf8","type":"function","z":"b00e4200.8f9fe","name":"build keyboard","func":"var opts = {\n  reply_markup: JSON.stringify({\n    \"inline_keyboard\": [[\n                {\n                    \"text\": \"A1\",\n                    \"callback_data\": \"1\"            \n                }, \n                {\n                    \"text\": \"A2\",\n                    \"callback_data\": \"2\"            \n                }]\n            ]\n  })\n};\n\nmsg.payload.content = \"Selection?\";\nmsg.payload.options = opts;\nmsg.payload.chatId = [redacted];\nmsg.payload.messageId = 99;\nmsg.payload.sentMessageId = 99;\nmsg.payload.type = \"message\";\n\nreturn [ msg ];\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":540,"y":630,"wires":[["f7c18f49.063c4","67925ff5.4c7c9"]]},{"id":"67925ff5.4c7c9","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":760,"y":690,"wires":[]},{"id":"e1a6a394.269598","type":"inject","z":"b00e4200.8f9fe","name":"","props":[{"p":"payload.content","v":"","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"str","x":300,"y":630,"wires":[["f97878f7.de1bf8"]]},{"id":"981d4537.1ced18","type":"telegram event","z":"b00e4200.8f9fe","name":"","bot":"7718cb42.42f534","event":"callback_query","autoanswer":false,"x":310,"y":712,"wires":[["ab3f06a.9c5a0f8"]]},{"id":"ab3f06a.9c5a0f8","type":"debug","z":"b00e4200.8f9fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":500,"y":712,"wires":[]},{"id":"93430912.0f4f4","type":"comment","z":"b00e4200.8f9fe","name":"Inline keyboard: Reply with \"callback_query\"","info":"","x":420,"y":572,"wires":[]},{"id":"7718cb42.42f534","type":"telegram bot","botname":"@HomeNotifierBot_bot","usernames":"1420472091","chatids":"-437665538","baseapiurl":"","updatemode":"polling","pollinterval":"500","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]`

**Comment by alecdesantis** [comment]
I was looking at this again and it looks like I'm not even seeing anything on the receiver node, either.  Wonder if it's an issue with my config somehow.

**Comment by windkh** [comment]
You do not have valid message ids in your example. 99 is only an example not real data!
Take this example
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/inlinekeyboard.json
here you have a valid  msg object from the /foo command node...

**Comment by alecdesantis** [comment]
Hi, thank you so much for your patience and help!  I imported your example but it still didn't work.  I didn't realize that there was verbose logging available, and when enabled, I got an error that an unauthorized person was trying to send me a message.  

I had my user id input into the user field, but changing it to the string of my username fixed the issue.

Do you know if it would be possible to use inline keyboard without using a command, e.g. could I set a message ID or something?  

My use case is that I have home automation set up. I want to send an alert when the doors are open too long with the thermostat is on.  The warning message would include the inline keyboard (Doors are open and thermostat open, do you want to turn off the thermostat? Button: Yes, Button: No).

**Comment by windkh** [comment]
Yes of course,... replace the command node with your input. You need to set the correct chatId asvthis info comes from the command node in your example

**Comment by alecdesantis** [comment]
Thanks again for your help!  I'm going to go work on this and try to get it to work.
