### ISSUE TITLE
more RAM used when not online

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#154]
Hi, I've noticed my node Red works about 0,22GB (of 1 GB) on Raspberry3b.. but when iternet not working for long time.. it comes up to 0,55. I think it's up to this module, because before installing it I havent's such problem, how can I check how much ram is using?
Verbose log mode is disabled. Thank you

**Comment by windkh** [comment]
hm.... no idea to be honest
what happens if internet is restored? Does memory consumption drop then?

**Comment by Barabba11** [comment]
Interesting question, thanks for help. Actually it doesn't depend on me, when it will be activated I'll post here

**Comment by Barabba11** [comment]
Ciao! Internet has back, but ram ingreased from 0.55 to 0,60
There is any way to stop just your module and see if the ram goes low? how can I debug it?
actually I have:
pi         349  4.4 56.4 654824 535600 ?       SNsl  2020 3337:04 node-red
56.4%
thank you

**Comment by Barabba11** [comment]
if it can be useful, I've just updated it from palette, I had a previous version, it took a while to update.. maybe less than 2 min, nor ram is 0,62, it went to 0,65 during process. 
If you think the module and its ram usage should be reset during this process then it's caused by something else

**Comment by windkh** [comment]
> if it can be useful, I've just updated it from palette, I had a previous version, it took a while to update.. maybe less than 2 min, nor ram is 0,62, it went to 0,65 during process.
> If you think the module and its ram usage should be reset during this process then it's caused by something else

Hi.. to be honest the only thing that is allocated is a connection for communicating with the telegram server. The rest is just normal node-red stuff. When you reboot the menory is back at 0,22GB?

**Comment by Barabba11** [comment]
I0ve rebooted, yes 0,18
The system was boot up 52 days, now I've to wait agin that long time to debug the problem.. 
so I have no way to debug this module how much resources is using? Thanks

**Comment by windkh** [comment]
To be honest I never did a memory profiling... let me find out if this is possible at all.

**Comment by windkh** [comment]
I tried to use chrome for memory profiling and found out that the memory of the process is constant

![image](https://user-images.githubusercontent.com/10910767/127753272-e266acce-9b19-4180-bc49-558098e1053a.png)

However I can confirm that the node.exe process in task manager of windows consumes more and more memory.

**Comment by windkh** [comment]
closed due to no feedback
