### ISSUE TITLE
pin and unpin message

### ISSUE THREAD

**Issue by HydrelioxGitHub** [windkh/node-red-contrib-telegrambot#155]
Recently Telegram add a feature that allow to pin multiple messages. I've tried for a few hours to unpin a specific message but it seems that the message_id provided is ignored and only the most recent message is unpinned.

Can someone confirm that ?

**Comment by windkh** [comment]
Can you send an example flow?

**Comment by HydrelioxGitHub** [comment]
`var type_alerte = msg.payload.type_alerte ;
var chatId = global.get("telegram_id_group");
var message = flow.get("weather_alert."+ type_alerte +".pinned.MessageId");
var options = {};
options = {
    message_id : message,
    chat_id : global.get("telegram_id_group")
};

var payload = {
    type: "unpinChatMessage",
    chatId: chatId,
    content: message,
    options : options
    
}

msg.payload = payload;
flow.set("weather_alert."+ type_alerte +".pinned.MessageId", null);
return msg;
`
This is what I send to my Telegram Sender Node. I've tried to pass the message_id in content or in option but it's not working as expected.

**Comment by windkh** [comment]
Hi sorry for delay,...
you could try

![image](https://user-images.githubusercontent.com/10910767/110247859-a1a4e300-7f6e-11eb-899b-f5ec933beadd.png)

Well, your options were not passed to the lower api via the options. You have to specify a content that contains message_id (and chat_id) see https://core.telegram.org/bots/api#unpinchatmessage

Indeed the chatId which is passed in payload.chatId is copied into  payload.content.chat_id. So it is always overwritten regardless what you specify.

**Comment by HydrelioxGitHub** [comment]
Hi, I've tried your solution but the result is the same. I've pinned 2 message, and when I try to unpin it, only the last one and not the one identified by the id in `message_id` in options variable.

**Comment by windkh** [comment]
Short answer: it works.
See the following flow: you must not use the message text as message_id!

[{"id":"46b012eb.3634bc","type":"telegram sender","z":"ed43e0f7.31d9","name":"","bot":"fcc25e57.4073a","haserroroutput":false,"outputs":1,"x":450,"y":80,"wires":[["90c8183c.df50d8"]]},{"id":"edd05cdc.ccba7","type":"inject","z":"ed43e0f7.31d9","name":"Pin 1","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"Pinned 1","payloadType":"str","x":110,"y":80,"wires":[["62a75af3.7db694"]]},{"id":"239ac48e.7aaafc","type":"function","z":"ed43e0f7.31d9","name":"unpin","func":"var chatId = -1001456177533;\n\nvar message_id =  flow.get(\"message1\");\nvar options = {};\noptions = {\n    message_id : message_id,\n    chat_id : chatId\n};\n\nvar payload = {\n    type: \"unpinChatMessage\",\n    chatId: chatId,\n    content: options\n}\n\nmsg.payload = payload;\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":610,"y":260,"wires":[["14e472e9.7fd11d"]]},{"id":"d14be332.4bb58","type":"inject","z":"ed43e0f7.31d9","name":"Unpin 1","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"1","payloadType":"num","x":110,"y":260,"wires":[["239ac48e.7aaafc"]]},{"id":"90c8183c.df50d8","type":"function","z":"ed43e0f7.31d9","name":"pin","func":"var chatId = -1001456177533;\n\nvar message_id = msg.payload.sentMessageId;\nflow.set(\"message1\", message_id);\n\nvar payload = {\n    type: \"pinChatMessage\",\n    chatId: chatId,\n    content: message_id\n}\n\nmsg.payload = payload;\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":610,"y":80,"wires":[["14e472e9.7fd11d"]]},{"id":"62a75af3.7db694","type":"function","z":"ed43e0f7.31d9","name":"send message","func":"var chatId = -1001456177533;\nvar message = msg.payload;\n\nvar payload = {\n    type: \"message\",\n    chatId: chatId,\n    content: message\n}\n\nmsg.payload = payload;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":260,"y":80,"wires":[["46b012eb.3634bc"]]},{"id":"2dd330e0.b9c11","type":"inject","z":"ed43e0f7.31d9","name":"Unpin 2","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"2","payloadType":"num","x":110,"y":320,"wires":[["55e710fd.20302"]]},{"id":"d3f18224.5a203","type":"telegram sender","z":"ed43e0f7.31d9","name":"","bot":"fcc25e57.4073a","haserroroutput":false,"outputs":1,"x":450,"y":180,"wires":[["d941af35.b1ebe"]]},{"id":"96833547.618ac8","type":"inject","z":"ed43e0f7.31d9","name":"Pin 2","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"Pinned 2","payloadType":"str","x":110,"y":180,"wires":[["b9efb76b.987648"]]},{"id":"d941af35.b1ebe","type":"function","z":"ed43e0f7.31d9","name":"pin","func":"var chatId = -1001456177533;\n\nvar message_id = msg.payload.sentMessageId;\nflow.set(\"message2\", message_id);\n\nvar payload = {\n    type: \"pinChatMessage\",\n    chatId: chatId,\n    content: message_id\n}\n\nmsg.payload = payload;\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":610,"y":180,"wires":[["14e472e9.7fd11d"]]},{"id":"b9efb76b.987648","type":"function","z":"ed43e0f7.31d9","name":"send message","func":"var chatId = -1001456177533;\nvar message = msg.payload;\n\nvar payload = {\n    type: \"message\",\n    chatId: chatId,\n    content: message\n}\n\nmsg.payload = payload;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":260,"y":180,"wires":[["d3f18224.5a203"]]},{"id":"14e472e9.7fd11d","type":"telegram sender","z":"ed43e0f7.31d9","name":"","bot":"fcc25e57.4073a","haserroroutput":false,"outputs":1,"x":810,"y":180,"wires":[[]]},{"id":"55e710fd.20302","type":"function","z":"ed43e0f7.31d9","name":"unpin","func":"var chatId = -1001456177533;\n\nvar message_id = flow.get(\"message2\");\nvar options = {};\noptions = {\n    message_id : message_id,\n    chat_id : chatId\n};\n\nvar payload = {\n    type: \"unpinChatMessage\",\n    chatId: chatId,\n    content: options\n}\n\nmsg.payload = payload;\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":610,"y":320,"wires":[["14e472e9.7fd11d"]]},{"id":"fcc25e57.4073a","type":"telegram bot","botname":"TestBot","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]

**Comment by HydrelioxGitHub** [comment]
I've just made a test with your code and it does not work as expected like you said. 

Pin 1 inject -> a message "Pinned 1" is pinned in the chat 

Pin 2 inject -> a message "Pinned 2" is pinned in the chat 

Unpin 1 inject -> "Pinned 1" message is the one left in the chat so the bot unpinned message "Pinned 2" which is not what it's expected.

I don't know if it's me or not but I only copy and paste your code through the import function of Nodered.

**Comment by windkh** [comment]
@HydrelioxGitHub 
Well, there is nothing else I can tell you: it works. Made some screenshots where you can see it.
Sorry but maybe it is a problem with your client. I don't know.

![image](https://user-images.githubusercontent.com/10910767/110472696-f5820a00-80dd-11eb-9cb6-9517b1ddd8cd.png)
