### ISSUE TITLE
reply Node doesn´t work

### ISSUE THREAD

**Issue by zzzzMarkuszzzz** [windkh/node-red-contrib-telegrambot#156]
I rebuild the figure shown in "Implementing an on reply node" but the "get reply" Node does not show any response of my message. Am I doing anything wrong or is this a bug?

**Comment by windkh** [comment]
Did you reply to a message or just send a response?

**Comment by zzzzMarkuszzzz** [comment]
Thanks a lot! That was it! I just responsed to the message!
