### ISSUE TITLE
code inconsistency

### ISSUE THREAD

**Issue by DarkPark** [windkh/node-red-contrib-telegrambot#158]
I see some minor problems in code (typos, no strict comparison, `var` usages, wrong `let` usages, tabs/spaces mixes, unnecessary indentations but missing in some other places, no hoisting potential problems prevention, no splitting to a small manageable files and so on).
It would be nice to integrate some linter (eslint for example) and adopt some widespread code style (for example https://github.com/airbnb/javascript).
It will make code more readable, decrease support cost and eliminate potential problems.

**Comment by windkh** [comment]
Yes you are right... as I only invest little time in that project I skipped cleaning up all the time. Feel free to create a pull request

**Comment by DarkPark** [comment]
Fortunately I have my own projects and very little free time :)

**Comment by windkh** [comment]
@DarkPark I am totally aware of the technical issues... and I will probably do something about that in future. As I am not earning money with this, my motivation is limited in invest investing a lot of time.

**Comment by TotallyInformation** [comment]
There are now some useful extensions to GitHub that can help with identifying coding issues, I'm using them myself on uibuilder where I have the same issue of too much to do and not enough time to work on the project.

**Comment by windkh** [comment]
@TotallyInformation sounds interesting ... is there any guidance available how to integrate this into github?
I guess setting up eslint locally should be straight forward, but what code style checker should I use. Can you recommend one?

**Comment by windkh** [comment]
version 8.12.0 should fix this:
added eslint and prettier

**Comment by TotallyInformation** [comment]
Gather you worked it out? Sorry I didn't respond at the time. The GitHub docs on the subject are not bad.

**Comment by windkh** [comment]
@TotallyInformation I had a look at your project and did the rest with help of Mr. Google... 
except for some changes in the code (indentations, brackets, quotas...) there are a dozen more dev dependencies. Feels better but made the overall package more complex.

**Comment by TotallyInformation** [comment]
Yes, there is some inevitable added complexity to the dev dependencies. But the eventual improvement in code quality often seems to outweigh that overhead. Even if it only occasionally catches something, I think it is worth it. Effectively you are getting another pair of eyes on your code for free. 😁
