### ISSUE TITLE
how to node-red into bot into Channel

### ISSUE THREAD

**Issue by syswombat** [windkh/node-red-contrib-telegrambot#160]
Hello
i have a working nodes sending script from Node Red to a telegram bot.
now i wish to get this information also in a telegram Channel!

the bot is added to the telegram Channel as administrator too

how to do this?

have a nice day
vinc

**Comment by windkh** [comment]
@syswombat 
erklärs nochmal auf deutsch, vielleicht verstehe ichs dann ... :)

**Comment by syswombat** [comment]
Danke,

als ich habe Node Red das mir Nachrichten nach Telegram Bot schickt. Das geht sehr gut!
Damit diese Nachricht auch andere erhalten können habe ich einen CHANNEL erstellt. Es geht ja nur darum zu Informieren ohne einen Dialog.
Ich habe den Telegram Bot als admin in den Channel erfasst.
Nun ging ich davon aus das der Bot sozusagen die erhaltene Nachricht in den Channel weiterleitet.
Was aber leider nicht der Fall ist.

Wie kann/muss ich eine Telegram Nachricht erstellen das diese anstonsten direkt in den CHANNEL publiziert? eine CHANNEL ID find ich nicht und auch ein CHANNEL Token find ich nicht.

der Node der die Info verschickt ist


var message  = 'Test Message';
var payload  = msg.payload.text ;
var payloadl = msg.payload.author;

msg.payload = {chatId : 1234chatnummer567,  type : 'message', 
content : "*" +message +"*" +"\n" +"\n"  +payload +"\n" +"\n" +"*" +payloadl +"*"
};

// activate markdown
//msg.payload.options = {disable_web_page_preview : true, parse_mode :"Markdown"};
msg.payload.options = {disable_web_page_preview : true, parse_mode :"Markdown"};
return msg;

**Comment by windkh** [comment]
Hi @syswombat,
am besten du leitest eine Message aus dem Channel mit forward message aus dem Telegram client an deinen Bot weiter. Der spuckt dir dann nach dem Receiver node im Debug aus, woher die message kam. Nimm am besten den folgenden Flow zum Test.

![image](https://user-images.githubusercontent.com/10910767/110247528-fa737c00-7f6c-11eb-93be-7ba4ee784d14.png)

![image](https://user-images.githubusercontent.com/10910767/110247556-1c6cfe80-7f6d-11eb-97ca-f2b69c3c2dca.png)

[{"id":"37f21150.086fde","type":"telegram receiver","z":"ed43e0f7.31d9","name":"","bot":"fcc25e57.4073a","saveDataDir":"","filterCommands":false,"x":150,"y":220,"wires":[["cf8f4fdc.c7564"],[]]},{"id":"cf8f4fdc.c7564","type":"debug","z":"ed43e0f7.31d9","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":380,"y":220,"wires":[]},{"id":"46b012eb.3634bc","type":"telegram sender","z":"ed43e0f7.31d9","name":"","bot":"fcc25e57.4073a","haserroroutput":false,"outputs":1,"x":530,"y":60,"wires":[[]]},{"id":"c53d4aaf.f42858","type":"function","z":"ed43e0f7.31d9","name":"send markdown","func":"var chatId = -1001456177533;\nvar message = 'Hi into channel.';\nmsg.payload = {chatId : chatId, type : 'message', content : message};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":309,"y":58.000022888183594,"wires":[["46b012eb.3634bc"]]},{"id":"edd05cdc.ccba7","type":"inject","z":"ed43e0f7.31d9","name":"Trigger","repeat":"","crontab":"","once":false,"topic":"","payload":"","payloadType":"date","x":108.31849670410156,"y":57.459373474121094,"wires":[["c53d4aaf.f42858"]]},{"id":"fcc25e57.4073a","type":"telegram bot","botname":"TestBot","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]
