### ISSUE TITLE
Send new document to chat

### ISSUE THREAD

**Issue by alexliit** [windkh/node-red-contrib-telegrambot#161]
Hello
I need to send a new document (in this case a CSV file) to a telegram chat with my demo bot.

I already succesfully send jpg images, setting (with a function)  the following properties on the payload:

    msg.payload={};
    msg.payload.type="photo";
    msg.payload.chatId="-888888888888";
    msg.payload.content=imagebuffer;
    msg.payload.caption=c;
    return msg;

having the "imagebuffer" variable setted as a binary buffer directly read from webcam with an http request node.

Attempting to create a buffer from a string

```
    msg.payload={}
    msg.payload.content=Buffer.from(csvstring)
    msg.payload.caption="Test"
    msg.payload.chatId="-888888888888";
    msg.payload.type="document"
```

I got the error from the Telegram sender node:

```
    Caught exception in sender node:
    'Error: EFATAL: Unsupported Buffer file-type'
    when processing message: 
    {"payload":{"content":{"type":"Buffer","data":        [60,104,116,109,108,62,60,66,62,73,110,102,111,114,109,97,116,105,111,110,32,73,110,116,114,97,100,97......
```

I assume there is some involment of the File_id properties but I could'nt figure out where or what to set it.

Any suggestion?

Thank you

**Comment by windkh** [comment]
Hi, I added fileOptions, so that you can specify the file name and content type (mime).
Otherwise the lib would try to find out the mime type from the buffer contents. As CSV is not recognized your sample failed.
version 8.10.0 should fix this.
see https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/senddocumenttochat.json

**Comment by alexliit** [comment]
> Hi, I added fileOptions, so that you can specify the file name and content type (mime).
> Otherwise the lib would try to find out the mime type from the buffer contents. As CSV is not recognized your sample failed.
> version 8.10.0 should fix this.
> see https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/senddocumenttochat.json

It works. Thanks
