### ISSUE TITLE
How to Get Senders User Name

### ISSUE THREAD

**Issue by Anjerlaan** [windkh/node-red-contrib-telegrambot#163]
Hi,

When I use the "Telegram Receiver" node to receive a message from a bot, the debug node shows the following message:

`{"chatId":11875XXXXX,"messageId":152,"type":"message","content":"Hey","date":1615841478}`

How do I get the User Name of the person who has sent the message? or is that not possible

**Comment by windkh** [comment]
Next to msg.payload there is another property originalMessage which contains more information.

**Comment by windkh** [comment]
Switch the debug node to the mode where you can see the whole msg object

**Comment by Anjerlaan** [comment]
Thanx!
