### ISSUE TITLE
Can't get callback query

### ISSUE THREAD

**Issue by evazzoler** [windkh/node-red-contrib-telegrambot#165]
Hi, I'm trying since a week but I can't get a callback query and use the inline keyboard.
I click on the keyboard and nothing happens.
I tried the example code without touching the code (except the bot config).
I'm using the polling connection and all works good but the callback query.
Nodered is the latest version form npm.
I open a issue because I'm no longer sure that may be a problem by my side.

**Comment by windkh** [comment]
What example did you use?

**Comment by evazzoler** [comment]
editinlinekeyboard.json in the examples folder

**Comment by evazzoler** [comment]
Maybe because I've set "ChatIds" in the bot configuration? Whithout that I receive the callback, but it becomes a security lack...

**Comment by windkh** [comment]
I just ran the example and it worked... 
![image](https://user-images.githubusercontent.com/10910767/112819715-2920d600-9085-11eb-9e4c-a6af0358c22c.pn

Is the callback_query node configured correctly?

**Comment by windkh** [comment]
I checked it out with chatId: it works

**Comment by evazzoler** [comment]
I confirm: without chatid it works for me, but I need chatid to be set for security resons. With chatid set, it doesen't work.

**Comment by evazzoler** [comment]
NOTE: when I configure the bot without chatid, callback works but comes with a different chatid than the one of the group I'm using.

**Comment by windkh** [comment]
Is there a way to setup up a screen sharing session so that I can see what is going on?

**Comment by evazzoler** [comment]
Sure! Teamviewer? I'll contact you via private message? Now or do you prefer in a different moment?

**Comment by windkh** [comment]
now but only for 10min

**Comment by windkh** [comment]
can I send you a link? e-mail?

**Comment by evazzoler** [comment]
I've sent you a mail

**Comment by windkh** [comment]
I will have to leave for lunch now. 
The flow is not working as expected within groups or supergroups. It claims that the message to edit was not found.
Can you confirm that the flow works when you directly talk to the bot (not within a group?)

**Comment by windkh** [comment]
@evazzoler The function TelegramEventNode takes the chatId from the user that initiated the callback_query. Maybe the function should also check for the sending group if there is any.

--> must be fixed
Workaround: add the userIds of the chat to the allowed chatIds not only the id of the group itself.

--> the examples sometimes throw errors in super groups "message can not be edited" or "message can not be found" 
--> must be fixed, too

**Comment by evazzoler** [comment]
Thank you for your super instant (synchronous) support and for your very useful "palette"!

**Comment by windkh** [comment]
version 8.11.0 should fix this
