### ISSUE TITLE
Event node - channel_post - unknown error.

### ISSUE THREAD

**Issue by photocromax** [windkh/node-red-contrib-telegrambot#168]
I've just updated to 9.1.1 and I get two errors when the bot gets a channel_post event.
Error 1: "Cannot read property 'id' of undefined"
Error 2: "Unknown error. Trying again."

I've rolled back till 8.10.0 and the error disappeared.

Let me know if I can provide any further detail to better identify the problem.

**Comment by windkh** [comment]
@photocromax  thanx for reporting.
Dou you have the message object for that was received?

**Comment by photocromax** [comment]
The error happens before getting the msg. (a debug node connected to the output is not triggered)
By the way, the content is a simple latin text, around 15 chars long, no fancy symbols.

If I click the node ID on the debug console error, node-red switchs to the configuration nodes tab.

**Comment by windkh** [comment]
I think I found the problem. I will create a Version 9.2.1 now. please test it.

**Comment by photocromax** [comment]
It worked flawlessly!

@windkh thanks for your blazing fast correction.
