### ISSUE TITLE
can't Reinstall  node-red-contrib-telegrambot 9.2.1

### ISSUE THREAD

**Issue by KarlKartoffel** [windkh/node-red-contrib-telegrambot#169]
After some smaler issues I decided to update telegrambot from version 8.somehting to 9.2.1.

After restarting nodered all the Telegramm-Nodes were replaced with empty placeholder.
So i deleted all the nodes and tried to install Version 9.2.1. This installation failed. when deploying an error says :

Flow were stoped caus of missing nodetype:
    telegram bot
    
Even when i delted all the Telegramm nodes including global configuration nodes.

the error log says this:

    -----------------------------------------------------------
2021-04-09T13:09:53.046Z install: node-red-contrib-telegrambot 9.2.1

2021-04-09T13:09:53.197Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-telegrambot@9.2.1
2021-04-09T13:09:57.325Z [err] npm
2021-04-09T13:09:57.326Z [err]  WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
2021-04-09T13:09:57.326Z [err] npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
2021-04-09T13:09:57.367Z [err] npm
2021-04-09T13:09:57.367Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2021-04-09T13:09:57.398Z [err] npm
2021-04-09T13:09:57.398Z [err]  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2021-04-09T13:09:57.695Z [err] npm
2021-04-09T13:09:57.695Z [err]  ERR! code EINTEGRITY
2021-04-09T13:09:57.695Z [err] npm ERR! errno EINTEGRITY
2021-04-09T13:09:57.718Z [err] npm 
2021-04-09T13:09:57.719Z [err] ERR! Invalid response body while trying to fetch https://registry.npmjs.org/file-type: Integrity verification failed for sha512-jYBTV2n1gegQ+CtGOQ0I0wFkY4oPzCPXTF9Wh81ItTcKXce2uT9vn6YWfrSubhqEwwHFfWlCk6JXcelv+iJyag== (/home/pi/.npm/_cacache/content-v2/sha512/8d/80/535769f581e810f82b46390d08d30164638a0fcc23d74c5f5687cd48b5370a5dc7b6b93f6f9fa6167eb4ae6e1a84c301c57d694293a25771e96ffa22726a)
2021-04-09T13:09:57.733Z [err] 
2021-04-09T13:09:57.734Z [err] npm ERR! A complete log of this run can be found in:
2021-04-09T13:09:57.734Z [err] npm ERR!
2021-04-09T13:09:57.734Z [err]      /home/pi/.npm/_logs/2021-04-09T13_09_57_720Z-debug.log
2021-04-09T13:09:57.749Z rc=1

maybe someone can help me with this issue.
thx in advance have a nice day

**Comment by windkh** [comment]
I updated right after you posted this

![image](https://user-images.githubusercontent.com/10910767/114187507-5f453c00-9948-11eb-98c1-242f063d5630.png)

**Comment by windkh** [comment]
so basically it seems to work and the nodes are there. What does the log say?

**Comment by KarlKartoffel** [comment]
thx for the fast response.
When I try to open 
/home/pi/.npm/_logs/2021-04-09T13_09_57_720Z-debug.log responed with "Permission denied" so i guess i need to work on my raspy knolage first to open the log.

**Comment by windkh** [comment]
sudo nano /home/pi/.npm/_logs/2021-04-09T13_09_57_720Z-debug.log

**Comment by KarlKartoffel** [comment]
thx a lot.
so the Log looks like this:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--no-audit',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   '--save',
1 verbose cli   '--save-prefix=~',
1 verbose cli   '--production',
1 verbose cli   'node-red-contrib-telegrambot@9.2.1'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.21.0
4 verbose npm-session 3de9775da731087f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-telegrambot 278ms (from cache)
8 silly pacote version manifest for node-red-contrib-telegrambot@9.2.1 fetched in 301ms
9 timing stage:loadCurrentTree Completed in 1227ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 563ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-telegrambot@9.2.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/node-telegram-bot-api 92ms (from cache)
18 silly pacote range manifest for node-telegram-bot-api@^0.52.0 fetched in 98ms
19 silly resolveWithNewModule node-telegram-bot-api@0.52.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/bluebird 149ms (from cache)
21 silly pacote range manifest for bluebird@^3.5.1 fetched in 164ms
22 silly resolveWithNewModule bluebird@3.7.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/socks5-https-client 157ms (from cache)
24 silly pacote version manifest for socks5-https-client@1.2.1 fetched in 164ms
25 silly resolveWithNewModule socks5-https-client@1.2.1 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/bl 97ms (from cache)
27 silly pacote range manifest for bl@^1.2.3 fetched in 111ms
28 silly resolveWithNewModule bl@1.2.3 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/debug 129ms (from cache)
30 silly pacote range manifest for debug@^3.1.0 fetched in 135ms
31 silly resolveWithNewModule debug@3.2.7 checking installable status
32 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
33 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
34 silly fetchPackageMetaData error for file-type@^3.9.0 Invalid response body while trying to fetch https://registry.npmjs.org/file-type: Integrity verification failed for sha512-jYBTV2n1gegQ+CtGOQ0I0wFkY4oPzCPXTF9Wh81ItTcKXce2uT9vn6YW$
35 http fetch GET 304 https://registry.npmjs.org/request-promise 254ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/eventemitter3 265ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/request 263ms (from cache)
38 silly pacote range manifest for request-promise@^4.2.2 fetched in 276ms
39 warn deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
40 silly resolveWithNewModule request-promise@4.2.6 checking installable status
41 silly pacote range manifest for eventemitter3@^3.0.0 fetched in 285ms
42 silly resolveWithNewModule eventemitter3@3.1.2 checking installable status
43 silly pacote range manifest for request@^2.83.0 fetched in 283ms
44 warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
45 silly resolveWithNewModule request@2.88.2 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/pump 286ms (from cache)

**Comment by windkh** [comment]
Sounds like a npm problem... just google for integrity verification failed and hopefully you will find an answer like e.g.
https://stackoverflow.com/questions/49092723/fix-a-npm-install-failure-with-error-code-eintegrity
