### ISSUE TITLE
New Node-RED on bluemix 

### ISSUE THREAD

**Issue by FrancescaGigante** [windkh/node-red-contrib-telegrambot#17]
I'm not able to use the new package 2.3

My log errors start with a huge amount of messages (I'm unable to select all hope it will be enough):
017-05-26T17:43:03.36+0200 [APP/0] ERR { Error: ETELEGRAM: 409 Conflict: terminated by other long poll or webhook
017-05-26T17:43:03.36+0200 [APP/0] ERR     at request.then.err (/home/vcap/app/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:181:15)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at tryCatcher (/home/vcap/app/.node-red/node_modules/bluebird/js/release/util.js:16:23)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Promise._settlePromiseFromHandler (/home/vcap/app/.node-red/node_modules/bluebird/js/release/promise.js:512:31)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at TelegramError (/home/vcap/app/.node-red/node_modules/node-telegram-bot-api/src/errors.js:56:5)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at BaseError (/home/vcap/app/.node-red/node_modules/node-telegram-bot-api/src/errors.js:10:5)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Promise._settlePromises (/home/vcap/app/.node-red/node_modules/bluebird/js/release/promise.js:693:18)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Promise._settlePromise (/home/vcap/app/.node-red/node_modules/bluebird/js/release/promise.js:569:18)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Promise._settlePromise0 (/home/vcap/app/.node-red/node_modules/bluebird/js/release/promise.js:614:10)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Async._drainQueues (/home/vcap/app/.node-red/node_modules/bluebird/js/release/async.js:143:10)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at tryOnImmediate (timers.js:639:5)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Async._drainQueue (/home/vcap/app/.node-red/node_modules/bluebird/js/release/async.js:133:16)
017-05-26T17:43:03.36+0200 [APP/0] ERR   code: 'ETELEGRAM',
017-05-26T17:43:03.36+0200 [APP/0] ERR     at runCallback (timers.js:666:20)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at Immediate.Async.drainQueues (/home/vcap/app/.node-red/node_modules/bluebird/js/release/async.js:17:14)
017-05-26T17:43:03.36+0200 [APP/0] ERR     at processImmediate [as _immediateCallback] (timers.js:611:5)
017-05-26T17:43:03.36+0200 [APP/0] ERR    IncomingMessage {
017-05-26T17:43:03.36+0200 [APP/0] ERR       ReadableState {
017-05-26T17:43:03.36+0200 [APP/0] ERR         highWaterMark: 16384,
017-05-26T17:43:03.36+0200 [APP/0] ERR   response:
017-05-26T17:43:03.36+0200 [APP/0] ERR      _readableState:
017-05-26T17:43:03.36+0200 [APP/0] ERR         buffer: [Object],
.......
......

**Comment by windkh** [comment]
017-05-26T17:43:03.36+0200 [APP/0] ERR { Error: ETELEGRAM: 409 Conflict: terminated by other long poll or webhook

This indicates that another instane already occupies the bot. Make sure that you do not have 2 configuration nodes using the same bot token.

**Comment by FrancescaGigante** [comment]
Thanks!
I previously removed the box from another nodered application, but the configuration node was still there even if unused. 
Now I removed also the old configuration node and now the new one works!

**Comment by windkh** [comment]
Those Zombie Configuration Nodes are a common pitfall. Maybe I will change this in future. Glad that it finally works for you.
