### ISSUE TITLE
Send Silently

### ISSUE THREAD

**Issue by moshed** [windkh/node-red-contrib-telegrambot#170]
Would it be possible to incorporate an option to send silently?  https://core.telegram.org/bots/api#sendmessage

**Comment by ozett** [comment]
maybe this way?
![image](https://user-images.githubusercontent.com/5937811/115501028-bf09e400-a272-11eb-8c3f-32574076f771.png)

**Comment by windkh** [comment]
@ozett thanks perfect...

**Comment by moshed** [comment]
works perfectly!
