### ISSUE TITLE
Photo Mode Doesn't work anymore?

### ISSUE THREAD

**Issue by obbers** [windkh/node-red-contrib-telegrambot#171]
I used to be able to do 

msg.payload = {}
msg.payload.chatId = -XXXXXXXXX
msg.payload.type = 'photo'
msg.payload.content = '/NVR/snapshot,jpg'
msg.payload.caption = "Motion";
return msg;

and it would upload the local image.

Caught exception in sender node:
Error: ETELEGRAM: 400 Bad Request: URL host is empty
when processing message: 

Is there another way to upload local images?

**Comment by windkh** [comment]
@obbers 
I just tested the sendphoto.json example. It works
![image](https://user-images.githubusercontent.com/10910767/115747522-a514f200-a395-11eb-8211-ae4d57b9d6be.png)


msg.payload.content = '/NVR/snapshot,jpg'
--> there is a comma as extension delimiter in your code: should it be snapshot.jpg ?

**Comment by obbers** [comment]
The snapshot was just a place holder.  But you're right and my lack of due diligence raised this.
