### ISSUE TITLE
deleteMessage Problem

### ISSUE THREAD

**Issue by enriquetracker** [windkh/node-red-contrib-telegrambot#174]
Hello, everyone.

I am trying to delete a message on telegram, but i am having some problems.

I am using this format to edit a message:

msg.payload = {}
msg.payload.chatId =  1068642560

msg.payload.type = 'editMessageText'
msg.payload.content = 'Hello'

msg.payload.options = {
  message_id : global.get("msgID"),
  chat_id: 1068642560
}
return msg;

And I think I am saving the message_Id value good.

Well, I use the same format to delete a message but I have this problem:

Caught exception in sender node:Error: ETELEGRAM: 400 Bad Request: message identifier is not specifiedwhen processing message: {"_msgid":"d7504b7f.ea4e78","payload":{"chatId":1068642560,"type":"deleteMessage","content":"text","options":{"chat_id":1068642560,"message_id":1079}},"topic":""}

msg.payload = {}
msg.payload.chatId =  1068642560

msg.payload.type = 'deleteMessage'
msg.payload.content = 'text'

msg.payload.options = {
    chat_id: 1068642560,
  message_id : global.get("msgID")
  
}

return msg;

I dont understand what is my fault.
Thanks in advanced.

**Comment by windkh** [comment]
I would do something like

var chatId = ...
var message = „“;
var payload = { type: "deleteMessage", chatId: chatId, content: message}
msg.payload = payload;

return msg;

**Comment by enriquetracker** [comment]
> I would do something like
> 
> var chatId = ...
> var messageId= ...;
> var payload = { type: "deleteMessage", chatId: chatId, content: messageId}
> msg.payload = payload;
> 
> return msg;

Okey, you are a genius!!! It's solve. Thanks!!!!!!
