### ISSUE TITLE
Cannot read property 'chat' of undefined

### ISSUE THREAD

**Issue by padaVVan** [windkh/node-red-contrib-telegrambot#175]
Error while processing the following events:
- [pre_checkout_query](https://core.telegram.org/bots/api#precheckoutquery)
- [shipping_query](https://core.telegram.org/bots/api#shippingquery)
- [inline_query](https://core.telegram.org/bots/api#inlinequery)

Update has no chat property.

pre_checkout_query update example.

```JSON
{
  "update_id": 1231231231123,
  "pre_checkout_query": {
    "id": "111111212312312312312",
    "from": {
      "id": 111111111,
      "is_bot": false,
      "first_name": "XXXX",
      "last_name": "XXXX",
      "username": "XXXX",
      "language_code": "XXXX"
    },
    "currency": "EUR",
    "total_amount": 123,
    "invoice_payload": "secret token"
  }
}
```
Thank you.

**Comment by padaVVan** [comment]
[inline_query](https://core.telegram.org/bots/api#inlinequery) too

**Comment by windkh** [comment]
Thanks for reporting. Came the message from a channel, groupchat or a direct one?
Can you post the message of the other two events, too? I will fix this immediately. Would be fine if you could test that

**Comment by windkh** [comment]
Version 9.3.0 should fix it. Please test this version and tell me if it is working now.

**Comment by sanyafifa** [comment]
**chatId: undefined** - аfter upgrading to 9.3.1 I get this error :(

```
chatId: undefined
messageId: 154202
type: "editMessageReplyMarkup"
content: object
callbackQueryId: "3263562311586735500"
from: object
id: 759857313
is_bot: false
first_name: "X"
last_name: "X"
language_code: "ru"
options: object
```

**Comment by windkh** [comment]
@sanyafifa what version did you have before?

**Comment by windkh** [comment]
@sanyafifa version 9.4.0 should fix this

**Comment by sanyafifa** [comment]
> @sanyafifa what version did you have before? And what kind of event did you handle? From a channel or group?

ver 9.2.x
inline keyboard does not work in chat with bot and group

**Comment by windkh** [comment]
@sanyafifa please test 9.4.0

**Comment by sanyafifa** [comment]
Node Red palette update available yet

**Comment by sanyafifa** [comment]
Works! Thank you
