### ISSUE TITLE
accuracy of location message

### ISSUE THREAD

**Issue by RogierQ** [windkh/node-red-contrib-telegrambot#177]
Hi!

Is there an accuracy available of the location message?
Or is this also missing in the base message from telegram?

Now i have some strange spikes in my location updates.
Would be great if i can filter them based on accuracy

**Comment by windkh** [comment]
The location is provided as lat lon by the client. There is no additional info in the message that you can use on the receiver‘s side to improve that. Sorry

**Comment by RogierQ** [comment]
Thanks! Then it is time for a message to telegram ;-)

**Comment by windkh** [comment]
I would be interested in the outcome. Keep me informed, please.

**Comment by RogierQ** [comment]
Sure i do Karl!

**Comment by windkh** [comment]
https://core.telegram.org/bots/api#location
that type of object is stored inside msg.originalMessage.

you should check if any of the optional fields is set in your case... maybe there isxa chance to gather some values from there

**Comment by RogierQ** [comment]
Cool! I try that when the rain has stopt outside ;-)
