### ISSUE TITLE
Reading the Audio file which is sent from the App

### ISSUE THREAD

**Issue by shivag12** [windkh/node-red-contrib-telegrambot#18]
how do we read the audio file which is sent from the App, Now i'm getting only id of the audio file in the content field , Looking for the raw audio file which can be sent over speech to text service.

**Comment by windkh** [comment]
Audio should be downloaded into the configured dir (see configuration node). And the path should be in stores in the payload

msg.payload.path

**Comment by shivag12** [comment]
Is it possible to store the audio file to local file system. I m running the node red from bluemix.

**Comment by windkh** [comment]
The file ist automatically saved when a directory is configured. This input field is below the field where you entered your bot token.
