### ISSUE TITLE
[Feature Request] Poll with multiple answers

### ISSUE THREAD

**Issue by Dodoooh** [windkh/node-red-contrib-telegrambot#180]
Hi :) 
I would like to create a poll with multiple answers. in the [API of Telegram](https://core.telegram.org/bots/api#sendpoll) this is possible. is it possible to do this too ? 

many thanks.

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/createpoll.json

**Comment by windkh** [comment]
Did you see this?

**Comment by Dodoooh** [comment]
> Did you see this?

yes, but here it is only possible to create a poll which has only one answer option for the end user. 
I would like to have the possibility that the Telegram user can select multiple answers.
