### ISSUE TITLE
[Feature Request] Poll with multiple answers

### ISSUE THREAD

**Issue by Dodoooh** [windkh/node-red-contrib-telegrambot#181]
> Did you see this?

yes, but here it is only possible to create a poll which has only one answer option for the end user. 
I would like to have the possibility that the Telegram user can select multiple answers.

_Originally posted by @Dodoooh in https://github.com/windkh/node-red-contrib-telegrambot/issues/180#issuecomment-841718887_

------

because I think I was misunderstood I open this issue again. 

I would like to have multiple answer options also as a telegram user not only have one option which is selectable.

Or is this possible, would not be clear to me how. 
thank you very much.

**Comment by windkh** [comment]
Well, you can use all options of sendPoll as described in the API.

**Comment by Dodoooh** [comment]
ah really then I apologize for that. 

but how do i implement these options? or where can i read about this. is not clear to me right now. 

anyway thanks a lot

**Comment by windkh** [comment]
sendPoll(chatId, msg.payload.content, msg.payload.options)

**Comment by windkh** [comment]
I can try adding an additional parameter for passing all of those optional arguments... maybe you can support me in testing this

**Comment by Dodoooh** [comment]
> I can try adding an additional parameter for passing all of those optional arguments... maybe you can support me in testing this

unfortunately I don't have my NodeRed instance. (on the road) so I could not test it right now. 
But yes I like to help where I can 👍 
Let me know

**Comment by Dodoooh** [comment]
> sendPoll(chatId, msg.payload.content, msg.payload.options)

well i have now tried to integrate it more or less all ways. unfortunately it does not want to work. i think i still understand something wrong 

Would it be possible to see a more detailed example? 

```
msg.payload =
{
    chatId : -12345678,
    type : "poll",
    allows_multiple_answers: true,
    is_anonymous: false,
    content :
    {
        question: ["Montag", "Dienstag"]
    },
    options :
    {
        disable_notification : true
    }
}

return msg;

```

**Comment by windkh** [comment]
version 9.4.3 should fix this. See https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/createpoll.json
