### ISSUE TITLE
Sometimes message on receiver node

### ISSUE THREAD

**Issue by valbuz** [windkh/node-red-contrib-telegrambot#182]
Hi.
There are no incomming messanges at the receive node. The node is connected.
I try also to disable to limit to some users. only the bot name and token is configured.
Sometimes it receives messages, somtimes a long time not.

my installation is on iobroker/nodered on a proxmox vpe

how can i find some more information for debugging?
telegram V:9.4.3

thanks
pat

`[
    {
        "id": "b13efee.389c8",
        "type": "telegram receiver",
        "z": "ac3793bc.95858",
        "name": "",
        "bot": "b1fd3d8e.f5fff",
        "saveDataDir": "",
        "filterCommands": false,
        "x": 300,
        "y": 100,
        "wires": [
            [
                "db4264f8.f15408"
            ],
            [
                "db4264f8.f15408"
            ]
        ]
    },
    {
        "id": "db4264f8.f15408",
        "type": "telegram sender",
        "z": "ac3793bc.95858",
        "name": "",
        "bot": "b1fd3d8e.f5fff",
        "haserroroutput": false,
        "outputs": 1,
        "x": 570,
        "y": 100,
        "wires": [
            [
                "49ae3b06.7878c4"
            ]
        ]
    },
    {
        "id": "49ae3b06.7878c4",
        "type": "debug",
        "z": "ac3793bc.95858",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 790,
        "y": 100,
        "wires": []
    },
    {
        "id": "b1fd3d8e.f5fff",
        "type": "telegram bot",
        "botname": "zw_home_bot",
        "usernames": "",
        "chatids": "",
        "baseapiurl": "",
        "updatemode": "polling",
        "pollinterval": "300",
        "usesocks": false,
        "sockshost": "",
        "socksport": "6667",
        "socksusername": "anonymous",
        "sockspassword": "",
        "bothost": "",
        "botpath": "",
        "localbotport": "8443",
        "publicbotport": "8443",
        "privatekey": "",
        "certificate": "",
        "useselfsignedcertificate": false,
        "sslterminated": false,
        "verboselogging": false
    }
]`

**Comment by windkh** [comment]
Set verboselogging to true

**Comment by valbuz** [comment]
...there was another Node listening on the same bot....but the other flows are all disabled.
i restart the hole iobroker and now it's ok .
thanks for that help!
patrick
