### ISSUE TITLE
Array for message content

### ISSUE THREAD

**Issue by moshed** [windkh/node-red-contrib-telegrambot#184]
In the same vein that its possible to use an array for `chatId` to send one message to multiple chats would it be possible to use an array for `content` to send multiple messages to one chat? 

I know its possible to set the output amount of the function node to 2 and just make 2 payloads but that sees a little overcomplicated. 

Thanks!

**Comment by windkh** [comment]
Should that work for only text messages or all types like photos videos audio…?

**Comment by windkh** [comment]
Btw: you can alreafy send many messages from one function node using one output using as far as I know node.send(msg)

**Comment by moshed** [comment]
Didnt know about `node.send`. Thanks! will check it out. 

I would think it should work for all forms of sendable messages including videos and phots etc., however there already is a media group function (which if I understand correctly sends multiple forms of media) but it might still be useful to be ale to send multiple phots etc. in succession without joining them as a group.
