### ISSUE TITLE
Command nodes not functioning simultaneously

### ISSUE THREAD

**Issue by moshed** [windkh/node-red-contrib-telegrambot#185]
I currently have 3 command nodes set up and they all work... ish. When I edit any part of the flow related the command node (ie the command node itself, the function that sets the proper text, or the sender node) and deploy. all the rest of the commands stop working. 

A workaround I've noticed is that I make a change to _all_ the command nodes and _then_ deploy and all 3 work. see attached video file

[Screen Recording 2021-06-11 at 2.24.07 AM.mov.zip](https://github.com/windkh/node-red-contrib-telegrambot/files/6636267/Screen.Recording.2021-06-11.at.2.24.07.AM.mov.zip)

**Comment by samuelcanadi** [comment]
I have similar problems. If I change anything on the command nodes the others stop working randomly.

**Comment by windkh** [comment]
Did you do a full deploy or a partial one?

**Comment by samuelcanadi** [comment]
Partial (changed nodes)

**Comment by samuelcanadi** [comment]
When I do a full deploy all commands work fine. Is that the only way to do?

**Comment by windkh** [comment]
Yes
