### ISSUE TITLE
InlineQueryResultVideo thumbnail 

### ISSUE THREAD

**Issue by moshed** [windkh/node-red-contrib-telegrambot#186]
I cant seem to get a specified thumbnail to show up correctly on `InlineQueryResultVideo`, but works perfectly fine on `InlineQueryResultArticle` 

when using `InlineQueryResultVideo` 

```
single_result = [{
    type: 'video',
    id: '1',
    video_url: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
    title: 'test',
    mime_type: 'video/mp4',
    thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
    parse_mode: 'Markdown',
    caption: 'test',
    description: 'date',
}]
msg.payload.results = single_result
return msg
```
I get the below without my specified thumbnail 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/8683379/123049643-c6ae4c00-d3cd-11eb-9a0e-a0d95e535299.png">

but when using `InlineQueryResultArticle` with the below, the thumbnail shows up with no issues 

```
single_result = [{
    type: 'article',
    id: 1,
    title: 'test',
    thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
    input_message_content: {
        message_text: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
    },
    description: 'date',
}]
msg.payload.results = single_result
return msg
```

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/8683379/123051173-7e902900-d3cf-11eb-9b0e-a340967a62ac.png">

**Comment by windkh** [comment]
So what are you sending exactly? answerInlineQuery, inline_query?

**Comment by moshed** [comment]
im using inline_query from this section of the readme 

https://github.com/windkh/node-red-contrib-telegrambot#implementing-an-inline_query

![image](https://user-images.githubusercontent.com/8683379/123101145-bb751380-d401-11eb-93f2-6b84c78e7dec.png)

the 2 actions nodes are to easily toggle between the 2 examples I showed above.

**Comment by windkh** [comment]
Hm never tried that. Let me find out ….

**Comment by moshed** [comment]
thanks! am I not doing this the correct way? I never even noticed answerInlineQuery as I  tried inline_query and it worked fine so I assumed I was doing it properly.

**Comment by windkh** [comment]
> I cant seem to get a specified thumbnail to show up correctly on `InlineQueryResultVideo`, but works perfectly fine on `InlineQueryResultArticle`
> 
> when using `InlineQueryResultVideo`
> 
> ```
> single_result = [{
>     type: 'video',
>     id: '1',
>     video_url: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
>     title: 'test',
>     mime_type: 'video/mp4',
>     thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
>     parse_mode: 'Markdown',
>     caption: 'test',
>     description: 'date',
> }]
> msg.payload.results = single_result
> return msg
> ```
> 
> I get the below without my specified thumbnail
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/8683379/123049643-c6ae4c00-d3cd-11eb-9a0e-a0d95e535299.png">
> 
> but when using `InlineQueryResultArticle` with the below, the thumbnail shows up with no issues
> 
> ```
> single_result = [{
>     type: 'article',
>     id: 1,
>     title: 'test',
>     thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
>     input_message_content: {
>         message_text: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
>     },
>     description: 'date',
> }]
> msg.payload.results = single_result
> return msg
> ```
> 
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/8683379/123051173-7e902900-d3cf-11eb-9b0e-a340967a62ac.png">
I took the video version of what you wrote and it generated the following output:
![image](https://user-images.githubusercontent.com/10910767/123682782-beca2e00-d84b-11eb-965a-cf019dfa43d1.png)

--> I can see the thumb and I can click the link: the video is playing
![image](https://user-images.githubusercontent.com/10910767/123682850-d9040c00-d84b-11eb-9b1e-7743c9a33cd4.png)

**Comment by windkh** [comment]
I took the standard desktop client for windows!

**Comment by moshed** [comment]
when I do the article version as you showed the thumbnail works fine. The issue arises when I try to send a video the thumbnail cant be specified see below code:

```
single_result = [{
    type: 'video',
    id: '1',
    video_url: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
    title: 'test',
    mime_type: 'video/mp4',
    thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
    parse_mode: 'Markdown',
    caption: 'test',
    description: 'date',
},
{
    type: 'article',
    id: 2,
    title: 'test',
    thumb_url: 'https://img.mlbstatic.com/mlb-photos/image/upload/w_100/v1/people/660670/headshot/67/current.jpeg',
    input_message_content: {
        message_text: 'https://video.twimg.com/amplify_video/1407558846822981632/vid/1280x720/rttlFu4iUy41szgF.mp4?tag=14',
    },
    description: 'date',
}]
msg.payload.results = single_result
return msg
```
that results in below 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/8683379/123739437-a6223e00-d874-11eb-9c56-d06dbbdaf625.png">

**Comment by moshed** [comment]
@windkh sorry. dont know if you get notifications if the issue is closed so I wanted to tag you!

**Comment by windkh** [comment]
I  will reopen it to give it a second try.

**Comment by windkh** [comment]
@moshed I can confirm that I have the same problem. I can not see anything wrong with your code.
However I can not tell you why the thumbnail is not displayed. At least I guess it has nothing to do with the nodes.

**Comment by moshed** [comment]
ok! good to have some company!
I will see if I can get an answer from telegrams end to see if an issue is with their API
