### ISSUE TITLE
Display list of bot commands?

### ISSUE THREAD

**Issue by philipsd6** [windkh/node-red-contrib-telegrambot#187]
The bot api supports setting a list of supported commands/scopes so that when a user types '/' it pops up a list of supported commands -- how can we do this in Node-RED? 

It seems to me that adding a command node should somehow update Telegram to add it to the bot commands list.

**Comment by windkh** [comment]
I will have to add the support for this in the nodes.

**Comment by windkh** [comment]
should be working in version 9.5.0.
