### ISSUE TITLE
Failed to call /setMyCommands for language

### ISSUE THREAD

**Issue by DarkPark** [windkh/node-red-contrib-telegrambot#192]
After migration to node-red v2.0.3 and upgrade to telegrambot v9.6.0 after each node-red restart I see this line in logs:

```
24 Jul 14:01:00 - [warn] [telegram bot:13314001.6f19] Failed to call /setMyCommands for language : Error: ETELEGRAM: 400 Bad Request: can't parse BotCommand: Can't find field "description"
```

but I don't use setMyCommands
can you please advise?

**Comment by windkh** [comment]
Ok then uncheck the register box in the command node… I will change the default in next version

**Comment by DarkPark** [comment]
Hm. Are you talking about "Register At Telegram Server"?
It was not checked.

**Comment by windkh** [comment]
That is weird… then I will ship just another release…

**Comment by windkh** [comment]
@DarkPark you can delete an add the node again that should work

**Comment by DarkPark** [comment]
I have 4 such nodes. Recreated all of them. Nothing has changed.

**Comment by windkh** [comment]
Version 9.6.1 should fix this... please try it out.

**Comment by DarkPark** [comment]
Node-red doesn't see this plugin update. Restart doesn't help. Maybe you know a way to force it?

**Comment by windkh** [comment]
I did ... it takes some minutes

**Comment by DarkPark** [comment]
Now it works without errors! Thanks :)

**Comment by osulivanDE** [comment]
Hi, i get the same message:
"Failed to call /setMyCommands for language : Error: ETELEGRAM: 400 Bad Request: BOT_COMMAND_INVALID"

when adding a command node with the following settings. 
<img width="816" alt="Bildschirm­foto 2023-05-07 um 21 29 05" src="https://user-images.githubusercontent.com/44095221/236698695-0d846a85-c435-4ea4-8bad-bf240d48aca6.png">

What am i doing wrong?

**Comment by osulivanDE** [comment]
Ok, it seems to take 20minutes until the command is created. Then the error message goes away

**Comment by windkh** [comment]
Hm can you reproduce it?

**Comment by SelyutinAV** [comment]
hi
I also had such a problem. The mistake was that I put capital letters in the name of the command

**Comment by windkh** [comment]
Maybe I should check and prevent that. Thanks for reporting
