### ISSUE TITLE
reciever stops working

### ISSUE THREAD

**Issue by diedder** [windkh/node-red-contrib-telegrambot#195]
I'am not very experienced with the bot burin my flows I'm using reciever an command input of telegram chats. Sometimes the reciever stops woking, even a direct debug node isn't showing messages when chatting with the bot. To fix it I have to deploy with the option complete/all flows, after that it is working fine again.

I'm using the latest version 10.0.0. Pls help an let me know what is needed to invetigate the bug. Thank you!

**Comment by windkh** [comment]
On what hardware do you run the bot?
Mabe it is the same as this one
https://github.com/windkh/node-red-contrib-telegrambot/issues/97

**Comment by diedder** [comment]
It's running on a VM in oracle cloud, no real hardware or raspi.
Only the normal reciever node stops working, the command-recievers are not affected, so I dont't thnik it's the same issue

**Comment by windkh** [comment]
Version 10.0.3 should address this problem. Reopen the issue if the problem still exists.
