### ISSUE TITLE
Unexpected behavior when deploying only the modified flows

### ISSUE THREAD

**Issue by xoancosmed** [windkh/node-red-contrib-telegrambot#197]
I'm used to use the "Modified Flows" option when deploying my flows in Node-RED. However, if I do this after adding a new receiver (or command) node, this makes the older receiver (or command) nodes to stop working.

I don't think this is a critical issue, as to fix it is enough to stop using the "Modified Flows" option when deploying your flow changes, but I didn't see the issue mentioned anywhere in the documentation. Is this a known issue? Is expected to be fixed? **If so, I think it should be added to the documentation** (I can create a PR).

My apologies if this is not the right place to discuss this. And thank you very much for taking your time in reading this note.

## How to reproduce

1) Create a fresh Node-RED instance:

       docker run -it -p 1880:1880 --name mynodered nodered/node-red

2) Install the node-red-contrib-telegrambot palette:

       "dependencies": {
           "node-red-contrib-telegrambot": "~10.0.4"
       }

3) Create a testing bot using `@BotFather`:

       /newbot
       (Send a name for the bot)
       (Send the alias of the bot)
       (Copy the bot token)

4) In the Node-RED flow, add a command node, doble clic on it and add the bot settings:

![Captura de pantalla 2021-08-02 a las 20 19 56](https://user-images.githubusercontent.com/5190070/127906903-8af8a769-2a5e-49b0-9fcf-ae741b6863e4.jpg)

5) Save the changes and write the command that node will handle:

![Captura de pantalla 2021-08-02 a las 20 20 31](https://user-images.githubusercontent.com/5190070/127906927-ca85bfdc-d16b-4f28-b478-03255ad5d50c.jpg)

6) Add a debug node to the first output of the command node:

![Captura de pantalla 2021-08-02 a las 20 26 28](https://user-images.githubusercontent.com/5190070/127906966-39072e38-7fc6-4441-9d25-cc06265f258f.jpg)

7) Make the first deploy:

![Captura de pantalla 2021-08-02 a las 20 26 48](https://user-images.githubusercontent.com/5190070/127907009-40d45dd1-00b1-4f26-bbb7-8672219e9207.jpg)

8) Add a second command node with a different command:

![Captura de pantalla 2021-08-02 a las 20 21 46](https://user-images.githubusercontent.com/5190070/127907269-b506bd03-d54d-4e62-bcce-9323b30fb634.jpg)

9) Add debug nodes to the first output of the new command node:

![Captura de pantalla 2021-08-02 a las 20 28 53](https://user-images.githubusercontent.com/5190070/127907251-dbc406e6-2b78-4ef7-a955-7796ecdaa224.jpg)

10) Deploy using the "Modified Flows" option:

![Captura de pantalla 2021-08-02 a las 20 29 01](https://user-images.githubusercontent.com/5190070/127907291-81dbcac2-be0d-4967-9cd1-ce475ce46b28.jpg)

11) Test sending messages to the bot:

    A) If you send `/world`, the last command we deployed, you'll see the messaged printed in the debug window.
    B) If you send `/hello`, the first command we deployed, you won't see anything in Node-RED's debug window. 

## My testing setup

I tested it in both a Respberry Pi 4 (Node-RED comes pre-installed; using the latest Node stable version) and using the official Docker image. Using node-red-contrib-telegrambot version 10.0.4 in both scenarios.

In case it depends, my web browser is Firefox 89.0.2 (in macOS and Manjaro).

**Comment by windkh** [comment]
Yes that is a known issue for ages. However I can not really tell you why it occurs. Maybe I should just try to debug that once again…. in the meantime extending the readme with a hint would be a useful alternative

**Comment by windkh** [comment]
I improved some register/unregister-event things inside the command nodes.
In addition to that I tried to reproduce your scenario. At least on my machine it sseems to work. 
@xoancosmed  can you test that for me on your machine?

Should work in 10.0.5 (hopefully :) )

**Comment by xoancosmed** [comment]
Good afternoon. Sorry for the delay. I've being testing it several time and now seems to work perfectly for me using the partial deploy. Thank very much your help and time.

**Comment by windkh** [comment]
@xoancosmed ah cool!
