### ISSUE TITLE
Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by jodelkoenig** [windkh/node-red-contrib-telegrambot#198]
I am running latest **2.0.5 node-red docker with this telegrambot**. Node-Red logs indicate this during start:

"(node:55) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 status listeners added to [TelegramBotNode]. Use emitter.setMaxListeners() to increase limit"

Any thoughts/ideas? 

Thanks for this great tool!!!

**Comment by windkh** [comment]
@jodelkoenig I saw this yesterday, too when having more than 11 nodes in one flow. The reason is that all nodes in the flow connect to the one and only configuration node that maintains the server connection. I will try to call setMaxListeners somewhere in the code to get rid of that.....

**Comment by jodelkoenig** [comment]
Cool. Thanks!

**Comment by windkh** [comment]
next version fixes this
