### ISSUE TITLE
No message received by node-red-contrib-telegrambot if message contains a large video

### ISSUE THREAD

**Issue by holnburger** [windkh/node-red-contrib-telegrambot#199]
If I forward messages to the bot it works most of the time (Telegram Receiver + Debug Node) but if I'm forwarding a message with a large video file there's often no debug message trickered and it looks like the bot doesnt receive a message at all.

Example message:
Forward with video doesn't work (isn't triggering the flow): https://t.me/auf1tv/227
Forward with video does work (is triggering the flow): https://t.me/auf1tv/259

**Comment by windkh** [comment]
Please send me a flow so that I can reproduce it

**Comment by holnburger** [comment]
Sure.

Telegram receiver node and debug node:
![image](https://user-images.githubusercontent.com/22478441/129766186-e1bf5bdd-1339-492b-a006-07edf244fef4.png)

Forwarding message from https://t.me/corona_infokanal_bmg/305 (containing a large video) to the bot. 
Expected behaviour: Debug message appearing. Behaviour: No debug message logged.

Forwarding message from https://t.me/corona_infokanal_bmg/306 (contains a short video) to the bot.
Expected Behaviour: Debug message appearing. Beheviour: Debug message received:

`{
   "chatId":REDACTED,
   "messageId":REDACTED,
   "type":"video",
   "content":"BAACAgIAAxkBAAIubmEb5vhmGb6xLb_Vgg-9mi6xSkhFAALiEAACEZsZSOuIE3XZzvKtIAQ",
   "caption":"ℹ️ Nützliche Information\n\n➡️ Aktuell stecken sich viele junge Menschen mit dem Coronavirus an. \n\n⚠️ Doch auch für Sie besteht immer die Gefahr an Long Covid zu erkranken. Dieser Begriff beschreibt die Langzeitfolgen von einer COVID-19-Infektion. \n\n⬆️ Den bestmöglichen Schutz dagegen bietet die Corona-Schutzimpfung!\n\n❗️Deswegen: Lassen Sie sich impfen❗️\n\n🌐 Mehr über Long Covid erfahren Sie unter: https://www.zusammengegencorona.de/informieren/koerperliche-gesundheit/long-covid-langzeitfolgen-einer-covid-19-erkrankung/",
   "date":1629218552,
   "blob":true,
   "weblink":"https://api.telegram.org/file/bot1501414317:AAGDsaJKs2mGT3bpDc7e9vEXCA23uph-ScI/videos/file_212.mp4"
}`


Flow: 

```
[
    {
        "id": "6a697f85.80446",
        "type": "telegram receiver",
        "z": "3a722186.548b2e",
        "name": "",
        "bot": "4dfdd33c.a6179c",
        "saveDataDir": "",
        "filterCommands": false,
        "x": 630,
        "y": 160,
        "wires": [
            [
                "44eaf42a.9e197c"
            ],
            []
        ]
    },
    {
        "id": "44eaf42a.9e197c",
        "type": "debug",
        "z": "3a722186.548b2e",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 860,
        "y": 160,
        "wires": []
    },
    {
        "id": "4dfdd33c.a6179c",
        "type": "telegram bot",
        "botname": "REDACTED",
        "usernames": "",
        "chatids": "{global.get(\"allowedIds\")}",
        "baseapiurl": "",
        "updatemode": "polling",
        "pollinterval": "300",
        "usesocks": false,
        "sockshost": "",
        "socksport": "6667",
        "socksusername": "anonymous",
        "sockspassword": "",
        "bothost": "",
        "botpath": "",
        "localbotport": "8443",
        "publicbotport": "8443",
        "privatekey": "",
        "certificate": "",
        "useselfsignedcertificate": false,
        "sslterminated": false,
        "verboselogging": false
    }
]
```

Node-Red-Contrib-Telegrambot Version: 10.0.4
Node-Red Version Version 1.2.7

Possible source of problem: AutodownloadSetting is set to default value for the bot and media isn't downloaded because it's to big.

**Comment by windkh** [comment]
This seems to be a common problem: bots can only download up to 20MB. This limit is by design of the Telegram server API

see https://github.com/yagop/node-telegram-bot-api/issues/697
