### ISSUE TITLE
Support video_note

### ISSUE THREAD

**Issue by dvv** [windkh/node-red-contrib-telegrambot#20]
Please consider adfing the subj.
AFAICS it's in here https://github.com/yagop/node-telegram-bot-api/issues/332

TIA

**Comment by windkh** [comment]
Good idea.

**Comment by windkh** [comment]
https://github.com/yagop/node-telegram-bot-api doesn't support this yet. As soon as it does I will integrate it.

**Comment by dvv** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L748 , no?

**Comment by windkh** [comment]
Oups!

**Comment by windkh** [comment]
The latest npm release 0.27.1 did not have this function. It seems that we have to wait for the next release until this code from the master branch is included.

**Comment by windkh** [comment]
0.28 version was released in the meantime... I will add the functions soon.

**Comment by windkh** [comment]
@dvv 
How can I send a video note? I can't find the feature on my telegram client (nor desktop, nor iPhone)? Any suggestions?

**Comment by dvv** [comment]
On android I press shortly the mic icon (the rightmost, to the right from attachment icon) and it turns into cam icon.

**Comment by windkh** [comment]
Ah thanks, I found it in the iPhone app, too. Didn't know this!
version 2.6.0 supports it.
