### ISSUE TITLE
command node only last wins

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#200]
Hi,
I have configured multiple command nodes, each handling one command - that was my understanding of the node!

But only the node where the last change has been deployed via node-red can receive commands.

Did I do something wrong? I expected all nodes to receive the command set in the command-field?

Regards
Kallewirsch

**Comment by averlon** [comment]
Hi,
I had to restart node-red - now all nodes act on the commands configured

**Comment by windkh** [comment]
Ok then I close this?
