### ISSUE TITLE
How can i create a menu in bot?

### ISSUE THREAD

**Issue by sergiobaiao** [windkh/node-red-contrib-telegrambot#201]
Hi there,

I'm trying to implement a menu in bot. What i want to implement is a menu where my users can click on the inline keyboard and send a command to the bot, and the bot would automatically reply to the command in accord.

I've tried a lot using the examples, but i can only create a text reply. How can i implement it in a way that the bot will act as the chosen option to be a command, like, if the user clicks on "yes" it would send a command and if the use clicks on "no" it would send a different command?

**Comment by windkh** [comment]
There is an example in the examples folder that handles yes and no. You can do whatever you want in that handler, not only replying text messages. I guess I can not see your problem.

**Comment by windkh** [comment]
see example
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/keyboard.json
