### ISSUE TITLE
send msg to bot, not group chat

### ISSUE THREAD

**Issue by bdydrp** [windkh/node-red-contrib-telegrambot#202]
Is it possible to send messages directly to my bot??

In the config node, i have set the bot name and access token and left usernames/chatID's blank.
But reading other help files, ChatID must be set in the message property

Thanks

**Comment by windkh** [comment]
See readme https://github.com/windkh/node-red-contrib-telegrambot#sending-messages-to-a-specified-chat

**Comment by windkh** [comment]
You communicate with a bot either in a one-to-one chat or using groups or channels where the bot is just a member just like any user. The bot receives all messages from a chat …. But whenever the bot needs to send a message to somebody else you need to specify a chatId.

**Comment by bdydrp** [comment]
OK - So there lies my confusion as i just wish to communicate 1 to 1 with the bot - It will only ever receive messages...and therefore i thought it does not have a chatId!!

I have just created a group anyway for my notifications from NR and added my bot. 

Thanks
