### ISSUE TITLE
How to send multiple photo's in one message

### ISSUE THREAD

**Issue by elvee77** [windkh/node-red-contrib-telegrambot#204]
Hi,

I want to send a message with 5 photo's in that one message.
Now I send 5 different messages with the same "_payload.mediaGroupId_" and with "_payload.blob_" set to true at practically the same time but I receive every picture as a separate message.

Is there any advice on how to send multiple photo's in one message?

Thx!

**Comment by windkh** [comment]
Have a look at the media group example

**Comment by elvee77** [comment]
Aha! Thanks for the right direction. Sometimes one just searches forever but the answer is right in front of you 😁.


`// sendMediaGroup example: send  between 2 and 10 media.
// Note that type can also be video.
// and the caption property is optional.
// see https://core.telegram.org/bots/api#inputmediaphoto
// see https://core.telegram.org/bots/api#inputmediavideo

msg.payload.type = "mediaGroup";
msg.payload.content = [
    {
        type : "photo",
        media : "/pic/frame_1.jpg",
        caption : "Photo 1"
    },
    {
        type : "photo",
        media : "/pic/frame_2.jpg",
        caption : "Photo 2"
    }
];

return msg; `
