### ISSUE TITLE
"msg.payload.type is empty"

### ISSUE THREAD

**Issue by sciaio** [windkh/node-red-contrib-telegrambot#205]
Hello,
following the instructions I was learning how to implement the custom keyboard feature but when I tried the first example with the function node filled with: 

```
var opts = {
  reply_markup: JSON.stringify({
    keyboard: [
      ['A1'],
      ['A2']],
      'resize_keyboard' : true,
      'one_time_keyboard' : true
  })
};


msg.error = false;
// Dialogaufbau
msg.payload.content = 'Selection?';
msg.payload.options = opts;


msg.payload.chatId = 123445;
msg.payload.messageId = 99;
msg.payload.sentMessageId = 99;
msg.payload.type = "message";

return [ msg ];
```

In the debug menu, Node-Red gives me "msg.payload.type is empty":

![image](https://user-images.githubusercontent.com/40140005/130290584-a9b2e42d-a045-47b4-8378-c1c98765331d.png)

Why this happens? The msg.payload.type was there and defined. What am I missing?

Thanks

**Comment by windkh** [comment]
You must use the correct javascript syntax

![image](https://user-images.githubusercontent.com/10910767/130367457-fa24e596-8e03-4d27-959d-d26deffa6722.png)
