### ISSUE TITLE
node red crashes

### ISSUE THREAD

**Issue by RogierQ** [windkh/node-red-contrib-telegrambot#207]
No idea what or when but i get a crash and a restart
The error log shows this:

26 Aug 10:45:14 - TypeError: Cannot convert undefined or null to object
    at Timeout._onTimeout (/home/qusax/.node-red/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:273:57)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

What could this be??

**Comment by windkh** [comment]
I can not reproduce it, can you post a flow here?

**Comment by RogierQ** [comment]
Flow is complicated and with databases. 
Can i test something for you?

**Comment by windkh** [comment]
version 10.0.7 contains some changes that could fix it. Sorry but I did it blindly... if the bug still occurs then reopen the issue.
Please report if it worked....

**Comment by RogierQ** [comment]
Solved! Thanks like always!!!
