### ISSUE TITLE
How to implement a general answer

### ISSUE THREAD

**Issue by LennartHennigs** [windkh/node-red-contrib-telegrambot#21]
Hi, 
I use several command bots to wait for certain actions. But if none of these commands were send I'd like to send a general response. 
But if I add a receiver node for this, it is always triggered, even when a command node could handle the request. 

Any suggestion on I'd be able to implement this. 
I am a bit stuck. 

Cheers.

**Comment by windkh** [comment]
Could you send me an example flow?
I'll take care of this right when I am back from vacation. 
Cheers, too

**Comment by LennartHennigs** [comment]
Hey,
sure. Hope you had a nice holiday.
The (non-working) example looks like is:

`[{"id":"a3914cab.ca4de8","type":"telegram command","z":"e01f7cc.32013","name":"/help","command":"/help","bot":"c2fc9817.bad4a","x":90,"y":340,"wires":[["42170ecb.beb188"],[]]},{"id":"42170ecb.beb188","type":"function","z":"e01f7cc.32013","name":"","func":"var answer   = \"this is help\\r\\n\";\nanswer      += \"more to come\\r\\n\";\nanswer      += \"allowed commands are:\\r\\n\";\nanswer      += \"/hello /help /argh\\r\\n\";\n\nmsg.payload.content = answer;\nmsg.payload.type = \"message\";\n\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":340,"wires":[["4a7d4d63.2fb81c"]]},{"id":"4a7d4d63.2fb81c","type":"telegram sender","z":"e01f7cc.32013","name":"","bot":"c2fc9817.bad4a","x":610,"y":220,"wires":[["a0c83bdc.00092"]]},{"id":"b35ef357.35a148","type":"telegram command","z":"e01f7cc.32013","name":"/argh","command":"/argh","bot":"c2fc9817.bad4a","x":90,"y":400,"wires":[["50fa57f2.a6485"],[]]},{"id":"50fa57f2.a6485","type":"function","z":"e01f7cc.32013","name":"","func":"var answer = \"roar!\\r\\n\";\nmsg.payload.content = answer;\nmsg.payload.type = \"message\";\n\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":400,"wires":[["4a7d4d63.2fb81c"]]},{"id":"99e818e8.a42038","type":"telegram command","z":"e01f7cc.32013","name":"/hello","command":"/hello","bot":"c2fc9817.bad4a","x":90,"y":280,"wires":[["3c28ad.a6d85f54"],[]]},{"id":"3c28ad.a6d85f54","type":"function","z":"e01f7cc.32013","name":"","func":"var answer = \"Who are you?\\r\\n\";\nmsg.payload.content = answer;\nmsg.payload.type = \"message\";\n\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":280,"wires":[["4a7d4d63.2fb81c"]]},{"id":"c1227f33.b8aea","type":"telegram receiver","z":"e01f7cc.32013","name":"telegram msg","bot":"c2fc9817.bad4a","saveDataDir":"","x":110,"y":160,"wires":[["f9615d15.521478","1ae47ca0.3f9ebb"],["61aa8fb9.547e2"]]},{"id":"a0c83bdc.00092","type":"debug","z":"e01f7cc.32013","name":"","active":true,"console":"false","complete":"false","x":810,"y":220,"wires":[]},{"id":"61aa8fb9.547e2","type":"function","z":"e01f7cc.32013","name":"unknown user","func":"\nvar answer = \"Who are you?\\r\\n\";\nmsg.payload.content = answer;\nmsg.payload.type = \"message\";\n\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":220,"wires":[["4a7d4d63.2fb81c"]]},{"id":"f9615d15.521478","type":"function","z":"e01f7cc.32013","name":"unknown keyword","func":"var answer = \"Ich möchte diesen Teppich nicht kaufen.\\r\\n\";\nmsg.payload.content = answer;\nmsg.payload.type = \"message\";\n\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":120,"wires":[["4a7d4d63.2fb81c"]]},{"id":"1ae47ca0.3f9ebb","type":"debug","z":"e01f7cc.32013","name":"","active":true,"console":"false","complete":"false","x":350,"y":160,"wires":[]},{"id":"c2fc9817.bad4a","type":"telegram bot","z":"","botname":"fooBot","usernames":"lennarthennigs","chatids":""}]`

Now the "telegram message node" and one of the command nodes is triggered when a command is entered.

**Comment by windkh** [comment]
Ok, I just had a look at your flow. Here my explanation:
The receiver node receives simply everything from the bot. 
The command node is a receiver node with a filter.
All nodes work independently from each other, so there is no kind of "chain of respnsibility" for all receiver nodes. 

If I get you right you want to send some message if the user entered an unknown command. You can achieve this by implementing your own filter in the function node called "unknown command " which is following your receiver node:
`
var knownCommands = ['/help', '/hello', '/argh'];

// check if this is a text message
if(msg.payload.type == "message"){
    var text = msg.payload.content;
    
    var commandValid = false;
    // check if the message starts with one of the known commands
    for (var i = 0; i < knownCommands.length; i++) {
        
        if(text.startsWith(knownCommands[i])){
            commandValid = true;
            break;
        }
    }
    
    if(!commandValid){
        var answer = "Ich möchte diesen Teppich nicht kaufen.\r\n";
        msg.payload.content = answer;
        msg.payload.type = "message";

        return msg;
    }
    else{
        return null;
    }
}
`

**Comment by windkh** [comment]
In this case I would only implement one receiver node which is followed by a function node which acts as a switch for all commands. The other command nodes would be not neccessary then.

// check if this is a text message
if(msg.payload.type == "message"){

    var tokens = msg.payload.content.split(" ");

    switch(tokens[0])
    {
        case "/help":
            msg.payload.content = "You help text here";
            return [msg, null];
        case "/hello":
            msg.payload.content = "You hello text here";
            return [msg, null];
        case "/argh":
            msg.payload.content = "You argh text here";
            return [msg, null];
        default:
            msg.payload.content = "Unknown command.";
            return [null, msg];
    }
}
