### ISSUE TITLE
Sending a Photo: not only from save-file? How to flow?

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#211]
on my flow an image is coming as base64 over MQTT.
i always save that and asemmble the send-message with a save-file as content.
are there other ways in node red to send that image without saving as a file?

How do i get the base64 image adressed in the content-option?

![image](https://user-images.githubusercontent.com/5937811/132576609-57cdef58-dc09-4dbd-a5c1-1aa1bfa8f712.png)

j-expression:
```
{
   "chatId": "-123456789",
   "type": "photo",
   "caption": "AI gesichtet: "  & msg.name & " (" & msg.confidence & "% )",
   "content": "/tmp/fm.jpg",
   "options": 
    {
       "disable_notification": "true"
    } 

}
```` 
![image](https://user-images.githubusercontent.com/5937811/132576981-200f56c8-a56d-4477-8257-0fce03ee80e8.png)

thanks a lot for ideas...

**Comment by windkh** [comment]
https://discourse.nodered.org/t/node-red-sending-picture-to-telegram/39656

you can use the buffer as content if it is a known format: e.g. Jpeg….

**Comment by ozett** [comment]
wow, real quick. i look up your hint instantly ...

found also something with multpart... but dont know how to use that... 🤫 

https://core.telegram.org/bots/api#sending-files
![image](https://user-images.githubusercontent.com/5937811/132579861-6a442a74-d411-43cf-ad98-eec926de065f.png)

**Comment by windkh** [comment]
The send function checks if the content is a file_id, a url,or a buffer….
if it is a buffer then the media type is determined and then send right away ….
Make sure that the buffer size does not exceed the limit and that the format is supported.

**Comment by ozett** [comment]
thanks for helping. fantastic. got it working with the func-node.

the last part is to reference msg.name in the function-node as part of the  caption. (?)
must be another secret syntax for me stupid low-coder... 😄 
![image](https://user-images.githubusercontent.com/5937811/132583618-e9f8e6a8-4a94-4f4d-8f56-2f965f7d4936.png)

**Comment by windkh** [comment]
caption : „AI gesichtet: „ + msg.name + „ „ + msg.confidence,

**Comment by windkh** [comment]
Btw typo: picture not piture … in line 3

**Comment by windkh** [comment]
Funktioniert das double-take?

**Comment by ozett** [comment]
ja, danke. 💐  auch noch so spät:  Jsonata "&" -> javascript "+"
exchanged the concatenation to javascript-style (and correct the typo 😄 )

🟢  ```caption: "AI gesichtet: "  + msg.name + " (" + msg.confidence + "% )",```

**Comment by ozett** [comment]
> Funktioniert das double-take?

astrein, letzte beta! mit compreface
bissl gefummel mit docker-compose. läuft jetzt bei mir paralell zu python und yolo, und kann für face-rec optimiert werden...
spannend...

**Comment by ozett** [comment]
spannend: 
https://documenter.getpostman.com/view/1013188/TzsWuAa8#aa26f5ce-f215-4771-a6cc-efb40a24c99e

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/132585774-baa3af8c-c1b2-47f6-b881-bfad9843fc21.png)

**Comment by windkh** [comment]
Muss ich auch mal probieren

**Comment by windkh** [comment]
Hm kann das auch trainiert werden um namen zuzuordnen?

**Comment by ozett** [comment]
> Hm kann das auch trainiert werden um namen zuzuordnen?

genauso läufts... 😄 

![image](https://user-images.githubusercontent.com/5937811/132586908-dd8debe3-d7c6-4a6d-ba90-da3fb84f76b2.png)

**Comment by windkh** [comment]
Oh ja das sieht gut aus… musst mir mal live zeigen…

**Comment by ozett** [comment]
😉   -> https://github.com/jakowenko/double-take#docker-compose
