### ISSUE TITLE
dont get al messages

### ISSUE THREAD

**Issue by higgis-daax** [windkh/node-red-contrib-telegrambot#213]
when I write something to my bot I get it in node red but if node red send to my bot I do not get that message in node red. Can you set that node red gets / can read all messages in the group?

**Comment by windkh** [comment]
Does the echo example work? 
To allow reading all messages from a group you must set the privacy mode using botfather
https://core.telegram.org/bots#privacy-mode

**Comment by higgis-daax** [comment]
if I send a message to my bot or group, I get node red to send the same
message back. But if I send a message via node red, I can not get this via
debug.

What I tried to do is to be able to automatically send different messages
to node red via bags with different commands, but when these do not come
up, I got stuck :-(

I have set my group to public and my bot to enabel.

Den tis 28 sep. 2021 kl 21:15 skrev Karl-Heinz Wind <
***@***.***>:

**Comment by windkh** [comment]
Have you tried the examples in the example folder?

**Comment by windkh** [comment]
There are plenty of tutorial videos on youtube that show you step by step what to do

**Comment by higgis-daax** [comment]
Have watched most of the youtube clips :-)

If I write a message to myself in the group, node red reacts to this and in
the chat it comes to "right" then I can get node red to send this back and
what I get back ends up on "left".

If I send another message to the group via bags or node red, it ends up
directly to the "left" and node red does not seem to know that I have
received a new message.

Den tis 28 sep. 2021 kl 21:34 skrev Karl-Heinz Wind <
***@***.***>:

**Comment by windkh** [comment]
I do not really what you mean with 
"...and node red does not seem to know that I have received a new message."

and secondly what is "bags" ???

**Comment by higgis-daax** [comment]
sorry is googel translate :-)

I have tried and read more today and what I understand is the problem that
when I send a message to the group it is via one of my bots and you can not
what I understand make it "read" what a bot has sent. And that's why it's
only come up if I myself sit and write the message.

Den ons 29 sep. 2021 kl 15:10 skrev Karl-Heinz Wind <
***@***.***>:

**Comment by windkh** [comment]
yes that is correct. The bot acts like a real person in a chat.
