### ISSUE TITLE
No menu - command node - register at Telegram server

### ISSUE THREAD

**Issue by tomcollis** [windkh/node-red-contrib-telegrambot#214]
Using multiple command nodes on a bot, the commands are 'registered' and work but they do not add a menu button in the bottom left. Adding commands via BotFather does create a menu.

I'll be honest, I'm not sure if this an issue with the Telegram Bot API missing a feature or the way this node module registers the commands.

Telegram Blog - Bot Menu
https://telegram.org/blog/animated-backgrounds#bot-menu

**Comment by windkh** [comment]
Hm… I do not know if that can be influnced via the API… but I will have a look at it. Maybe there is an option. Btw did you use the default scope or specified a language?

**Comment by tomcollis** [comment]
I used the default scope.
![image](https://user-images.githubusercontent.com/22452596/135347888-e79211c5-8a15-49c1-97dc-062f0fdc1350.png)

**Comment by foorschtbar** [comment]
Same problem here :(

**Comment by windkh** [comment]
I can not control the behaviors of the clients in a different way as it is already implemented. Sorry... maybe there will be an update ... let's wait until then
