### ISSUE TITLE
The node works but stop receiving messages

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#218]
Hi, when I've noticed this problem when I was using 10.0.7, the node works sending messages only, no error logs, it just stop receiving. After upgrade to 10.0.9 (but I believe a node reboot of .0.7 was enough too, already tested it), I've noticed at boot a couple of response for two command I (probably) sent a few minutes before when I attempt to figure out what was wrong.. but maybe it's just my phone's telegram app that was unable to send them before and sent them now, Or old command in node cache not yet performed?
This problem may become from a command which hasn't been answered.. an the node still waiting for that answer before receive any other command, I've figured that out whan I made a mistake and didn't give an answer after a command. How that happened (I've sent acommand and haven't replied) I don't know. If it is that may you please introduce a timeout and after it the receive node start behaving like before? thanks
How can I debug i

Node-RED version: v1.3.5
10 Oct 14:27:52 - [info] Node.js  version: v14.17.2
10 Oct 14:27:52 - [info] Linux 5.10.48-v7+ arm LE

**Comment by Barabba11** [comment]
Thanks for answer, later, I'm not home now. I think you didn't catch me fully, all wa online and working, sending messages, by to output from receiving. It happened already when wrongly I haven't answered to a keyboard question

**Comment by windkh** [comment]
So can you explain step by step how to reproduce your problem?

**Comment by Barabba11** [comment]
I've tried to reproduce the problem but I?m not more able, if I launche the command and avoid to push on the answer, typing something else, it goes to deactivated. At least there is a decision about this question. The problem was but I upldated to the lates version, seems working. If it will react like that again I'll notice here
