### ISSUE TITLE
send / receive msgs on your own telegram account

### ISSUE THREAD

**Issue by lu4t** [windkh/node-red-contrib-telegrambot#219]
Hi,
thanks for the great job, the nodes are awesom and very well documented.

Here is the use case I am trying to implement: is there I way to use the telegrambot nodes, to send/receive msgs to your account? (not to a bot created through botfather, but to a regular human telegram account).

I was evaluating using js telegram clients available out there, but after using the nodes of this repo for a while, it would be easier for me. 

I created an app and API key at https://my.telegram.org but this is not providing a token as the one used on the config of the telegrambot nodes. Is there anything I can do to get what I need done?

Thanks!!

**Comment by windkh** [comment]
Hi, I think this was already requested before by somebody else.
Short Answer: I won't implement this.

Lang Answer:
The nodes make use of the BOT-API. The feature that you request is only available in the client API (you already figured that out). Maybe I will create another set of nodes for that idea but as these nodes are called .... telegrambot and not telegramclient it would not really fit.
