### ISSUE TITLE
"Error stopping node: Close timed out" on re-deploy when Update Mode is set to None

### ISSUE THREAD

**Issue by reyemxela** [windkh/node-red-contrib-telegrambot#220]
Took some fiddling to narrow down exactly what was causing this.

When Update Mode is set to None, Node-RED hangs and throws that error when trying to re-deploy. Polling mode works fine.

I'm only using this to send notifications out at the moment, so I had disabled polling, and that's when I ran into this issue. I turned polling back on with a super long delay as a workaround for now.

I haven't had a chance to jump into the source to see if I can spot anything obvious that would cause this error yet.

**Node-RED:** v2.1.3
**telegrambot:** v10.0.9

**Comment by windkh** [comment]
Thanks for reporting, I will try to reproduce it

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/144760394-90acb46f-d2f3-42f3-b540-b21116b837e5.png)

After several redeploys
