### ISSUE TITLE
receiving messages from other bots 

### ISSUE THREAD

**Issue by Marcopolox13** [windkh/node-red-contrib-telegrambot#221]
Hey
I use the Telegramm bot for my openhab server and for connecting ifttt to it. 
The problem is, when the ifttt bot writes a message to my node red bot it isn't receiving it, I checked via debug.

**Comment by lstefanlombard** [comment]
I'm having a similar problem. I think it might have something to do with the /start command which starts the chat with the bot

**Comment by windkh** [comment]
@Marcopolox13 maybe you have to show this to me, because I can not really get what your problem is

**Comment by Marcopolox13** [comment]
@windkh I have a group chat with the node red bot, the ifttt bot and me. 
If I send a comment to the group my node red server reads it but if the ifttt bot writes the same comment the node red bot ignores it. I checked it with debug, node red just reads my messages and completely ignors everything from the ifttt bot.

**Comment by windkh** [comment]
https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

Is that the explanation to your problem?

**Comment by Marcopolox13** [comment]
Yes, thanks.

Isn't there a way around it?

**Comment by windkh** [comment]
It depends on what use case you have… maybe what you wantbto achieve can be done in a different way. But there is no way to let bots play ping pong with messages as this can lead to endless loops.

**Comment by Marcopolox13** [comment]
Ok thanks
