### ISSUE TITLE
force_reply to messages 

### ISSUE THREAD

**Issue by moshed** [windkh/node-red-contrib-telegrambot#222]
is it possible to issue a command to the api to force a reply to a messages as seen here. 
https://core.telegram.org/bots/api#forcereply

I have tried 

```
msg.payload = {
    content: 'test',
    chatId: msg.payload.chatId,
    type: 'message',
    force_reply: true
}
```

and 

```
msg.payload = {
    content: 'test',
    chatId: msg.payload.chatId,
    type: 'message',
    options: {
        force_reply: true
    }
}
```

but those don't seem to work

**Comment by windkh** [comment]
'message' takes the options described here
https://core.telegram.org/bots/api#sendmessage maybe you set 
reply_markup with a ForceReply object

Maybe try something like that
`
msg.payload = {
    content: 'test',
    chatId: msg.payload.chatId,
    type: 'message',
    options: {
        reply_markup : { 
           force_reply : true
       }
    }
}
`

**Comment by moshed** [comment]
works perfectly! thanks!

**Comment by windkh** [comment]
ok nice...
