### ISSUE TITLE
Not all chat messages received by receiver node

### ISSUE THREAD

**Issue by langrock** [windkh/node-red-contrib-telegrambot#226]
This may be a user error, a Telegram restriction, or a bug, but I am testing a group channel which has three users. A bot I created (and added to Node-RED) set to admin, the IFTTT bot also set to admin, and my own user. The receive node shows messages I post to either the bot directly or the group channel. Yet, when the IFTTT bot posts to the same group, the message is not being forwarded to the receiver node. The bot's privacy settings are set to disabled, which allegedly should imply that all messages are received by the bot.

**Comment by windkh** [comment]
I guess this is a duplicate:
see https://github.com/windkh/node-red-contrib-telegrambot/issues/221

**Comment by langrock** [comment]
Ah, indeed, that's exactly the same issue. Too bad that there isn't a solution for this due to the limitations imposed by Telegram. If someone else runs into this, I am now using io.adafruit.com to connect IFTTT and Node-RED.
