### ISSUE TITLE
Example "onreplymessage" doesn't work

### ISSUE THREAD

**Issue by bonny1992** [windkh/node-red-contrib-telegrambot#23]
It simply does not get the reply for the message, I just copied and incolled the nodes in a new flow, changed the bot and it does absolutely nothing :\

**Comment by windkh** [comment]
Could you provide your flow please?
Did you have a look at the example flows?

**Comment by bonny1992** [comment]
Sorry for the late reply.

`[{"id":"66de13bf.907a5c","type":"tab","label":"Bot Telegram","disabled":false,"info":""},{"id":"7b601510.d3c85c","type":"telegram command","z":"66de13bf.907a5c","name":"/test","command":"/test","bot":"59a6dea.d78d92","x":141,"y":120,"wires":[["68eedad.9b95b24"],[]]},{"id":"68eedad.9b95b24","type":"function","z":"66de13bf.907a5c","name":"Crea domanda","func":"msg.payload.type = 'message';\nmsg.payload.content = 'Vuoi farlo davvero?';\nmsg.payload.options = {reply_to_message_id : msg.payload.messageId}\nreturn [ msg ];","outputs":1,"noerr":0,"x":340,"y":120,"wires":[["5e17d159.797fc","f5f84149.0350a"]]},{"id":"5e17d159.797fc","type":"telegram sender","z":"66de13bf.907a5c","name":"Invia domanda","bot":"59a6dea.d78d92","x":531,"y":123,"wires":[["96ee8f3b.e537b"]]},{"id":"ca7e7a95.e5c8d8","type":"function","z":"66de13bf.907a5c","name":"Risposta fittizia","func":"msg.payload.content = 'Risposta a caso??';\nreturn msg;","outputs":1,"noerr":0,"x":988,"y":118,"wires":[["6fb1c1be.c44c1"]]},{"id":"96ee8f3b.e537b","type":"telegram reply","z":"66de13bf.907a5c","name":"Aspettati risposta","bot":"59a6dea.d78d92","x":750,"y":120,"wires":[["ca7e7a95.e5c8d8"]]},{"id":"1a910b.72276ef6","type":"catch","z":"66de13bf.907a5c","name":"","scope":null,"x":244,"y":432,"wires":[["f5f84149.0350a"]]},{"id":"f5f84149.0350a","type":"debug","z":"66de13bf.907a5c","name":"debug","active":true,"console":"true","complete":"payload","x":498,"y":437,"wires":[]},{"id":"6fb1c1be.c44c1","type":"telegram sender","z":"66de13bf.907a5c","name":"","bot":"59a6dea.d78d92","x":1200,"y":116,"wires":[[]]},{"id":"59a6dea.d78d92","type":"telegram bot","z":"","botname":"BonnyTestBot","usernames":"","chatids":""}]`

Here's the full code for the flow.
It should be extremely similar to the example flow "onreplymessage" :/

**Comment by windkh** [comment]
Ok I probably know what your problem is. First of all the flow works as expected. 
The ReplyNode receives a message if you explicitly answer to a specified chat-message.
This does not mean by simply typing a message below the received one, but by clicking on the message you received from the bot and choosing "answer"  from the context menue.

**Comment by bonny1992** [comment]
Ooooh now I understood.

Sorry, I thought it was like `ConversationHandler` from the python-telegram-bot library, which accepts every message after that!

To achieve something like that what can I use? Is there any node that can be used to hold a conversation?

**Comment by windkh** [comment]
See also 
https://github.com/yagop/node-telegram-bot-api/blob/release/doc/help.md#pitfalls

Well interacting with the user can be done using keyboards if this is ok for you. 
Another option would be to store information in your flow to control some kind of state-machine.
It really depends on the kind of conversation you intend to realize.
Is it a kind of simple "question and answer" or should it be a conversation over more than one interactions?

**Comment by bonny1992** [comment]
I thought too of interacting with the user by using keyboards.
Should I check the messages with regex?

**Comment by windkh** [comment]
Yes, that would be an option. Combined with a switch and several outputs this should work. Good luck!
