### ISSUE TITLE
How to receive "from_user" in the payload of the receiver node

### ISSUE THREAD

**Issue by borelg** [windkh/node-red-contrib-telegrambot#231]
Hello,

is there any way to retrieve the name of the user who has sent the message and then received from the "Receiver node"?
In the payload I receive only the following element:
chatId: 
messageId: 
type: ""
content: ""
date: 

I have understood that the field "from_user" might be the one.

Thanks in advance!

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/148291010-2f054998-ac9c-4bbf-b91e-43da855adda9.png)

**Comment by windkh** [comment]
sorry I forgot to mention that this can be found in originalMessage.from.first_name and so on.

**Comment by borelg** [comment]
Hi windkh,

thanks for the very quick reply.
However, I receive only the payload from the "Receiver node".

![image](https://user-images.githubusercontent.com/37478033/148292593-ccaf2aa6-b87f-4dd4-9359-fc5f38b0d33b.png)

**Comment by windkh** [comment]
Then configure the debug node so that it shows the complete message object and not only payload

**Comment by borelg** [comment]
.... yes, you are right.
Thanks :)
