### ISSUE TITLE
Can't install telegram bot anymore

### ISSUE THREAD

**Issue by Schmetterfliege** [windkh/node-red-contrib-telegrambot#232]
I just updated a bunch of nodes, including the telegram bot.
Afterwards, I wanted to check but the telegrambot nodes were gone.
Looking at my palette, I can see that it's not installed.

When trying to install, it fails and outputs these messages:

````
2022-02-02T21:48:36.584Z Installieren : node-red-contrib-telegrambot 11.2.1

2022-02-02T21:48:36.739Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-telegrambot@11.2.1
2022-02-02T21:48:42.011Z [err] npm
2022-02-02T21:48:42.012Z [err]  
2022-02-02T21:48:42.012Z [err] WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2022-02-02T21:48:46.476Z [out] + node-red-contrib-telegrambot@11.2.1
2022-02-02T21:48:46.476Z [out] updated 1 package in 8.103s
2022-02-02T21:48:46.511Z rc=0`
```

**Comment by Schmetterfliege** [comment]
remark: installing telegrambot-home works just fine, so I assume the issue is indeed with the telegrambot nodes

**Comment by Schmetterfliege** [comment]
I should learn to read...
the NR adapter in IoBroker runs an older version, and triggering the update for this Node uninstalled it due to version incompatibility... (my NR is still on version 1.3.7)

**Comment by windkh** [comment]
well to be honest it should also work with your NR version but I had to add a tag in the package.json where the version is defined as >=2.0 ...

**Comment by Schmetterfliege** [comment]
War trotzdem mein Fehler :)

Ich hatte dann versucht per CLI die 10.0.2 von dem Module hier zu installieren, und dabei versehentlich NR auf 2.2.0 geupdated (keine Ahnung wie^^).
Insofern das sich das "Problem" für mich dann sowieso erledigt :)

**Comment by windkh** [comment]
Does the latest version work?Gesendet mit der WEB.DE iPad AppAm 02.02.22 um 22:51 schrieb Schmetterfliege
                
            
            
                
                    Von: "Schmetterfliege" ***@***.***>Datum: 2. Februar 2022An: "windkh/node-red-contrib-telegrambot" ***@***.***>Cc: "Subscribed" ***@***.***>Betreff: [windkh/node-red-contrib-telegrambot] Can't install telegram bot anymore (Issue #232)
                
                
I just updated a bunch of nodes, including the telegram bot.
Afterwards, I wanted to check but the telegrambot nodes were gone.
Looking at my palette, I can see that it's not installed.
When trying to install, it fails and outputs these messages:
`2022-02-02T21:48:36.584Z Installieren : node-red-contrib-telegrambot 11.2.1
2022-02-02T21:48:36.739Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production ***@***.***
2022-02-02T21:48:42.011Z [err] npm
2022-02-02T21:48:42.012Z [err]
2022-02-02T21:48:42.012Z [err] WARN deprecated ***@***.***: request-promise has been deprecated because it extends the now deprecated request package, see request/request#3142
2022-02-02T21:48:46.476Z [out] + ***@***.***
2022-02-02T21:48:46.476Z [out] updated 1 package in 8.103s
2022-02-02T21:48:46.511Z rc=0`

**Comment by Schmetterfliege** [comment]
Yes, now it works perfectly fine :)

There was just a little bug that I also had before, not sure if it's a NR issue or an issue with this module.
I have a flow with all the telegram nodes, and suddenly it happened that the command nodes or event nodes stopped working (they didn't react when sending the command or any message).
I then have to copy-paste the node and delete the "original" one, and it works fine.
If I then place it a second time, the first one doesn't work anymore.
At some point all command nodes stopped doing anything, and by replacing one of them twice and deleting one in a different flow, everything started working fine again.
The issue didn't pop up again yet though, so everything works fine.

It's definitely not the nodes itself, because out of ~ 15 nodes I only replace one a few times, and then all started working fine again.
Having the same node twice (copy paste) also works flawlessly now.

No idea what triggered this and where the issue originated from.

**Comment by Schmetterfliege** [comment]
And I can't say 110% for sure that this only happened with the nodes from this module.

If it happens again, I'll export the flow and create an issue - just to see if anyone is able to find out if there is a broken node in the flow that breaks all other nodes :D

**Comment by windkh** [comment]
OK glad that it works now. I have no clue what could have triggered that problem ....
 

Gesendet: Donnerstag, 03. Februar 2022 um 20:01 Uhr
Von: "Schmetterfliege" ***@***.***>
An: "windkh/node-red-contrib-telegrambot" ***@***.***>
Cc: "Karl-Heinz Wind" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [windkh/node-red-contrib-telegrambot] Can't install telegram bot anymore (Issue #232)


 

And I can't say 110% for sure that this only happened with the nodes from this module.

If it happens again, I'll export the flow and create an issue - just to see if anyone is able to find out if there is a broken node in the flow that breaks all other nodes :D

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
