### ISSUE TITLE
Reply Node doesn't work as expected

### ISSUE THREAD

**Issue by wolfdave** [windkh/node-red-contrib-telegrambot#233]
First of all I'd like to thank you for this great package. I love it! 
Everything works just fine. 

Now I wanted to send a message through a "Sender"-Node and then catch the answer with a "Reply"-Node. I used the "Answer-Feature" in Telegram. Not only an inline answer! I tried it on Telegram Web (right-click an reply) and on mobile. 

If i use a command (green) like in the examples it works. But if I change it to a "Sender"-Node it just sends the message but ignores the reply. 

![image](https://user-images.githubusercontent.com/49744216/152634180-05d51ef8-cc04-4e81-8402-ddb3da530eec.png)

Maybe I misunderstood the purpose of the "Reply"-Node or just did a mistake in the configuration. 

I've also tried to make it more simple like this: 
![image](https://user-images.githubusercontent.com/49744216/152634245-6f7266de-2e16-4b9b-aaf3-56c89868b5de.png)

My node-red is the latest version (2.2.0) and node-red-contrig-telegrambot is 11.2.3. 

Thank you for your help and support!

**Comment by windkh** [comment]
Hm what payload do you inject in the first example?
I will try to reproduce your problem

**Comment by wolfdave** [comment]
The Inject Node looks like this: 
![image](https://user-images.githubusercontent.com/49744216/152648432-3142f02b-a663-4d91-a415-90cff7406eab.png)

Thank you very much!

**Comment by windkh** [comment]
Why do you not just trigger the function node which would send the question???? You have just added another sender node???

**Comment by wolfdave** [comment]
I just did this for an quick&dirty testing. Later I will do something like this: 
![image](https://user-images.githubusercontent.com/49744216/154988751-e5ac8fc6-a809-45b0-a929-595c2df27501.png)

For example: If we get a phonecall, the bot is writing to someone and if the user chooses reply, the bot takes the answer as content as body for a new ticket in our ticketsystem. 

Bot: Hi, we have a new call from 0123-456789. Do you wish to create a ticket? If yes, send me the content as an answer to this message. 
User: (selects reply) This is a Testmessage
Bot: Thank you. Your Ticket #1234567 has been created.

**Comment by windkh** [comment]
Please send me the flow so that I can see what is going on

**Comment by windkh** [comment]
closed as author did not reply
