### ISSUE TITLE
unable to update / install

### ISSUE THREAD

**Issue by dibadodo** [windkh/node-red-contrib-telegrambot#235]
I was running th telegram bot for a lot of time. Today i trying to install the update. 
The install remove the existing version but is unable install the new version. 
Install log:
2022-02-11T22:25:15.246Z installieren : node-red-contrib-telegrambot 11.2.3

2022-02-11T22:25:15.273Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-telegrambot@11.2.3
2022-02-11T22:25:24.479Z [out] 
2022-02-11T22:25:24.479Z [out] up to date in 8s
2022-02-11T22:25:24.575Z rc=0

I running node-red as redmatic  inside a RaspberryMatic on Raspi3

Would be nice when i can get the old version to get it working again if the new version not running on my environment.

Greetings

**Comment by jbrown123** [comment]
I just attempted to install from scratch (no previous version). I got an error as well.

Install log
```
2022-02-11T22:32:29.839Z Install : node-red-contrib-telegrambot 11.2.3

2022-02-11T22:32:28.630Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-telegrambot@11.2.3
2022-02-11T22:33:08.517Z [err] npm
2022-02-11T22:33:08.518Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2022-02-11T22:33:47.852Z [out] + node-red-contrib-telegrambot@11.2.3
2022-02-11T22:33:47.852Z [out] added 39 packages from 72 contributors in 72.417s
2022-02-11T22:33:47.981Z rc=0
```

**Comment by windkh** [comment]
I guess node red checks for the minimum supported version in package.json. 
maybe it is better to remove these properties. The deprecation warning can be ignored btw

**Comment by dibadodo** [comment]
You mean remove this properties inside node red or on the package side?
When on side of node red - Where and How?

**Comment by dibadodo** [comment]
Please can you send me the old version to get it working again? Because of missing nodes the entire flows are disabled. :(
I dont want to delete all telegram nodes...

Thank you

**Comment by windkh** [comment]
You can download all releases from this repo under Releases on the right pane

**Comment by dibadodo** [comment]
> You can download all releases from this repo under Releases on the right pane

I see under release only source code files as tar or zip. Are you sure I can upload them directly in node red?

**Comment by windkh** [comment]
You can simply replace the folder inside node red with those files… it should be even enough to just copy the two files 99-telegrambot.js and .html…. 
As an alternativ you can install the package into nodered via command line
Npm install …

**Comment by dibadodo** [comment]
Replacing the folder does not work, I think the old package was uninstalled during the update process. 
I can use directly the source files? Sorry, I'm not a developer - I'm just a user.... ;)

**Comment by colinl** [comment]
I don't see any errors in the install logs shown.  What exactly is the problem that people are having here?

**Comment by colinl** [comment]
For anyone who does want to install an old version then go into your .node-red folder (or wherever the flows are located) and run
`npm install node-red-contrib-telegrambot@a.b.c`
where a.b.c is the version you want.

**Comment by dibadodo** [comment]
sorry, direct install with npm seems doesn't work on Redmatic on Rapsberrymatic. I can upload a tar.gz file or i install direct from repository but only from gui

**Comment by colinl** [comment]
In what way does the npm install not work?  What does it say when you try to do it?

**Comment by dibadodo** [comment]
npm via cli don't work - that is the output:

/usr/lib/node_modules# npm install node-red-contrib-telegrambot
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EROFS
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, access '/usr/lib/node_modules'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2022-02-12T21_43_44_177Z-debug.log

I'm logged in as root.

**Comment by colinl** [comment]
You are in the wrong folder.  You must be in the folder where your flows file is (usually the user's .node-red folder).

**Comment by colinl** [comment]
And don't run it as root.  Run it as the user that runs node-red (unless that is root which is almost always a bad idea.

**Comment by dibadodo** [comment]
I have no idea which path is the right and i don't know which user is used - as explained on my first post, this is a raspberrymatic installation and redmatic is a plugin on this - Raspberrymatic is installed as a image and will only accessed via browser - redmatic will be installed via upload a file from gui - that is all - so i don't know where and on which user is each service running - because of this i don't want to install some thing via cli and outside the normal system - but i was looking how to use npm on this system - that is the output:

/usr/local/addons/redmatic/var# npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-telegrambot@11.2.3

up to date, audited 589 packages in 8s

57 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (3 low, 2 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

The package is not available on redmatic, i have restarted the redmatic but is still not available - i got still the the message:

Flows were stopped due to missing nodetypes.

The package is not show as installed on package manager.

**Comment by dibadodo** [comment]
i see the packe with npm list but not on gui and package manager:

 npm list
node-red-project@0.0.1 /usr/local/addons/redmatic/var
+-- node-red-contrib-ccu@3.4.2
+-- node-red-contrib-combine@1.8.1
+-- node-red-contrib-deconz@2.3.3
+-- node-red-contrib-hikvision-ultimate@1.0.60
+-- node-red-contrib-influxdb@0.6.1
+-- node-red-contrib-telegrambot@11.2.3
+-- node-red-contrib-unit-converter@0.0.2
+-- node-red-dashboard@3.1.5
+-- node-red-node-email@1.14.0
+-- node-red-node-rbe@0.5.0
`-- node-red-node-tail@0.3.2

**Comment by TotallyInformation** [comment]
I would suggest raising this issue in the redmatic or raspberrymatic forum since the issues seem to be caused by those. It doesn't appear to happen on Node-RED itself.

However, there are several outdated dependencies in this module that could do with being updated (not sure if they are deep or direct dependencies though).

**Comment by dibadodo** [comment]
I think you are right - redmatic use a old version of node-red - maybe that is the main reason 
But it would be nice to know what is the reason that the last version of 10.x is working and the version of 11.x not. 
I will open a issue on redmatic - Thank you for your time

**Comment by jbrown123** [comment]
I am NOT using redmatic. I'm using a standard node red running on an Orange Pi. I haven't tried a direct npm install, but I am seeing failure (log above) using the node red palette manager.

Other packages install correctly using the palettw manager

**Comment by TotallyInformation** [comment]
Anything might change between major versions of node.js. At the very least, you need to do an `npm rebuild` on the userDir folder to recompile any C++ libraries, this is a common issue.

On the OrangePi, please try a direct install as that may give more information. What version of node.js, npm and node-red do you have on the orangepi and what OS version?

**Comment by windkh** [comment]
I released 11.2.4 without the version info. Please check if this works now...
https://github.com/windkh/node-red-contrib-telegrambot/releases/tag/V11.2.4

**Comment by colinl** [comment]
Why didn't you just revert the previous change? Then you would know it would be ok.

**Comment by windkh** [comment]
> Why didn't you just revert the previous change? Then you would know it would be ok.

… well, because with that change the problems started…. I just wanted to have a release that does not cause even more troubles.

**Comment by colinl** [comment]
I thought that 11.2.2 was ok.  Which was the first version that caused problems?

**Comment by windkh** [comment]
11.2.0

**Comment by colinl** [comment]
OK, that was not clear to me as this issue is specifically about 11.2.3
The reason for the problems in this issue are the node-red version in the engines directive.  I can't comment on any other issues with previous versions as I don't know what they are.

**Comment by dibadodo** [comment]
Hi,

I can confirm this. Version 11.2.2 still works, 11.2.3 has the described problems - the new version 11.2.4 works again. 
Great
Many thanks for your effort

I think we can close this call.

Regards

**Comment by dibadodo** [comment]
Sorry, the new package damaged my repository. After installation i have tried to show the installed packages with npm list. I got a lot off error messages like this:
npm list
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

followed from 

+-- node-red-contrib-combine@1.8.1
+-- UNMET DEPENDENCY node-red-contrib-deconz@2.3.3
| +-- UNMET DEPENDENCY @node-red/util@2.1.1
| | +-- UNMET DEPENDENCY fs-extra@10.0.0
| | | +-- UNMET DEPENDENCY graceful-fs@4.2.8
| | | +-- UNMET DEPENDENCY jsonfile@6.1.0
| | | | +-- UNMET DEPENDENCY graceful-fs@4.2.8
| | | | `-- UNMET DEPENDENCY universalify@2.0.0
| | | `-- UNMET DEPENDENCY universalify@2.0.0
| | +-- UNMET DEPENDENCY i18next@21.3.1
| | | `-- UNMET DEPENDENCY @babel/runtime@7.15.4
| | |   `-- UNMET DEPENDENCY regenerator-runtime@0.13.9
| | +-- UNMET DEPENDENCY json-stringify-safe@5.0.1
| | +-- UNMET DEPENDENCY jsonata@1.8.5

and then:
npm ERR! missing: node-red-contrib-deconz@2.3.3, required by node-red-project@0.0.1
npm ERR! missing: node-red-contrib-hikvision-ultimate@1.0.60, required by node-red-project@0.0.1
npm ERR! missing: node-red-contrib-telegrambot-home@0.7.0, required by node-red-project@0.0.1
npm ERR! missing: node-red-dashboard@3.1.5, required by node-red-project@0.0.1
npm ERR! missing: node-red-node-email@1.14.0, required by node-red-project@0.0.1
npm ERR! missing: node-red-node-tail@0.3.2, required by node-red-project@0.0.1
npm ERR! missing: node-red-contrib-telegrambot@~11.2.2, required by node-red-project@0.0.1
npm ERR! invalid: xmlbuilder@0.4.2 /usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-xmlrpc/node_modules/xmlbuilder
npm ERR! missing: ws@8.2.3, required by node-red-contrib-deconz@2.3.3
npm ERR! missing: @node-red/util@2.1.1, required by node-red-contrib-deconz@2.3.3
npm ERR! missing: compare-versions@3.6.0, required by node-red-contrib-deconz@2.3.3
npm ERR! missing: dot-prop@6.0.1, required by node-red-contrib-deconz@2.3.3
npm ERR! missing: got@11.8.2, required by node-red-contrib-deconz@2.3.3
npm ERR! missing: set-interval-async@2.0.3, required by node-red-contrib-deconz@2.3.3
npm ERR! peer dep missing: jquery@1.9.1 - 3, required by multiple-select@1.5.2
npm ERR! extraneous: ws@8.2.3 /usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws
npm ERR! missing: fs-extra@10.0.0, required by @node-red/util@2.1.1


Uninstalling of the new Package fails with this message:

 npm uninstall node-red-contrib-telegrambot
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

added 4 packages from 13 contributors, removed 126 packages, updated 279 packages and audited 473 packages in 212.023s

39 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

**Comment by colinl** [comment]
@dibadodo what do these commands show
`node -v`
`npm -v`

**Comment by dibadodo** [comment]
node -v
v12.22.7

npm -v
6.14.15

**Comment by colinl** [comment]
What does this command give?
`npm install`

**Comment by jbrown123** [comment]
I'm still getting the same exact same error via Node-Red palette manager with 11.2.4 as with 11.2.3. Same log entries as well.

```
2022-02-14T21:15:05.212Z Install : node-red-contrib-telegrambot 11.2.4

2022-02-14T21:15:04.305Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-telegrambot@11.2.4
2022-02-14T21:15:40.346Z [err] npm
2022-02-14T21:15:40.347Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2022-02-14T21:16:09.280Z [out] + node-red-contrib-telegrambot@11.2.4
2022-02-14T21:16:09.280Z [out] updated 1 package in 59.944s
2022-02-14T21:16:09.366Z rc=0
```

Here's my environment
```
Node Red 
v1.1.3

node -v
v12.20.1

npm -v
6.14.10

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

uname -r
3.4.113-sun8i

cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=orangepione
BOARD_NAME="Orange Pi One"
BOARDFAMILY=sun8i
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=76ac54aa
VERSION=5.90
LINUXFAMILY=sun8i
BRANCH=default
ARCH=arm
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm
KERNEL_IMAGE_TYPE=zImage
```

**Comment by colinl** [comment]
@jbrown123 there are no errors there.  It says it has installed version 11.2.4
```
2022-02-14T21:16:09.280Z [out] + node-red-contrib-telegrambot@11.2.4
2022-02-14T21:16:09.280Z [out] updated 1 package in 59.944s
```

**Comment by windkh** [comment]
@jbrown123 what happens after you restart node-red?

**Comment by dibadodo** [comment]
@colinl 
 
npm install
npm WARN multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

audited 478 packages in 18.17s

57 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
^C
┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

**Comment by jbrown123** [comment]
The palette manager gives an error and says it did NOT install.
![image](https://user-images.githubusercontent.com/636969/153948825-5d69ed8b-b519-4fa9-8e12-13c2dc3ae474.png)

After install, telegrambot does not appear in the nodes list
![image](https://user-images.githubusercontent.com/636969/153948296-08cc6f86-7e93-4abc-a490-b8461c47491d.png)

It still shows up in the list of available packages to be installed.
![image](https://user-images.githubusercontent.com/636969/153948319-2d2929da-ef96-4368-a6ab-f131251850a9.png)

It does, however, show up as an installed package when you do an `npm list` in the .node-red folder
```
~/.node-red$ npm list --depth=0
node-red-project@0.0.1 /home/james/.node-red
├── node-red-contrib-arp@0.0.2
├── node-red-contrib-bigtimer@2.7.5
├── node-red-contrib-castv2@4.1.2
├── node-red-contrib-config@1.2.1
├── node-red-contrib-debounce@0.0.2
├── node-red-contrib-fs-ops@1.6.0
├── node-red-contrib-functionx@1.0.2
├── node-red-contrib-light-scheduler@0.0.17
├── node-red-contrib-npm@1.0.2
├── node-red-contrib-persistent-fsm@1.1.0
├── node-red-contrib-play-audio@2.5.0
├── node-red-contrib-telegrambot@11.2.4        <======================
├── node-red-contrib-time-range-switch@1.0.1
├── node-red-contrib-tplink@1.0.0
├── node-red-contrib-ui-led@0.4.9
├── node-red-dashboard@2.29.0
├── node-red-node-email@1.12.1
├── node-red-node-google@0.2.2
├── node-red-node-pi-gpio@1.2.3
├── node-red-node-ping@0.3.1
├── node-red-node-random@0.4.0
├── node-red-node-rbe@0.5.0
├── node-red-node-serialport@0.14.0
├── node-red-node-smooth@0.1.2
└── node-red-node-tail@0.3.1
```

**Comment by windkh** [comment]
This is realy weird

**Comment by jbrown123** [comment]
> @jbrown123 what happens after you restart node-red?

Restarting node-red causes telegram to appear in the list (as expected, since it was listed as an installed module).
![image](https://user-images.githubusercontent.com/636969/153949633-739d80fc-9d42-4cf2-81d7-1f971419bafa.png)

I don't know if you want to keep this here, or start a new issue of "doesn't report that it installed correctly via palette manager".

**Comment by windkh** [comment]
Well I do not have any idea what is going on here nor do I see anything I could do about it…

**Comment by jbrown123** [comment]
Clearly something is unhappy in the palette manager. Does it no do this when you attempt to install via the palette manager?

**Comment by colinl** [comment]
What did you see when you clicked View Log in the popup error message?

**Comment by jbrown123** [comment]
Exactly what I posted previously in https://github.com/windkh/node-red-contrib-telegrambot/issues/235#issuecomment-1039569605

```
2022-02-14T21:15:05.212Z Install : node-red-contrib-telegrambot 11.2.4

2022-02-14T21:15:04.305Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-telegrambot@11.2.4
2022-02-14T21:15:40.346Z [err] npm
2022-02-14T21:15:40.347Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2022-02-14T21:16:09.280Z [out] + node-red-contrib-telegrambot@11.2.4
2022-02-14T21:16:09.280Z [out] updated 1 package in 59.944s
2022-02-14T21:16:09.366Z rc=0
```

**Comment by colinl** [comment]
So apart from the popup (which I don't get) all is well?
If you clear the browser cache (via the browser menus) and refresh the page, does it still not show up as installed in the palette manager?

**Comment by jbrown123** [comment]
Unfortunately I've restarted node-red now and it does show in the palette after restart (as shown above).

I've never had this problem before with any other modules (as you can see from above, I  have several installed).

If it's useful, I can uninstall the module, restart node-red and repeat the process. I don't know if I will get the error again. Presumably I would.

**Comment by colinl** [comment]
If you installed via npm and then tried to install via the palette manager, without re-starting node-red first then that could  have confused it temporarily.  You must restart node-red after changing the modules behind its back before doing anything else.
Yes, you could try removing it and then re-installing via the palette manager again.
Why are you using an ancient version of node-red?

**Comment by jbrown123** [comment]
> If you installed via npm and then tried to install via the palette manager,

I have ONLY attempted install via NR palette manager. It clearly installed 11.2.4 even though it said it failed.

> Why are you using an ancient version of node-red?

I installed a couple of years ago and just haven't updated NR. The "if it ain't broke don't fix it" philosophy.

**Comment by jbrown123** [comment]
@colinl FYI: I'm upgrading NR to the latest version right now.

**Comment by colinl** [comment]
Perhaps it was still confused because of the previous messing about.

**Comment by jbrown123** [comment]
@colinl ... previous message about ... what?

That it failed previously with 11.2.3?

**Comment by colinl** [comment]
Yes.  The node was installed but not usable. It may have been a hangover from that.

**Comment by colinl** [comment]
Very odd.  What do you see if, in the .node-red folder, you run
`npm install`

**Comment by colinl** [comment]
@dibadodo 
```
│ npm update check failed │
│ Try running with sudo or get access │
│ to the local update config store via │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
```

That suggests you have some files with root permissions in your home folder.  The most common cause of that is using sudo when installing nodes locally.
Did you try running the chown command to fix that?

**Comment by colinl** [comment]
@dibadodo I see you are running node red as root.  Is that normal on redmatic?
```
│ npm update check failed │
│ Try running with sudo or get access │
│ to the local update config store via │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
```
That suggests that the user who ran that command did not have full permissions to all the files there, which is odd, since presumably you are logged in as root doing this.

**Comment by dibadodo** [comment]
@colinl the system seems to be working as expected 
the behavior of clie output has changed since install of 11.4.2 
I thin the Frame with hint npm update check failed was not seen before. The output of npm list was before like this:
── node-red-contrib-arp@0.0.2
├── node-red-contrib-bigtimer@2.7.5
├── node-red-contrib-castv2@4.1.2
├── node-red-contrib-config@1.2.1
├── node-red-contrib-debounce@0.0.2
├── node-red-contrib-fs-ops@1.6.0
├── node-red-contrib-functionx@1.0.2
├── node-red-contrib-light-scheduler@0.0.17
├── node-red-contrib-npm@1.0.2

than output was this:

+-- node-red-contrib-combine@1.8.1
+-- UNMET DEPENDENCY node-red-contrib-deconz@2.3.3
| +-- UNMET DEPENDENCY @node-red/util@2.1.1
| | +-- UNMET DEPENDENCY fs-extra@10.0.0
| | | +-- UNMET DEPENDENCY graceful-fs@4.2.8
| | | +-- UNMET DEPENDENCY jsonfile@6.1.0
| | | | +-- UNMET DEPENDENCY graceful-fs@4.2.8
| | | | -- UNMET DEPENDENCY universalify@2.0.0 | | | -- UNMET DEPENDENCY universalify@2.0.0
| | +-- UNMET DEPENDENCY i18next@21.3.1
| | | -- UNMET DEPENDENCY @babel/runtime@7.15.4 | | | -- UNMET DEPENDENCY regenerator-runtime@0.13.9
| | +-- UNMET DEPENDENCY json-stringify-safe@5.0.1
| | +-- UNMET DEPENDENCY jsonata@1.8.5

after some new install, npm found and so on it shows now again like this:

root@homematic-raspi:~# source /usr/local/addons/redmatic/home/.profile
root@homematic-raspi:~# cd /usr/local/addons/redmatic/var
root@homematic-raspi:/usr/local/addons/redmatic/var# npm list
node-red-project@0.0.1 /usr/local/addons/redmatic/var
+-- node-red-contrib-ccu@3.4.2
+-- node-red-contrib-combine@1.8.1
+-- node-red-contrib-deconz@2.3.3
+-- node-red-contrib-hikvision-ultimate@1.0.60
+-- node-red-contrib-influxdb@0.6.1
+-- node-red-contrib-telegrambot@10.4.1
+-- node-red-contrib-unit-converter@0.0.2
+-- node-red-dashboard@3.1.5
+-- node-red-node-email@1.14.0
+-- node-red-node-rbe@0.5.0
`-- node-red-node-tail@0.3.2

but still with old version of 10.4.1

**Comment by windkh** [comment]
As this is very spooky I have another theory.
Between version 10.x and 11.x I changed a dependency for socks5 support.
However the package.lock was not updated. 
maybe that messed things up since then?

**Comment by TotallyInformation** [comment]
If in doubt, delete the lock file. I do that regularly as I've had so many issues with it in the past. It should have no impact on Node-RED installations.

**Comment by colinl** [comment]
Should you even have a lock file in a contrib node?  If you need specific versions of dependencies then put it in the dependencies in package.json

**Comment by TotallyInformation** [comment]
npm manages that itself Colin. You don't get a lot of choice. It doesn't get published to npm I don't believe though. But I think that npm may create one when you install.  Never been too sure to be honest. If anything funny happens, the lock file is the first thing I delete.

**Comment by colinl** [comment]
Well my nodes don't have a lock file in the node's github repo (eg https://github.com/colinl/node-red-contrib-pid). But you are right in that it doesn't get published to npm anyway (or at least it doesn't get installed), I checked with the telegrambot node and it is not in the installed files.
Perhaps it influences which versions of the dependencies get loaded though, I don't know.

**Comment by dibadodo** [comment]
@windkh  Maybe, normaly i don't look on the cli - when the upgrade work as expected and all other is working to -  normal i start updates only on gui
