### ISSUE TITLE
[FR:] sendDice possible?

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#238]
did anybody else miss this method ?
😄 

https://core.telegram.org/bots/api#senddice

![image](https://user-images.githubusercontent.com/5937811/155395904-2860d4d6-4bfa-4056-b8db-183c5af01cb1.png)

**Comment by windkh** [comment]
I can add it

**Comment by ozett** [comment]
Great. but no hurry... its only for playing with it..
👍

**Comment by windkh** [comment]
11.3.0 supports it: see senddice.json example "roll the dice".
Have fun.
