### ISSUE TITLE
how to send video?

### ISSUE THREAD

**Issue by kzhebenev** [windkh/node-red-contrib-telegrambot#24]
hi, i try to sent video from "motion" on motion detection event.
it's work ok with photo, but it's don't work with video :-(
i create node-red function:

var movie = msg.payload.filename;
msg.payload.chatId=83134571;
msg.payload.type="video";
msg.payload.caption=">>";
msg.payload.content=movie;
return msg;

msg.payload.content is - "/tmp/cam/10-20170809010523.avi"

next point  in flow is "telegram sender". i receive  caption ">>" in telegram, but do not receive video file. 

if i try to sent photo (type=photo) it's work OK

help me please

**Comment by windkh** [comment]
How large is the file?

**Comment by kzhebenev** [comment]
about 1-2mb

**Comment by windkh** [comment]
I will try to reproduce this...

**Comment by kzhebenev** [comment]
with help of some magic i'l find way to sent video on iphone/ipad, but it's steel don't work on mac. :(
i receive the video message on ios, but it's don't want to play  :(
on mac i receive message, but without any content

**Comment by windkh** [comment]
Maybe only some formats are supported like on blackberry:
https://core.telegram.org/blackberry/chat-media-send

**Comment by windkh** [comment]
I tried to send a avi file and received a black preview. Then I sent a video from my iphone to the bot and let it save it to a local folder using the receiver node. Obviously the telegram client of the iphone transcoded the video before uploading to the server to a mp4 with a height of 848 and a width of 464.

I asume that not all formats are supported. This means that you have to convert your files to a usable format before sending. Unfortunately I can't tell you which format is the right one. I'll try to find more information about that.

**Comment by windkh** [comment]
See also
https://stackoverflow.com/questions/38702981/which-video-format-is-right-for-sendvideo-method-in-telegram-bot-api

**Comment by kzhebenev** [comment]
thanks, it's works!
