### ISSUE TITLE
I miss the "disable_notification" option

### ISSUE THREAD

**Issue by gerardovf** [windkh/node-red-contrib-telegrambot#240]
I'm using my bot with the "mute notifications" enabled because of the many messages I'm sending.
It would be nice to have the "mute notifications" disabled and to be able to use the Telegram option "mute notifications" so that only a few (the important ones) messages would require my immediate attention.

    var opts = {
        //parse_mode: 'Markdown'
        parse_mode: 'html',
        disable_notification: true
    };

**Comment by windkh** [comment]
@gerardovf sorry for delay.

You can set the disable_notification in the  options of a message just as you mentioned it above. So why do you "miss"  this option?

**Comment by gerardovf** [comment]
I'm sorry. My bad.
I was thinking that "disable notifications" had to do with whole "notifications". But not just "sound" (do not disturb) notifications.
After reading the API and checking again, it works 'as designed'

Thanks for your good work
