### ISSUE TITLE
can't run on Node-Red Version V2.2.2

### ISSUE THREAD

**Issue by KaiJ17** [windkh/node-red-contrib-telegrambot#241]
I can't seem to run the telegram Bot Node on Node-Red V2.2.2

**Comment by windkh** [comment]
@KaiJ17 could you please provide some more details?

**Comment by KaiJ17** [comment]
Hi @windkh ,

after downloading telegram palette and dragging it into the workspace, i get this error upon deploying
![image](https://user-images.githubusercontent.com/102976255/164198828-e8c44628-e00f-4546-b452-ec20f415309e.png)

I also get this when looking at the palettes
![image](https://user-images.githubusercontent.com/102976255/164198786-5aa4b653-70e8-4874-bd0e-9addebdc537d.png)

I am also asking questions on the node-red forum [here](https://discourse.nodered.org/t/why-doesnt-telegram-node-work-on-node-red-version-v2-2-2/61473/4)

**Comment by windkh** [comment]
any news?

**Comment by windkh** [comment]
Are you running on a x86 or x64 platform or arm?

**Comment by windkh** [comment]
closed due to no response
