### ISSUE TITLE
Update to 6.0.0 API

### ISSUE THREAD

**Issue by boroda4436** [windkh/node-red-contrib-telegrambot#242]
On 16 April 2022 was released new API version. Do we have any plans to support it?

https://core.telegram.org/bots/api#april-16-2022

**Comment by windkh** [comment]
@boroda4436 maybe in a few weeks.... I need to have a look at the new features to check if they are useful.
Do you wait for a specific feature?

**Comment by demon-goxa** [comment]
Hello!
I'm waiting for web_app feature

**Comment by windkh** [comment]
Version 11.8.0 should contain the desired changes
