### ISSUE TITLE
get same error

### ISSUE THREAD

**Issue by kzhebenev** [windkh/node-red-contrib-telegrambot#25]
hi, i get next error once per second,

Aug 11 00:51:23 openHABianPi Node-RED[454]: { Error: ETELEGRAM: 409 Conflict: terminated by other long poll or webhook
Aug 11 00:51:23 openHABianPi Node-RED[454]: at request.then.resp (/root/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:181:15)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at tryCatcher (/root/.node-red/node_modules/bluebird/js/release/util.js:16:23)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Promise._settlePromiseFromHandler (/root/.node-red/node_modules/bluebird/js/release/promise.js:512:31)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Promise._settlePromise (/root/.node-red/node_modules/bluebird/js/release/promise.js:569:18)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Promise._settlePromise0 (/root/.node-red/node_modules/bluebird/js/release/promise.js:614:10)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Promise._settlePromises (/root/.node-red/node_modules/bluebird/js/release/promise.js:693:18)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Async._drainQueue (/root/.node-red/node_modules/bluebird/js/release/async.js:133:16)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Async._drainQueues (/root/.node-red/node_modules/bluebird/js/release/async.js:143:10)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at Immediate.Async.drainQueues (/root/.node-red/node_modules/bluebird/js/release/async.js:17:14)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at runCallback (timers.js:672:20)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at tryOnImmediate (timers.js:645:5)
Aug 11 00:51:23 openHABianPi Node-RED[454]: at processImmediate [as _immediateCallback] (timers.js:617:5)
Aug 11 00:51:23 openHABianPi Node-RED[454]: code: 'ETELEGRAM',
Aug 11 00:51:23 openHABianPi Node-RED[454]: response:
Aug 11 00:51:23 openHABianPi Node-RED[454]: IncomingMessage {
Aug 11 00:51:23 openHABianPi Node-RED[454]: _readableState:
Aug 11 00:51:23 openHABianPi Node-RED[454]: ReadableState {
Aug 11 00:51:23 openHABianPi Node-RED[454]: objectMode: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: highWaterMark: 16384,
Aug 11 00:51:23 openHABianPi Node-RED[454]: buffer: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: length: 0,
Aug 11 00:51:23 openHABianPi Node-RED[454]: pipes: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: pipesCount: 0,
Aug 11 00:51:23 openHABianPi Node-RED[454]: flowing: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: ended: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: endEmitted: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: reading: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: sync: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: needReadable: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: emittedReadable: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: readableListening: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: resumeScheduled: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: defaultEncoding: 'utf8',
Aug 11 00:51:23 openHABianPi Node-RED[454]: ranOut: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: awaitDrain: 0,
Aug 11 00:51:23 openHABianPi Node-RED[454]: readingMore: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: decoder: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: encoding: null },
Aug 11 00:51:23 openHABianPi Node-RED[454]: readable: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events:
Aug 11 00:51:23 openHABianPi Node-RED[454]: { end: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: close: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: data: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: error: [Function] },
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 4,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: socket:
Aug 11 00:51:23 openHABianPi Node-RED[454]: TLSSocket {
Aug 11 00:51:23 openHABianPi Node-RED[454]: _tlsOptions: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _secureEstablished: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _securePending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _newSessionPending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _controlReleased: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _SNICallback: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: servername: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: npnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: alpnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorizationError: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: encrypted: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 9,
Aug 11 00:51:23 openHABianPi Node-RED[454]: connecting: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _hadError: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _handle: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _parent: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _host: 'api.telegram.org',
Aug 11 00:51:23 openHABianPi Node-RED[454]: _readableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: readable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _writableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: writable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: allowHalfOpen: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: destroyed: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _bytesDispatched: 13966,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _sockname: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingData: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingEncoding: '',
Aug 11 00:51:23 openHABianPi Node-RED[454]: server: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _server: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: ssl: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _requestCert: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rejectUnauthorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: parser: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _httpMessage: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: read: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _consuming: true },
Aug 11 00:51:23 openHABianPi Node-RED[454]: connection:
Aug 11 00:51:23 openHABianPi Node-RED[454]: TLSSocket {
Aug 11 00:51:23 openHABianPi Node-RED[454]: _tlsOptions: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _secureEstablished: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _securePending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _newSessionPending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _controlReleased: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _SNICallback: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: servername: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: npnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: alpnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorizationError: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: encrypted: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 9,
Aug 11 00:51:23 openHABianPi Node-RED[454]: connecting: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _hadError: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _handle: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _parent: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _host: 'api.telegram.org',
Aug 11 00:51:23 openHABianPi Node-RED[454]: _readableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: readable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _writableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: writable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: allowHalfOpen: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: destroyed: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _bytesDispatched: 13966,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _sockname: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingData: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingEncoding: '',
Aug 11 00:51:23 openHABianPi Node-RED[454]: server: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _server: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: ssl: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _requestCert: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rejectUnauthorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: parser: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _httpMessage: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: read: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _consuming: true },
Aug 11 00:51:23 openHABianPi Node-RED[454]: httpVersionMajor: 1,
Aug 11 00:51:23 openHABianPi Node-RED[454]: httpVersionMinor: 1,
Aug 11 00:51:23 openHABianPi Node-RED[454]: httpVersion: '1.1',
Aug 11 00:51:23 openHABianPi Node-RED[454]: complete: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: headers:
Aug 11 00:51:23 openHABianPi Node-RED[454]: { server: 'nginx/1.10.1',
Aug 11 00:51:23 openHABianPi Node-RED[454]: date: 'Thu, 10 Aug 2017 21:52:09 GMT',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'content-type': 'application/json',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'content-length': '96',
Aug 11 00:51:23 openHABianPi Node-RED[454]: connection: 'keep-alive',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'access-control-allow-origin': '*',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'access-control-expose-headers': 'Content-Length,Content-Type,Date,Server,Connection' },
Aug 11 00:51:23 openHABianPi Node-RED[454]: rawHeaders:
Aug 11 00:51:23 openHABianPi Node-RED[454]: [ 'Server',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'nginx/1.10.1',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Date',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Thu, 10 Aug 2017 21:52:09 GMT',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Content-Type',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'application/json',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Content-Length',
Aug 11 00:51:23 openHABianPi Node-RED[454]: '96',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Connection',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'keep-alive',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Access-Control-Allow-Origin',
Aug 11 00:51:23 openHABianPi Node-RED[454]: '*',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Access-Control-Expose-Headers',
Aug 11 00:51:23 openHABianPi Node-RED[454]: 'Content-Length,Content-Type,Date,Server,Connection' ],
Aug 11 00:51:23 openHABianPi Node-RED[454]: trailers: {},
Aug 11 00:51:23 openHABianPi Node-RED[454]: rawTrailers: [],
Aug 11 00:51:23 openHABianPi Node-RED[454]: upgrade: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: url: '',
Aug 11 00:51:23 openHABianPi Node-RED[454]: method: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: statusCode: 409,
Aug 11 00:51:23 openHABianPi Node-RED[454]: statusMessage: 'Conflict',
Aug 11 00:51:23 openHABianPi Node-RED[454]: client:
Aug 11 00:51:23 openHABianPi Node-RED[454]: TLSSocket {
Aug 11 00:51:23 openHABianPi Node-RED[454]: _tlsOptions: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _secureEstablished: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _securePending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _newSessionPending: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _controlReleased: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _SNICallback: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: servername: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: npnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: alpnProtocol: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: authorizationError: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: encrypted: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 9,
Aug 11 00:51:23 openHABianPi Node-RED[454]: connecting: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _hadError: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _handle: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _parent: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _host: 'api.telegram.org',
Aug 11 00:51:23 openHABianPi Node-RED[454]: _readableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: readable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _writableState: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: writable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: allowHalfOpen: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: destroyed: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _bytesDispatched: 13966,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _sockname: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingData: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _pendingEncoding: '',
Aug 11 00:51:23 openHABianPi Node-RED[454]: server: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _server: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: ssl: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _requestCert: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rejectUnauthorized: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: parser: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _httpMessage: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: read: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _consuming: true },
Aug 11 00:51:23 openHABianPi Node-RED[454]: _consuming: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _dumped: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: req:
Aug 11 00:51:23 openHABianPi Node-RED[454]: ClientRequest {
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 5,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: output: [],
Aug 11 00:51:23 openHABianPi Node-RED[454]: outputEncodings: [],
Aug 11 00:51:23 openHABianPi Node-RED[454]: outputCallbacks: [],
Aug 11 00:51:23 openHABianPi Node-RED[454]: outputSize: 0,
Aug 11 00:51:23 openHABianPi Node-RED[454]: writable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _last: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: upgrading: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: chunkedEncoding: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: shouldKeepAlive: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: useChunkedEncodingByDefault: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: sendDate: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _removedHeader: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _contentLength: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _hasBody: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _trailer: '',
Aug 11 00:51:23 openHABianPi Node-RED[454]: finished: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _headerSent: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: socket: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: connection: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _header: 'POST /bot415471672:AAFMhnDFKqWWd6-hR4Kz7mSHhsumMVCiGQQ/getUpdates HTTP/1.1\r\nhost: api.telegram.org\r\ncontent-type: application/x-www-form-urlencoded\r\ncontent-length: 19\r\nConnection: keep-alive\r\n\r\n',
Aug 11 00:51:23 openHABianPi Node-RED[454]: _headers: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _headerNames: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _onPendingData: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: agent: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: socketPath: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: timeout: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: method: 'POST',
Aug 11 00:51:23 openHABianPi Node-RED[454]: path: '/bot415471672:AAFMhnDFKqWWd6-hR4Kz7mSHhsumMVCiGQQ/getUpdates',
Aug 11 00:51:23 openHABianPi Node-RED[454]: _ended: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: res: [Circular],
Aug 11 00:51:23 openHABianPi Node-RED[454]: aborted: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: timeoutCb: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: upgradeOrConnect: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: parser: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: maxHeadersCount: null },
Aug 11 00:51:23 openHABianPi Node-RED[454]: request:
Aug 11 00:51:23 openHABianPi Node-RED[454]: Request {
Aug 11 00:51:23 openHABianPi Node-RED[454]: domain: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _events: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _eventsCount: 5,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _maxListeners: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: method: 'POST',
Aug 11 00:51:23 openHABianPi Node-RED[454]: simple: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: resolveWithFullResponse: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: forever: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: readable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: writable: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: explicitMethod: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _qs: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _auth: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _oauth: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _multipart: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _redirect: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _tunnel: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rp_resolve: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rp_reject: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rp_promise: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rp_callbackOrig: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: callback: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _rp_options: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: headers: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: setHeader: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: hasHeader: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: getHeader: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: removeHeader: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: localAddress: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: pool: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: dests: [],
Aug 11 00:51:23 openHABianPi Node-RED[454]: __isRequestRequest: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _callback: [Function: RP$callback],
Aug 11 00:51:23 openHABianPi Node-RED[454]: uri: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: proxy: null,
Aug 11 00:51:23 openHABianPi Node-RED[454]: tunnel: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: setHost: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: originalCookieHeader: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _disableCookies: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _jar: undefined,
Aug 11 00:51:23 openHABianPi Node-RED[454]: port: 443,
Aug 11 00:51:23 openHABianPi Node-RED[454]: host: 'api.telegram.org',
Aug 11 00:51:23 openHABianPi Node-RED[454]: body: 'timeout=10&offset=0',
Aug 11 00:51:23 openHABianPi Node-RED[454]: path: '/bot415471672:AAFMhnDFKqWWd6-hR4Kz7mSHhsumMVCiGQQ/getUpdates',
Aug 11 00:51:23 openHABianPi Node-RED[454]: httpModule: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: agentClass: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: agentOptions: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: agent: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _started: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: href: 'https://api.telegram.org/bot415471672:AAFMhnDFKqWWd6-hR4Kz7mSHhsumMVCiGQQ/getUpdates',
Aug 11 00:51:23 openHABianPi Node-RED[454]: req: [Object],
Aug 11 00:51:23 openHABianPi Node-RED[454]: ntick: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: response: [Circular],
Aug 11 00:51:23 openHABianPi Node-RED[454]: originalHost: 'api.telegram.org',
Aug 11 00:51:23 openHABianPi Node-RED[454]: originalHostHeaderName: 'host',
Aug 11 00:51:23 openHABianPi Node-RED[454]: responseContent: [Circular],
Aug 11 00:51:23 openHABianPi Node-RED[454]: _destdata: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _ended: true,
Aug 11 00:51:23 openHABianPi Node-RED[454]: _callbackCalled: true },
Aug 11 00:51:23 openHABianPi Node-RED[454]: toJSON: [Function: responseToJSON],
Aug 11 00:51:23 openHABianPi Node-RED[454]: caseless: Caseless { dict: [Object] },
Aug 11 00:51:23 openHABianPi Node-RED[454]: read: [Function],
Aug 11 00:51:23 openHABianPi Node-RED[454]: body:
Aug 11 00:51:23 openHABianPi Node-RED[454]: { ok: false,
Aug 11 00:51:23 openHABianPi Node-RED[454]: error_code: 409,
Aug 11 00:51:23 openHABianPi Node-RED[454]: description: 'Conflict: terminated by other long poll or webhook' } } }
^C

**Comment by windkh** [comment]
This happens when you have two configuration nodes using the same bot-token.
Telegram allows only one connection with the same token.
