### ISSUE TITLE
Not all telegram messages are received

### ISSUE THREAD

**Issue by nygma2004** [windkh/node-red-contrib-telegrambot#251]
This issue is happening for a while for me, and never managed to get to the bottom of it. I am using Node-Red 2.1.3 and telegrambot 10.0.9.

The issue simply is that some of the messages I send from the phone or the Telegram desktop app never arrive to the Node-Red:
![image](https://user-images.githubusercontent.com/16757620/173686114-482df183-da8f-4a0a-80af-1ce5900c2545.png)
I have a telegram receiver, connected to a debug node and I only see a single "test" message to which the flow also responded. But the other 4 messages are lost and never arrives.
And it is a hit and miss. Sometimes, the server responds to the first message, sometimes the second, or third.

The bot node is set up for Polling with Poll Interval of 300.

**Comment by windkh** [comment]
Can you change the pollintervall to 1000 and let me know if something changed?
Can you turn on verbose logging?

**Comment by nygma2004** [comment]
I changed the interval to 1000 and it started working, getting all my messages. And after about 5 message it stopped again and skipped like 8-9 messages before getting the next one.
Verbose logging should be turned on the bot configuration? And where do I see the log generated?

**Comment by windkh** [comment]
In the node-red console output

**Comment by windkh** [comment]
Can you please make sure that your token is only used in one configuration node and not in many.

**Comment by nygma2004** [comment]
Yes, Yes! Most probably because of import, export I have the configuration node duplicated 3 times. I deleted the extra configurations and reassigned the single configuration to all the telegram nodes and it seems to be working now.

I reset the polling period back to the default 300 and so far everything is looking good. 

I will keep testing for a few days but for now I think the issue is resolved. I never though checking the configuration nodes.

**Comment by windkh** [comment]
Ok nice
