### ISSUE TITLE
Missing msg.payload.sentMessageId

### ISSUE THREAD

**Issue by chrismox** [windkh/node-red-contrib-telegrambot#256]
At some point in the last week (having not changed any of my Node-RED flows), I noticed some odd behaviour with my bot.

I have traced the issue to a node where I am trying to track a message ID with the following:

context.global.keyboard.messageId = msg.payload.sentMessageId;

Having debugged the Telegram receiver node output, msg.payload.sentMessageId isn't being sent.

Either I've found an issue or something has gone wrong with my bot.

**Comment by windkh** [comment]
So what was the output object then?

**Comment by chrismox** [comment]
{"payload":{"chatId":xxxxxxxxxx,"messageId":538,"type":"message","content":"hw","date":1656702633},"originalMessage":{"message_id":538,"from":{"id":xxxxxxxxxx,"is_bot":false,"first_name":"Chris","last_name":"xxxxx","language_code":"en"},"chat":{"id":xxxxxxxxxx,"first_name":"Chris","last_name":"xxxxx","type":"private"},"date":1656702633,"text":"hw"},"_msgid":"xxxxxxxxxxxxxxxx"}

**Comment by chrismox** [comment]
(I've removed personal info)

**Comment by windkh** [comment]
And that output was created by the sender node?

**Comment by chrismox** [comment]
No, the receiver mode.

**Comment by windkh** [comment]
Well the receiver does not have a sentMessageId property as it did not send but receive a message. Only the sender can tell you what messageId was sent

**Comment by chrismox** [comment]
Hmmm, odd. You obviously know this better than anyone, yet my flows worked fine last week and now they don't.

I'll investigate futher, but thanks a lot for your help.

**Comment by chrismox** [comment]
Sorry for taking your time before I had understood this correctly. 

My function node contains the following:
context.global.keyboard.messageId = msg.payload.sentMessageId;
return msg;

It is connected to a sender node and that node does indeed output msg.payload.sentMessageId

For some reason, however, the fundtion node returns the error "TypeError: Cannot set property 'messageId' of undefined".

Why this worked before but no longer does is my problem, not an issue for you to spend time on.

Once again, thanks for your help and sorry for taking your time!

**Comment by chrismox** [comment]
For the benfit of anyone else coming across this, I had to change this:

context.global.keyboard.messageId = msg.payload.sentMessageId;

...to this:

context.global.messageId = msg.payload.sentMessageId;

For reasons I can't explain, this has fixed my issue.

**Comment by windkh** [comment]
…. Maybe it would help if you would paste your flow here so that the others can see what you intended to do….

**Comment by chrismox** [comment]
Apologies for the delay. This is an abbreviated selection of the relevant flows.

 `[{"id":"3af6958a49f4cdc1","type":"telegram sender","z":"44b467ab2c9b7681","name":"","bot":"a0d7ae6187ce4595","haserroroutput":false,"outputs":1,"x":190,"y":860,"wires":[[]]},{"id":"549b5431e63e50d3","type":"function","z":"44b467ab2c9b7681","name":"Help?","func":"// This function checks if a help was requested\n// The msg.originalMessage.help flag instructs the other function nodes to process the request or provide help text\n\nmsg.help = false;\n\nif (msg.payload.content===\"help\")\n{\n    msg.help = true;\n    msg.payload.content = msg.payload.content + \"\\r\\n\";\n}\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":350,"y":100,"wires":[["32856f836e1aeebd"]]},{"id":"1a36761e4861af53","type":"switch","z":"44b467ab2c9b7681","name":"A cry for help?","property":"help","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":380,"y":420,"wires":[["7cb5bd3f9a71db1a"],["d80d8fd2c8518f78"]],"outputLabels":["Yes",""]},{"id":"d80d8fd2c8518f78","type":"change","z":"44b467ab2c9b7681","name":"Unknown function","rules":[{"t":"set","p":"payload.content","pt":"msg","to":"Eh?","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":460,"wires":[["7cb5bd3f9a71db1a"]]},{"id":"5ef2ea18151dcf41","type":"telegram receiver","z":"44b467ab2c9b7681","name":"","bot":"a0d7ae6187ce4595","saveDataDir":"","filterCommands":false,"x":150,"y":40,"wires":[["06548b69841227f3"],[]]},{"id":"06548b69841227f3","type":"function","z":"44b467ab2c9b7681","name":"Lower case","func":"msg.payload.content = msg.payload.content.toLowerCase();\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":370,"y":40,"wires":[["549b5431e63e50d3"]]},{"id":"32856f836e1aeebd","type":"function","z":"44b467ab2c9b7681","name":"Hot water","func":"// Handle the help request\nif (msg.help)\n{\n    msg.payload.content = msg.payload.content + \"\\r\\nHW\";  \n    return [null,msg];\n}\n\n// Check if the current message contains this function\nif (msg.payload.content===\"hw\")\n{\n    return [msg,null];\n}\n\n// pass the message to the next node\nelse\n{\n    return [null,msg];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":160,"wires":[["602e9630384a9272"],["93b0cfa4ccfa7bae"]],"outputLabels":["User has access","Insufficient access"]},{"id":"4c90aa411fa5b28c","type":"telegram event","z":"44b467ab2c9b7681","name":"","bot":"a0d7ae6187ce4595","event":"callback_query","autoanswer":false,"x":140,"y":560,"wires":[["fc0c96d85373eded","8fe968f9c56efdd2"]]},{"id":"38667436afaa8f67","type":"link in","z":"44b467ab2c9b7681","name":"Telegram sender","links":["7cb5bd3f9a71db1a","95a88bfc88771841","3e6ea73d29bd1eb4","d2921b75655325e9","476ce65bd4e92c7c","0c322cafd0824a30","268b952dd20b98c0","d88f1def1a86edc5","7e4783b404e52219","1f53e8698ac6ccde","62a3d63ddcf5cab1","4ae3dc6362a8838c","55ed2b7ea3ab2a40","e0c051b34e838382","0fd0e8dacc965a25","6c99c837d944fee1","cee2ebdf33fb555f","0dbf6578b22db0c8"],"x":65,"y":860,"wires":[["3af6958a49f4cdc1"]]},{"id":"7cb5bd3f9a71db1a","type":"link out","z":"44b467ab2c9b7681","name":"Telegram sender","mode":"link","links":["38667436afaa8f67"],"x":555,"y":440,"wires":[]},{"id":"93b0cfa4ccfa7bae","type":"function","z":"44b467ab2c9b7681","name":"Curtains","func":"// Handle the help request\nif (msg.help)\n{\n    msg.payload.content = msg.payload.content + \"\\r\\nCurtains\";  \n    return [null,msg];\n}\n\n// Check if the current message contains this function\nif (msg.payload.content===\"curtains\")\n{\n    return [msg,null];\n}\n\n// pass the message to the next node\nelse\n{\n    return [null,msg];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":220,"wires":[["665fa5759ee627a2"],["09f8301380fd1523"]],"outputLabels":["User has access","Insufficient access"]},{"id":"665fa5759ee627a2","type":"function","z":"44b467ab2c9b7681","name":"Recall variable","func":"msg.status = global.get(\"curtainAutomation\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":560,"y":220,"wires":[["f0e9ef9cf9a4aad5"]]},{"id":"f0e9ef9cf9a4aad5","type":"function","z":"44b467ab2c9b7681","name":"Inline keyboard","func":"var opts = {\n  reply_markup: JSON.stringify({\n    \"inline_keyboard\": [[\n                {\n                    \"text\": \"Auto\",\n                    \"callback_data\": \"curtains_auto\"\n                },\n                {\n                    \"text\": \"Manual\",\n                    \"callback_data\": \"curtains_manual\"\n                }]\n            ]\n  })\n};\n\nmsg.payload.content = \"Curtains are currently \"+msg.status.toLowerCase();\nmsg.payload.options = opts;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":780,"y":220,"wires":[["0f9108a627369678"]]},{"id":"0f9108a627369678","type":"telegram sender","z":"44b467ab2c9b7681","name":"Show inline keyboard","bot":"a0d7ae6187ce4595","haserroroutput":false,"outputs":1,"x":1020,"y":220,"wires":[["f6b8f7df171ea6ef"]]},{"id":"f6b8f7df171ea6ef","type":"function","z":"44b467ab2c9b7681","name":"Store messageId","func":"// Store the sent messageId to be able to edit this reply in the callback query. \ncontext.global.messageId = msg.payload.sentMessageId;\nreturn msg;","outputs":"1","noerr":0,"initialize":"","finalize":"","libs":[],"x":1270,"y":220,"wires":[[]]},{"id":"2e76d9ecab7c8ef9","type":"function","z":"44b467ab2c9b7681","name":"Auto","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Curtains auto\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":550,"y":540,"wires":[["8f9e9441093a38b8","d2921b75655325e9"]]},{"id":"fc0c96d85373eded","type":"function","z":"44b467ab2c9b7681","name":"Curtains callback","func":"if(msg.payload.content === \"curtains_auto\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [msg,null];\n}\n\nif(msg.payload.content === \"curtains_manual\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [null,msg];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":370,"y":560,"wires":[["2e76d9ecab7c8ef9","d2921b75655325e9"],["9feca713816ff9aa","d2921b75655325e9"]]},{"id":"9feca713816ff9aa","type":"function","z":"44b467ab2c9b7681","name":"Manual","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Curtains manual\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":560,"y":580,"wires":[["634155ab45d33ca9","d2921b75655325e9"]]},{"id":"634155ab45d33ca9","type":"link out","z":"44b467ab2c9b7681","name":"Curtains manual","mode":"link","links":["dfc800bf3a17e2f5"],"x":695,"y":580,"wires":[]},{"id":"8f9e9441093a38b8","type":"link out","z":"44b467ab2c9b7681","name":"Curtains auto","mode":"link","links":["0ef320f2e0f9a94a"],"x":695,"y":540,"wires":[]},{"id":"d2921b75655325e9","type":"link out","z":"44b467ab2c9b7681","name":"Telegram sender","mode":"link","links":["38667436afaa8f67"],"x":775,"y":560,"wires":[]},{"id":"09f8301380fd1523","type":"function","z":"44b467ab2c9b7681","name":"Temperatures","func":"// Handle the help request\nif (msg.help)\n{\n    msg.payload.content = msg.payload.content + \"\\r\\nTemps\";  \n    return [null,msg];\n}\n\n// Check if the current message contains this function\nif (msg.payload.content===\"temps\")\n{\n    return [msg,null];\n}\n\n// pass the message to the next node\nelse\n{\n    return [null,msg];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":380,"y":280,"wires":[["021e90cf97e2c207"],["ed2a537e05f41a89"]],"outputLabels":["User has access","Insufficient access"]},{"id":"021e90cf97e2c207","type":"function","z":"44b467ab2c9b7681","name":"Recall variables","func":"msg.lounge = global.get(\"temLounge\");\nmsg.kitchen = global.get(\"temKitchen\");\nmsg.utility = global.get(\"temUtility\");\nmsg.hallway = global.get(\"temHallway\");\nmsg.masterbed = global.get(\"temMasterBed\");\nmsg.ensuite = global.get(\"temEnsuite\");\nmsg.bed2 = global.get(\"temBedroom2\");\nmsg.bed3 = global.get(\"temBedroom3\");\nmsg.bathroom = global.get(\"temBathroom\");\nmsg.rumpus = global.get(\"temRumpus\");\nmsg.garage = global.get(\"temGarage\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":600,"y":280,"wires":[["97de245062e0a0c5"]]},{"id":"97de245062e0a0c5","type":"function","z":"44b467ab2c9b7681","name":"Compile response","func":"var temps = \"Lounge - \"+msg.lounge+\"°C\\r\\n\";\n//temps += \"Kitchen - \"+msg.kitchen+\"°C\\r\\n\";\ntemps += \"Utility room - \"+msg.utility+\"°C\\r\\n\";\n//temps += \"Hallway - \"+msg.hallway+\"°C\\r\\n\";\ntemps += \"Master bedroom - \"+msg.masterbed+\"°C\\r\\n\";\ntemps += \"Ensuite - \"+msg.ensuite+\"°C\\r\\n\";\ntemps += \"Rear bedroom - \"+msg.bed2+\"°C\\r\\n\";\ntemps += \"Front bedroom - \"+msg.bed3+\"°C\\r\\n\";\n//temps += \"Bathroom - \"+msg.bathroom+\"°C\\r\\n\";\ntemps += \"Rumpus room - \"+msg.rumpus+\"°C\\r\\n\";\ntemps += \"Garage - \"+msg.garage+\"°C\\r\\n\";\n\nmsg.payload.content = temps;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":830,"y":280,"wires":[["476ce65bd4e92c7c"]]},{"id":"476ce65bd4e92c7c","type":"link out","z":"44b467ab2c9b7681","name":"Telegram sender","mode":"link","links":["38667436afaa8f67"],"x":985,"y":280,"wires":[]},{"id":"ed2a537e05f41a89","type":"function","z":"44b467ab2c9b7681","name":"Humidities","func":"// Handle the help request\nif (msg.help)\n{\n    msg.payload.content = msg.payload.content + \"\\r\\nHums\";  \n    return [null,msg];\n}\n\n// Check if the current message contains this function\nif (msg.payload.content===\"hums\")\n{\n    return [msg,null];\n}\n\n// pass the message to the next node\nelse\n{\n    return [null,msg];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":370,"y":340,"wires":[["f06032257dce2c98"],["1a36761e4861af53"]],"outputLabels":["User has access","Insufficient access"]},{"id":"f06032257dce2c98","type":"function","z":"44b467ab2c9b7681","name":"Recall variables","func":"msg.lounge = global.get(\"humLounge\");\nmsg.kitchen = global.get(\"humKitchen\");\nmsg.utility = global.get(\"humUtility\");\nmsg.hallway = global.get(\"humHallway\");\nmsg.masterbed = global.get(\"humMasterBed\");\nmsg.ensuite = global.get(\"humEnsuite\");\nmsg.bed2 = global.get(\"humBedroom2\");\nmsg.bed3 = global.get(\"humBedroom3\");\nmsg.bathroom = global.get(\"humBathroom\");\nmsg.rumpus = global.get(\"humRumpus\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":600,"y":340,"wires":[["5a97e08ac46b1c18"]]},{"id":"5a97e08ac46b1c18","type":"function","z":"44b467ab2c9b7681","name":"Compile response","func":"var temps = \"Lounge - \"+msg.lounge+\"%\\r\\n\";\n//temps += \"Kitchen - \"+msg.kitchen+\"%\\r\\n\";\ntemps += \"Utility room - \"+msg.utility+\"%\\r\\n\";\n//temps += \"Hallway - \"+msg.hallway+\"%\\r\\n\";\ntemps += \"Master bedroom - \"+msg.masterbed+\"%\\r\\n\";\ntemps += \"Ensuite - \"+msg.ensuite+\"%\\r\\n\";\ntemps += \"Rear bedroom - \"+msg.bed2+\"%\\r\\n\";\ntemps += \"Front bedroom - \"+msg.bed3+\"%\\r\\n\";\n//temps += \"Bathroom - \"+msg.bathroom+\"%\\r\\n\";\ntemps += \"Rumpus room - \"+msg.rumpus+\"%\\r\\n\";\n\nmsg.payload.content = temps;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":830,"y":340,"wires":[["0c322cafd0824a30"]]},{"id":"0c322cafd0824a30","type":"link out","z":"44b467ab2c9b7681","name":"Telegram sender","mode":"link","links":["38667436afaa8f67"],"x":985,"y":340,"wires":[]},{"id":"9478818391c90378","type":"function","z":"44b467ab2c9b7681","name":"Inline keyboard","func":"var opts = {\n  reply_markup: JSON.stringify({\n    \"inline_keyboard\": [[\n                {\n                    \"text\": \"Auto\",\n                    \"callback_data\": \"hw_auto\"\n                }, \n                {\n                    \"text\": \"Off\",\n                    \"callback_data\": \"hw_off\"\n                },\n                {\n                    \"text\": \"Skip\",\n                    \"callback_data\": \"hw_skip\"\n                },\n                {\n                    \"text\": \"Boost\",\n                    \"callback_data\": \"hw_boost\"\n                }]\n            ]\n  })\n};\n\nmsg.payload.content = \"Hot water is currently \"+msg.status;\nmsg.payload.options = opts;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":780,"y":160,"wires":[["482e91b540f63653"]]},{"id":"602e9630384a9272","type":"function","z":"44b467ab2c9b7681","name":"Recall variable","func":"var hw = global.get(\"HotWater\");\n\nif (hw === \"0\")\n{\n    msg.status = \"off\";\n}\n\nif (hw === \"1\")\n{\n    msg.status = \"auto\";\n}\n\nif (hw === \"2\")\n{\n    msg.status = \"skipping then auto\";\n}\n\nif (hw === \"3\")\n{\n    msg.status = \"boosting then auto\";\n}\n\nif (hw === \"4\")\n{\n    msg.status = \"boost then off\";\n}\n\nif (hw === \"5\")\n{\n    msg.status = \"boost then skip\";\n}\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":560,"y":160,"wires":[["9478818391c90378"]]},{"id":"482e91b540f63653","type":"telegram sender","z":"44b467ab2c9b7681","name":"Show inline keyboard","bot":"a0d7ae6187ce4595","haserroroutput":false,"outputs":1,"x":1020,"y":160,"wires":[["5801d4024195f451"]]},{"id":"6ef045b76d24c421","type":"function","z":"44b467ab2c9b7681","name":"Auto","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Hot water auto\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":570,"y":640,"wires":[["55ed2b7ea3ab2a40"]]},{"id":"8fe968f9c56efdd2","type":"function","z":"44b467ab2c9b7681","name":"Hot water callback","func":"if(msg.payload.content === \"hw_auto\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [msg,null,null,null];\n}\n\nif(msg.payload.content === \"hw_off\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [null,msg,null,null];\n}\n\nif(msg.payload.content === \"hw_skip\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [null,null,msg,null];\n}\n\nif(msg.payload.content === \"hw_boost\")\n{\n    // Hide the inline keyboard and forget the messageId\n    msg.payload.type = 'deleteMessage';\n    msg.payload.content = context.global.messageId\n    context.global.messageId = null;\n    return [null,null,null,msg];\n}","outputs":4,"noerr":0,"initialize":"","finalize":"","libs":[],"x":370,"y":700,"wires":[["6ef045b76d24c421","55ed2b7ea3ab2a40","5a97399bc8b79aab"],["1c63d902ea138fcd","151c5eef97434e1b","55ed2b7ea3ab2a40"],["55ed2b7ea3ab2a40","4473e43a22a60550"],["55ed2b7ea3ab2a40","ea61f37c20b4cd6c"]]},{"id":"ea61f37c20b4cd6c","type":"function","z":"44b467ab2c9b7681","name":"Boost","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Hot water boosting\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":570,"y":760,"wires":[["55ed2b7ea3ab2a40","638d8af2acac5a92"]]},{"id":"55ed2b7ea3ab2a40","type":"link out","z":"44b467ab2c9b7681","name":"Telegram sender","mode":"link","links":["38667436afaa8f67"],"x":775,"y":740,"wires":[]},{"id":"6ea26b3afbcd6730","type":"mqtt out","z":"44b467ab2c9b7681","name":"Boiler/HotWater/cmnd","topic":"Boiler/HotWater/cmnd","qos":"2","retain":"true","broker":"e50ad69.c1a5f28","x":940,"y":660,"wires":[]},{"id":"5a97399bc8b79aab","type":"change","z":"44b467ab2c9b7681","name":"Auto","rules":[{"t":"set","p":"payload","pt":"msg","to":"1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":640,"wires":[["6ea26b3afbcd6730"]]},{"id":"1c63d902ea138fcd","type":"function","z":"44b467ab2c9b7681","name":"Off","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Hot water off\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":570,"y":680,"wires":[["55ed2b7ea3ab2a40"]]},{"id":"151c5eef97434e1b","type":"change","z":"44b467ab2c9b7681","name":"Off","rules":[{"t":"set","p":"payload","pt":"msg","to":"0","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":680,"wires":[["6ea26b3afbcd6730"]]},{"id":"4473e43a22a60550","type":"function","z":"44b467ab2c9b7681","name":"Skip","func":"msg.payload.type = \"message\";\nmsg.payload.content = \"Hot water skipping\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":570,"y":720,"wires":[["55ed2b7ea3ab2a40","908b01851a742458"]]},{"id":"638d8af2acac5a92","type":"link out","z":"44b467ab2c9b7681","name":"HW boost","mode":"link","links":["3b606c19cf587b66"],"x":695,"y":760,"wires":[]},{"id":"908b01851a742458","type":"link out","z":"44b467ab2c9b7681","name":"HW skip","mode":"link","links":["2e6b0cbb00fa99c6"],"x":695,"y":720,"wires":[]},{"id":"5801d4024195f451","type":"function","z":"44b467ab2c9b7681","name":"Store messageId","func":"// Store the sent messageId to be able to edit this reply in the callback query. \ncontext.global.messageId = msg.payload.sentMessageId;\nreturn msg;","outputs":"1","noerr":0,"initialize":"","finalize":"","libs":[],"x":1270,"y":160,"wires":[[]]},{"id":"a0d7ae6187ce4595","type":"telegram bot","botname":"Node-RED","usernames":"","chatids":"5384770153","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false},{"id":"e50ad69.c1a5f28","type":"mqtt-broker","name":"","broker":"192.168.1.222","port":"1883","clientid":"","autoConnect":true,"usetls":false,"protocolVersion":4,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by chrismox** [comment]
Sorry, I'd posted the flows but they contain personal info. I'll try to depersonalise them and add again.
