### ISSUE TITLE
managing members of a group.

### ISSUE THREAD

**Issue by lu4t** [windkh/node-red-contrib-telegrambot#259]
Is it possible to use any of the api methods listed here?: https://core.telegram.org/bots/api#available-methods 

if not, would it be possible to implement this methods? (I believe they're part of the api 6.x release):

https://core.telegram.org/bots/api#approvechatjoinrequest

https://core.telegram.org/bots/api#createchatinvitelink

Thanks!

**Comment by windkh** [comment]
I will put this on my list ... should be doable

**Comment by lu4t** [comment]
just to make sure I get the idea: is it right if I say that ONLY the methods on mentioned on the guides are implemented on node-red-contrib-telegrambot?
Just want to make sure there's no a generic way to parse API methods.
Thanks for the clarification!

**Comment by windkh** [comment]
I just noticed that approveChatJoinRequest is already implemented

**Comment by windkh** [comment]
Version 11.7.0 will implement the commands.

**Comment by lu4t** [comment]
thanks!

**Comment by windkh** [comment]
Usage is similar to answerInlineQuery but with webAppQueryId:
The arguments are as follows:
msg.payload.webAppQueryId, msg.payload.results, msg.payload.options || {}
