### ISSUE TITLE
Cannot find event that catches Telegram.WebApp.sendData

### ISSUE THREAD

**Issue by MykhailKacha** [windkh/node-red-contrib-telegrambot#264]
Hello, cannot find any event that catches Telegram.WebApp.sendData.

```
Node-RED Version: 2.2.0
node-red-contrib-telegrambot Version: 12.0.0
```

> <img width="580" alt="image" src="https://user-images.githubusercontent.com/48906060/182632995-97a26978-48f7-4916-8216-4e6c9b518bae.png">

I was developing a webpage to include it into my bot using webapp feature.
I had a button, that sends data onclick to bot.

> <img width="393" alt="image" src="https://user-images.githubusercontent.com/48906060/182633381-34af5f55-f451-48a1-a50a-e8d2f4931f6f.png">

After click on the button telegram sends a message that I have passed data to bot

> 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/48906060/182633636-9966fc6b-5077-4a9e-8f26-bdf0a4f266ba.png">

So, I am not sure that this feature is already implemented, but I saw that you have added a support for API 6.0.0 version that contains WebApp support.

So, if I have missed something or this feature is not implemeted, please answer me in the issue.

Thank you for your library.
Have a nice day.

**Comment by windkh** [comment]
WebApp features are not supported yet. 
I added only few API 6.0 features that people requested a whike ago.

**Comment by windkh** [comment]
@MykhailKacha I would like to implement this for you. But how can I call Telegram.WebApp.sendData?
I never did a WebApp and would need your help to be able to reproduce/test it.

In my theory the bot will receive a message of a new type like SentWebAppMessage.

**Comment by ShotokanZH** [comment]
I am interested in this feature too.
Note: a catch-all-the-updates node would be amazing to configure new features without waiting for them to be implemented here :)

By the way:
1- create a web app that sends a message back:
```html
<script src="https://telegram.org/js/telegram-web-app.js"></script>                                                                                                                                   
<script>                                                                                                                                                                                              
window.Telegram.WebApp.sendData("SNADO");                                                                                                                                                             
</script>
```
2- upload it to a public web server ( https://example.com/test.html )
3- send a message to the user showing a custom inline keyboard:
```javascript
    msg.payload={
        reply_to_message_id: msg.payload.messageId,
        type: "message",
        content: "Managing stuff..",
        chatId: 1234567890,
        options: {
            reply_markup: JSON.stringify({
                keyboard:[
                    [
                        {
                            "text": "Manage Firewall",
                            "web_app": {
                                "url":"https://example.com/test.html?"+Math.random()
                            }
                        }
                    ]
                ]
            })
        }
    };
```
4- Just press on the gigantic "Managing stuff.." button
5- The bot will receive a Message object ( https://core.telegram.org/bots/api#message ) containing the WebAppData optional object populated ( https://core.telegram.org/bots/api#webappdata )
6- Enjoy ?

**Comment by windkh** [comment]
@ShotokanZH  thanks alot... exactly what I was looking for

**Comment by windkh** [comment]
please try 14.1.0
the message type is web_app_data and can be received using the receiver node

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/188013201-cced4401-1901-43b5-906b-f693515872b3.png)

**Comment by ShotokanZH** [comment]
Amazing work man!
