### ISSUE TITLE
poll quiz type not working

### ISSUE THREAD

**Issue by skynet-cloud** [windkh/node-red-contrib-telegrambot#265]
hi if use msg.payload.optional.type = "quiz"
```
msg.payload.type = 'poll';
msg.payload.content = "What do you think?";
msg.payload.options = ["A", "B", "C" ];

// you can add optional arguments see
// https://core.telegram.org/bots/api#sendpoll
msg.payload.optional = {
    allows_multiple_answers : true,
    is_closed : false,
    type: "quiz"
    
};
return msg;
```
> Caught exception in sender node:
> Error: ETELEGRAM: 400 Bad Request: wrong correct option ID specified
> when processing message:

**Comment by windkh** [comment]
hm strange seems to be correct
https://core.telegram.org/bots/api#sendpoll

can you try single quotes 'quiz' ?

**Comment by skynet-cloud** [comment]
correct option ID is messing
