### ISSUE TITLE
Replying with additional information on the telegram bot

### ISSUE THREAD

**Issue by mjtrini** [windkh/node-red-contrib-telegrambot#268]
Hello,

I have your telegram node running fine on my raspberry pi 4. I wish to include an additional button called STATUS that will let me know the state of digital inputs on my pi. Is it possible for you to provide an example flow showing how to bundle gpio states into a reply from the bot?

Much thanks and appreciation, 
Michael.

**Comment by windkh** [comment]
Sorry no.

**Comment by mjtrini** [comment]
Your examples and documentation do not clearly show how to capture external information in flows and forward it to the sender.

**Comment by mjtrini** [comment]
Not a problem. I found a more comprehensive telegram node with better documentation than yours.

**Comment by windkh** [comment]
Go ahead...
