### ISSUE TITLE
basic custom keyboard Issue

### ISSUE THREAD

**Issue by KaiJ17** [windkh/node-red-contrib-telegrambot#270]
Hi, I have encountered an issue while using this telegram node red flow, using it on my computer the selection has a "background" but telegram on my phone doesn't have that, I'm not sure if telegram side or the flow issue. 

![image](https://user-images.githubusercontent.com/102976255/189022069-6ad010f0-8d81-45a9-9859-d8f4b6ffd67a.png)
^ This image shows it on the computer

![image](https://user-images.githubusercontent.com/102976255/189022241-cafc0a2e-52bf-45b3-a58e-2e1995d961ca.png)
^ This image is on my personal phone

**Comment by windkh** [comment]
I think that this depends on how the client is implemented. The bot has nothing tomdo with that effect
