### ISSUE TITLE
Capture reactions

### ISSUE THREAD

**Issue by FullDad** [windkh/node-red-contrib-telegrambot#274]
Hey all!  I'm looking for some help.  Here is what i'm looking to do:

-When someone reacts with a "wave" emoji to a message i want to capture that and pull the original message's userid and then send a message.  

I've tried a lot of connectors and tried for more hours than i care to admit...is this possible?  If it isn't possible, what's a good way to get the bot to pull a user id to say kick or ban a user?  I want to be able to use send a /kick username to the bot and remove from the channel.

Thanks in advance for your time!

**Comment by windkh** [comment]
Hm I have to test this on my own first... never tried it before.

**Comment by windkh** [comment]
HI @FullDad
if you directly responded to the original message, then you can use the contents 
in reply_to_message: 

![image](https://user-images.githubusercontent.com/10910767/195924119-9da90b17-6c6a-49d6-8402-102d250ad2d0.png)
