### ISSUE TITLE
Bot cant connect in Polling Mode

### ISSUE THREAD

**Issue by photocromax** [windkh/node-red-contrib-telegrambot#276]
Since yesterday, after updating to 14.8.0, only bots that are polling, gives the following error

 `ReferenceError: performance is not defined`

If I disable the polling, the bot can connect successfully

Rolling back to 14.6.0 eliminates the problem.
Tried to roll back to 14.7.0 but the problem still persists (hope it can helps identifying where the problem is)

Please let me know if I can give you more details in order to solve the issue.

**Comment by windkh** [comment]
Thanks for reporting. I use let startTime = performance.now(); for measuring a duration.
What nodejs version du you use?

**Comment by photocromax** [comment]
Node 14.20.1, should I upgrade?

**Comment by windkh** [comment]
I will replace it with new Date().getTime()

**Comment by windkh** [comment]
should be fixed in V14.8.1

**Comment by photocromax** [comment]
I confirm V14.8.1 solved the problem.
performance.now() should be available since node V8.5... can't understand why I got that error.

Thanks for your fast solution.
