### ISSUE TITLE
answerCallbackQuery error

### ISSUE THREAD

**Issue by sanyafifa** [windkh/node-red-contrib-telegrambot#278]
after updating to `node-red-contrib-telegrambot: 14.8.2`, an error will appear and the bot's inline keyboard does not work. Help )

```
[warn] [telegram bot:c74c5bc9.eaaff8] telegramBot.answerCallbackQuery is not a function
 [warn] [telegram bot:c74c5bc9.eaaff8] Unknown error. Trying again.
```
```
telegrambot : 14.8.2
Node-RED version: v3.0.2
Node.js  version: v16.18.0
 Linux 5.15.68-v7l+ arm LE
```

**Comment by itsboo07** [comment]
same here...when i respond to callback query of  inline keyboard ...all telegram nodes gets to pooling state....please fix this

**Comment by itsboo07** [comment]
@sanyafifa a quick solution is to disable `Auto-Answer` in event node.. looks like with update this is turned on by default
![image](https://user-images.githubusercontent.com/87331871/196787583-b6b4948f-c2e4-49cf-a871-335a0dacc513.png)

**Comment by windkh** [comment]
@sanyafifa thanks for reporting... will check this immediately

**Comment by windkh** [comment]
Sorry for inconvenience... please try 14.8.2
