### ISSUE TITLE
'Send only mode' on command node

### ISSUE THREAD

**Issue by bdydrp** [windkh/node-red-contrib-telegrambot#280]
Just started playing with the command node, and noticed this after i deployed. 
![image](https://user-images.githubusercontent.com/63593828/200317596-7b2baed0-b112-4e2a-b79e-4b9fa05dfa82.png)

Attaching a debug, i dont dee any commnds being received...
Also, is my understanding correct in that, if i dont want to issue/start commands with '/' i leave "register at telegram server' checkbox unticked?

Cheers

**Comment by bdydrp** [comment]
i have, and when imported the command examples i got the same status under node..

This is my flow:
```[{"id":"a3bae5ae7b2d5dee","type":"debug","z":"97ef67ae.095ef8","name":"debug 38","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1200,"y":480,"wires":[]},{"id":"703c21a2d548de29","type":"telegram command","z":"97ef67ae.095ef8","name":"/seefrontdoor","command":"/seefrontdoor","description":"","registercommand":false,"language":"","scope":"default","bot":"fa7a9376.321ce","strict":false,"hasresponse":false,"useregex":false,"removeregexcommand":false,"outputs":1,"x":810,"y":480,"wires":[["9d7b7c82709ac4ce"]]},{"id":"9d7b7c82709ac4ce","type":"telegram sender","z":"97ef67ae.095ef8","name":"","bot":"fa7a9376.321ce","haserroroutput":false,"outputs":1,"x":1010,"y":480,"wires":[["a3bae5ae7b2d5dee"]]},{"id":"fa7a9376.321ce","type":"telegram bot","z":"97ef67ae.095ef8","botname":"HubitatNRbot","usernames":"","chatids":"","baseapiurl":"","updatemode":"none","pollinterval":"","usesocks":false,"sockshost":"","socksport":"","socksusername":"","sockspassword":"","bothost":"","botpath":"","localbotport":"","publicbotport":"","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]```

**Comment by windkh** [comment]
The send only mode indicates that the bot does not receive any command nor any message. In this mode you can only send messages. If you want to use commands then set the update mode to polling
