### ISSUE TITLE
Failed to call /setMyCommands: : 400 Bad Request: BOT_COMMAND_INVALID"

### ISSUE THREAD

**Issue by palvarez89** [windkh/node-red-contrib-telegrambot#283]
```
"Failed to call /setMyCommands for language : Error: ETELEGRAM: 400 Bad Request: BOT_COMMAND_INVALID"
```

I believe this command has changed and is now `/setcommands`

**Comment by windkh** [comment]
did you make use of any capital letter? so instead of /Foo it must be /foo

**Comment by palvarez89** [comment]
Hi, I had 2 nodes, one with `/test` and other with `/temps`. Only was registering one of them. After I enabled both this warning went away, and the commands were being configured correctly.

The error message was misleading. It made me think the issue was that we were sending the wrong command.

**Comment by windkh** [comment]
The error is directly issued by the Telegram Server. It was not created by the nodes.

**Comment by windkh** [comment]
@palvarez89 so the error is not reproducible?
If not then I would close the issue and if it appears again, then I would need an example flow, ok?

**Comment by palvarez89** [comment]
> The error is directly issued by the Telegram Server. It was not created by the nodes.

that explains why I wasn't able to find the error message in the codebase. Closing this now!

Thank you for replying so quick, and for this project!
