### ISSUE TITLE
[FR] Update documentation on Receiver Node?

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#289]
i fiddelt with receiving messages in a chat with 7 of my bots, and did not get all messages. 
now i would like to see the documentation on a bot which is receiving messages a bit clearer on some crucial points:

i dont know better to make some annotations than on the existing docu section:
| screenshot |
| :----:| 
![image](https://user-images.githubusercontent.com/5937811/210967807-292cdece-3b34-4686-b917-9df3c59af1b4.png)
somehow some inverse logic: ```/setprivacy must be **DISABLED** to receive chat messages```

also i found a helpful german page with the information of the broken link
https://teleme.io/articles/group_privacy_mode_of_telegram_bots

edit: changed settings on /setprivacy can be checked in the APP. (in the webui looks like that its missing)
on a chatgroup see the memberlist, find the bot and there the status will than be shown as "Access to messages"  (instead before "NO Access....")

what do you think?

(and as always: Great Work! 🏅 )

**Comment by windkh** [comment]
Thanks for your input. As always the documentation was done in a hurry and useful details are missing as I am not aware of what the users already know and how expirienced they are.I will adapt the doc as you suggested. C u khGesendet mit der WEB.DE iPad AppAm 06.01.23 um 10:08 schrieb toz
                
            
            
                
                    Von: "toz" ***@***.***>Datum: 6. Januar 2023An: "windkh/node-red-contrib-telegrambot" ***@***.***>Cc: "Subscribed" ***@***.***>Betreff: [windkh/node-red-contrib-telegrambot] [FR] Update documentation on Receiver Node? (Issue #289)
                
                

i fiddelt with receiving messages in a chat with 7 of my bots, and did not get all messages.

now i would like to see the documentation on a bot which is receiving messages a bit clearer on some crucial points:

i dont know better to make some annotations than on the existing docu section:







screenshot















somehow some inverse logic: /setprivacy must be **DISABLED** to receive chat messages








also i found a helpful german page with the information of the broken link

https://teleme.io/articles/group_privacy_mode_of_telegram_bots

what do you think?

(and as always: Great Work! 🏅 )

**Comment by ozett** [comment]
documentation is good, 
even it comes out of "a hurry"

but could be a bit "sharpend" over time
