### ISSUE TITLE
Seems to be impossible to have a bot send messages to a channel

### ISSUE THREAD

**Issue by osulivanDE** [windkh/node-red-contrib-telegrambot#291]
Hi, i can´t get my bot to post into Telegram Channels. Posting into a Group is no Problem but sending messages into a channel results in getting the message sent to the Telegram Bot instead of the channel.

Is this intended behavior and what can i do to get my messages post into a channel?

I´m sending this into the Telegram Sender node:

msg.payload = {
    type: "message",
    content: "test",
    chatId: 5476XXXXX
    }; 
return msg;

Thanks

**Comment by windkh** [comment]
Can you check if the bot is allowed to send messages in that particular channel?

**Comment by osulivanDE** [comment]
Sorry, as i posted this i found out i have gotten the wrong Channel ID from the GetIDs bot. This was my own mistake. Posting into Channels is working.
