### ISSUE TITLE
Error stopping node: Close timed out

### ISSUE THREAD

**Issue by FISEChris1337** [windkh/node-red-contrib-telegrambot#292]
Morning,

i have a fresh installation with nodered and now just setup telegrambot today (14.8.7) i got the only error message via Debug when i restart the flow nothing more. Sometimes there is the same in syslog. After upgrade to latest 15.0.1 same issue. complete uninstall and fresh telegrambot install. nothing changed.

Any idear where i can look for this issue? no communications :/

node said - connected
NR 3.0.2
rpi4 debian bullseye latest updates from today

**Comment by windkh** [comment]
The same problem was already discussed here. There are two ways how to install nodered on a raspi. 
Maybe you check the other issues here for a hint...

**Comment by FISEChris1337** [comment]
same installation on different pi is working so this did not help . maybe interessting to find the real issue. reinstall raspberry os is not always a 5min option. thats why iam asking maybe are there anywhere more logs?

**Comment by windkh** [comment]
Is this a duplicate issue: see #282
