### ISSUE TITLE
installation in ccu3 failed

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#293]
Hi,
message:
"[node-red-contrib-telegrambot] Node module cannot be loaded on this version. Requires: >=1.3.7 "

"TypeError: Cannot read property 'nodes' of null"

Redmatic: 7.2.1

Any idea?

**Comment by windkh** [comment]
What node-red version is on that ccu3?

**Comment by averlon** [comment]
O.K - I found node-red = 1.2.9. Anyhow, the update of node-red-contrib-telegrambot to 15.0.1 is offered.
An when I start the update it fails and telegrambot is not anymore available on the system which causes follow-up errors on all nodes and flows where telegrambot is included.

I was forced to restore the CCU3 with my latest backup - which worked - as far as I can see!

**Comment by windkh** [comment]
Well basically the nodes should work on older node-red versions. However since node-red introduced scorecards they published a tool that checks for compatibility. The output of this tool said that the nodes require at least 1.3.7 (don't ask me why).
So I added the information as suggested. The same goes for the nodejs version.
Maybe you search for a way to update the node-red version on your CCU3.

**Comment by averlon** [comment]
Thanks for reply!
There is currently no update offered and I don't like to install versions e.g. from Github - or other not officially offered sources.

I would like to encourage you to check the version of node-red befor any part of the installation starts - how ever this can be done - so at least the currently installed version stays as is.

O.K. - the good thing is: the restore worked. Although after restore Redmatic was not installed on the CCU3 and I assumed I had lost all flows. But after reinstalling Redmatic and logging in to Node-Red on the CCU3 all flows were as I left them before the backup - good to know!
I will immediately run a new backup and som export of the flows.

**Comment by windkh** [comment]
The current node-red version is 3.0.2 which means that the CCU3 is really outdated.

The complete installation is performed automatically by node-red, not by any of my code.
So the version check that you recommended to do before damaging something is an issue you should raise in the node-red community.

**Comment by windkh** [comment]
I could set the node red required version to a lower one.
But then the same could happen after installation.
