### ISSUE TITLE
live location in groups

### ISSUE THREAD

**Issue by PeterHunt** [windkh/node-red-contrib-telegrambot#297]
Hello,

I just started testing with live locations in a group. As far as I can see, only the initial location is sent, but I cannot find any updates (edited message). In private chats this is working perfectly.

Am I overseeing something, or might groups intendently have been excluded?

Kind regards,
Peter Hunt

**Comment by windkh** [comment]
Hm never tried that. Can you share a flow where I can see what you want to achieve?

**Comment by PeterHunt** [comment]
My flows are pretty complicated :)

I think the user-case will be a bit too much to explain, but let me try a little basic, without the end-user data.
A user can send his fixed location which can provide him some data in his area.
A user can also send his live location so he gets constant updates from his (changing) area.
When monitoring the debug node attached to the Event Node > Edited Message, I see the constant updates from the location.

As mentioned in the OP, when user sends his live location in a group, the BOT fetches the initial location coordinates, but I don't see any updates.

I think it should be enough to create a test group with you and the BOT and to see if you are able to fetch location updates anywhere. I think the current BOT version does not supports it (yet).

Kind regards,
Peter Hunt.

**Comment by windkh** [comment]
You closed it?

**Comment by PeterHunt** [comment]
Sorry I don't think I intended to close this one. For my use-case I only needed a group for test-purposes. I don't need it permanently. So I guess this still remains an issue. Not for me, so you should't give it any priority right now :)

**Comment by nkgiovannivl** [comment]
Hi All,

I'm having the same issue, when a location is shared on a group, every coordinates change generate a updates message, but the node does not detect , using polling or webhook.

![image](https://github.com/windkh/node-red-contrib-telegrambot/assets/48342344/8d53b0d4-093e-4bce-885f-eeec2c109ce4)

So, I'm not sure if it's a bug or I'm missing some configuration?

**Comment by windkh** [comment]
I will check if there are limitations by telegram...

**Comment by nkgiovannivl** [comment]
> I will check if there are limitations by telegram...

Well, just after a full node red restart, location updates are incoming from edited message, thanks!

**Comment by windkh** [comment]
Hi all, I checked it out: in my group I get notifications for location updates as "edited_message" via the event node.
