### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by Floppe** [windkh/node-red-contrib-telegrambot#3]
Hi!

Authorization does not work for me. Unknown users are using all methods though I have filled in my own chat ID in the configuration. I do not have any username assigned to my account, if that could be the issue.

**Comment by windkh** [comment]
Hi, 
which version do you use? There was a bug in authorization some versions ago, so make sure you have the latest one.

If you have ausername assigned to your own account doesn't matter here. The received message contains a username of the sender and the chatId of the chat the message came from. If the chatId is the same, the user is allowed to enter the bot. If the chatId does not match, but the user is on the list of the allowed users then access is granted, too.

Does authorization work if you leave the chatId blank and enter a username (separated by a , and without any blanks ... e.g.:
foo,bar

**Comment by Floppe** [comment]
node-red-contrib-telegrambot@1.9.3

**Comment by windkh** [comment]
I think I could reproduce your problem. If you enter a number in "ChatIds" but leave the "Users" field empty, then the bot grants access. The same problem could occur if you configure it vice versa. I will fix this as soon as possible, In the meanwhile you could enter just a dummy name in "Users".
Thank you for reporting this.

**Comment by windkh** [comment]
Fixed in version 1.10.0

**Comment by Floppe** [comment]
Thank you!
