### ISSUE TITLE
send contact example?

### ISSUE THREAD

**Issue by ImTheDeveloper** [windkh/node-red-contrib-telegrambot#30]
Hey,

I've been wondering if you could supply an example of the bot sending a contact. I have tried numerous ways to get this working but don't seem to be getting this right for example, by placing a function node before my sender with:

```
msg.payload.type = "contact"
msg.payload.content.phone_number = "numberhere"
msg.payload.content.first_name = "userhere"
msg.payload.content.user_id = idhere
return msg;
```

as well as just required fields in underlying API

```
msg.payload.type = "contact"
msg.payload.content.phoneNumber= "numberhere"
msg.payload.content.firstName= "userhere"
return msg;
```

Thanks for any help.

**Comment by windkh** [comment]
I will add a sample. But in the meantime try to add a debug–node after a receiver node and send a contact to the bot. Now have a look at the output: there should be all fields you need to know.

**Comment by ImTheDeveloper** [comment]
Ah maybe I didn't explain. I see that information when receiving a contact
but I thought I could also send a contact from the bot once one had been
received ?
https://core.telegram.org/bots/api#sendcontact

**Comment by windkh** [comment]
You are right that should work, but I just noticed that the send function is missing. I am fixing it right now. New release should be available in a few minutes.

**Comment by windkh** [comment]
2.7.0 is able to send a contact. But unfortunately the underlying api only supports the first_name and phone_number property. But you can also receive last_name.
This should work now: 

msg.payload.chatId = yourchatidhere;
msg.payload.type = "contact";
msg.payload.content.phone_number = "numberhere"
msg.payload.content.first_name = "userhere"
return msg;

**Comment by windkh** [comment]
sorry for inconvenience!

**Comment by windkh** [comment]
2.7.1 supports the last_name property. Example flow is included now.

**Comment by ImTheDeveloper** [comment]
Working thanks
