### ISSUE TITLE
Error: ETELEGRAM: 400 Bad Request: can't parse prices JSON object when processing message:

### ISSUE THREAD

**Issue by mihail4anov** [windkh/node-red-contrib-telegrambot#302]
[This](https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/sendinvoice.json) example does not work anymore(

**Comment by windkh** [comment]
hm maybe the api changed?
https://core.telegram.org/bots/api#sendinvoice

**Comment by windkh** [comment]
startParameter was removed: please test next version

**Comment by windkh** [comment]
@mihail4anov thanks for reporting!

**Comment by mihail4anov** [comment]
> mihail4anov

Now it says:
Error: ETELEGRAM: 400 Bad Request: parameter "currency" is required
when processing message:

**Comment by windkh** [comment]
The node passes the following args:
                                chatId,
                                msg.payload.content.title,
                                msg.payload.content.description,
                                msg.payload.content.payload,
                                msg.payload.content.providerToken,
                                msg.payload.content.currency,
                                msg.payload.content.prices,
                                msg.payload.options

**Comment by windkh** [comment]
The underlying lib accepts
function sendInvoice(
chatId, 
title, 
description, 
payload, 
providerToken, 
currency, 
prices)

--> looks ok

**Comment by mihail4anov** [comment]
> Is there a way we can debug this on your computer together in a teams meeting?

Yea, sure
Text me: https://t.me/Michael_WiFi

**Comment by shevchenkoav** [comment]
Up

**Comment by pupupupupup** [comment]
Up

**Comment by windkh** [comment]
Version 15.1.0 fixes the problem: I will update the examples
