### ISSUE TITLE
Port conflict pevents node-red from starting

### ISSUE THREAD

**Issue by bogorad** [windkh/node-red-contrib-telegrambot#303]
I set up two bots, both in `webhook` mode and both using the same local port. The node fails **and** prevents node-red from starting.

Maybe it should just report failure into the log (or, alternatively, report & switch to `polling`?), but not prevent node-red from starting?

**Comment by windkh** [comment]
Hm I will check this, thanks for reporting

**Comment by windkh** [comment]
please check 15.1.1
