### ISSUE TITLE
how to implement like BotFather inline keyboard

### ISSUE THREAD

**Issue by azrin1972** [windkh/node-red-contrib-telegrambot#31]
Hi I'm trying to implement inline keyboard like Bot Farther where every time you select an inline keyboard button, the message will be replaced with a new set of buttons without creating a new line of message. I think it is using the editMessageReplyMarkup but how to implement it using this contrib?

Thanks in advance

**Comment by windkh** [comment]
Hm, I will have a look at it... this evening.

**Comment by windkh** [comment]
Hi, I played around with the editMessageReplyMarkup and finally I got it running. Right now sending this kind of message is not supported, but could be introduced easily. The only pitfall when using this function is that you need to specify the messageId of the original message you want to edit. Storing such an id must be done in the flow context itself. If you want I can release a new version of the nodes that contain this feature, but the rest has to be done in the flow itself. I could provide a sample for that, too.

**Comment by azrin1972** [comment]
Yes please - thank you very much

**Comment by azrin1972** [comment]
you can email me to azrin.aris(at)gmail.com btw

Thank you

**Comment by windkh** [comment]
version 2.7.2 can handle this. Have a look at the example editinlinekeyboard.json

editMessageReplyMarkup and deleteMessage are tunneled using the message type. I am not glad with this solution and this could probably changed in future.

**Comment by azrin1972** [comment]
Hi Karl. 

Thanks for the update. As I’m using it now, I might be of help once I understand how things works - it that is ok with you. 

Sincerely 
Azrin

**Comment by windkh** [comment]
Yes of course. Did you try out the sample yet?

**Comment by azrin1972** [comment]
Yes I did. And I’m changing my flow now to use the new feature. Thank you very much. 

Sincerely 
Azrin

**Comment by azrin1972** [comment]
Hi Karl,

The example you show works and after looking closely how Bot Father reply to inline keyboard event, it changes the message too and not only the markupMessage. If I want to start implement editMessageText, how best I do that and test? If everything succeeded, then I can make a pull request

**Comment by windkh** [comment]
Hm, then it would be best to not only replace the markup but also the text in one term.
I will implement this, no need for a pull request.

**Comment by azrin1972** [comment]
Hi Karl

Thank you, I really appreciate this.

Btw, I just did some test by adding this line and it works.

                                case 'editMessageText':
                                    node.telegramBot.editMessageText(msg.payload.content, msg.payload.options).then(function (sent) {
                                        msg.payload.sentMessageId = sent.message_id;
                                        node.send(msg);
                                    });
                                    break;

This works as the bot father does.

**Comment by windkh** [comment]
Yes, that is working using two requests, I will search for a solution to be able to do this using a single one

**Comment by windkh** [comment]
2.7.3 contains your changes and the editMessageCaption command now.

**Comment by azrin1972** [comment]
Thanks Karl. 

Appreciate the update.

Sincerely 
Azrin
