### ISSUE TITLE
Timeout on Callback query?

### ISSUE THREAD

**Issue by K-RAD** [windkh/node-red-contrib-telegrambot#310]
I've been trying to find an answer to this to no avail. Is there a way to put a timeout on a callback query? Like after a specified time it disables it. I saw there is a removeListener function applied in other implementations, but I don't know if it's been implemented here?

**Comment by windkh** [comment]
Can you provide a link to the code where you found that removeListener pattern?

**Comment by K-RAD** [comment]
It's used in this implementation [here](https://github.com/scraton/node-red-contrib-telegrambot-home/blob/master/nodes/switch/switch.js) but it came up in some other places too during my google'ing

**Comment by windkh** [comment]
I will check it out

**Comment by windkh** [comment]
@K-RAD checked it out, but I guess that is not that easy to implement. Sorry.
