### ISSUE TITLE
Missing msg.payload.sentMessageId in Pinned Message

### ISSUE THREAD

**Issue by proton555** [windkh/node-red-contrib-telegrambot#313]
EDIT : Please close
---------------
Telegram Bot API deleteMessage function supports deleting service messages

I am using sender node. I got the previous SentMessageId & used PinMessage example to pin a message fine (top)
but to delete that pin service message, i could not find any SentMessageId . It says "undefined" (Bottom)
So how do i delete the "Bot pinned xyz" service message?
![image](https://github.com/windkh/node-red-contrib-telegrambot/assets/20039806/530d985f-26f0-410c-9f02-ad0c950d3ae5)

I found that in case of a non-busy group, service message ID = initial messageID+1 (checked link manually in group)
I can use that way but that would create problems in busy group/laggy bot

Thanks Karl :)

**Comment by proton555** [comment]
Just tried deleting using the previous message+1 integer and it gave error
"ETELEGRAM: 400 Bad Request: message can't be deleted"

https://core.telegram.org/bots/api#deletemessage
Oops i missed. Silly me
"- Service messages about a supergroup, channel, or forum topic creation can't be deleted"

Sad! Is there any other workaround i can use other than userbot?
Also Karl, any chance of incorporating userbot token? Some of us requested you some months back. we can have lot of additional power to bots :)  Thanks

**Comment by windkh** [comment]
I will create nodes for userbots ... if I can find sone time
