### ISSUE TITLE
Support for [media] file upload

### ISSUE THREAD

**Issue by outlying** [windkh/node-red-contrib-telegrambot#316]
According to documentation Telegram API supports file upload with `multipart/form-data` but I cannot find a way to do it with available Telegram nodes.

https://core.telegram.org/bots/api#inputmediaphoto

**Comment by windkh** [comment]
Did you check the examples folder?

**Comment by windkh** [comment]
@outlying 
I guess you can use sendMediaGroup

https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/sendmediagroup.json

**Comment by windkh** [comment]
@outlying any news?

**Comment by outlying** [comment]
@windkh Yes, sorry, I provided a local path to the image/video in the message and it worked out, file was uploaded

At first I looked at documentation and there was no indication that it could be done this was, although public URL was suggested in few cases
