### ISSUE TITLE
Not recovering from network down: getaddrinfo EAI_AGAIN api.telegram.org

### ISSUE THREAD

**Issue by ivanvaccari** [windkh/node-red-contrib-telegrambot#317]
I'm hosting a nodered instance at my home server (docker image on ubuntu 20.04), which controls various stuff and uses telegram to provide real time notifications and interactions.

My network connection is quite stable, but once a week it drop for some reasons. The downtime duration is mostly some minutes only, but it's enough to break the telegram polling.

The error never recover itself and persist until a manual deploy is executed, and mostly appear as "getaddrinfo EAI_AGAIN api.telegram.org". On web ui, the node displays "polling" forever:

![image](https://github.com/windkh/node-red-contrib-telegrambot/assets/28731723/1de56e93-39ea-4486-9bf7-af97f5f9b208)

See log attached, relevant events:
11 Jun 11:07:12 - connection drops
11 Jun 11:14:34 - connection reappear. Mqtt broker reconnect succesfully.

[nr_log.txt](https://github.com/windkh/node-red-contrib-telegrambot/files/11749848/nr_log.txt)

Nodered version: 3.0.2, custom docker build (https://github.com/ivanvaccari/node-red-docker, which is just a fork of official nodered but built with debian instead of alpine, mostly for glibc issues with one node i'm using)

**Comment by windkh** [comment]
That was reported in the past, too but I was never able to reproduce... I will try with your docker image

**Comment by ivanvaccari** [comment]
Fyi: the docker image probably is ininfluent, had the same problem with the official one before using the one built by me

**Comment by ivanvaccari** [comment]
No, i'm using a intel nuc( i3, 8gb RAM, msata ssd), connected via cable to the router.

**Comment by ivanvaccari** [comment]
Failed again, but this time the origin of the failure might differ: yesterday morning i did some electrical works, and i switched the house power breaker off. The server powered down, and when the power was restored, the server surely powered up before the router can connect to internet.
The telegram node apparently does not like this, see attached log: 
[nr_log_18-06-2023.txt](https://github.com/windkh/node-red-contrib-telegrambot/files/11780826/nr_log_18-06-2023.txt)

**Comment by windkh** [comment]
Hi you are at HS Augsburg?I live nearbyVon meinem iPhone gesendetAm 18.06.2023 um 09:15 schrieb Ivan Vaccari ***@***.***>:﻿
Failed again, but this time the origin of the failure might differ: yesterday morning i did some electrical works, and i switched the house power breaker off. The server powered down, and when the power was restored, the server surely powered up before the router can connect to internet.
The telegram node apparently does not like this, see attached log:
nr_log_18-06-2023.txt

**Comment by ivanvaccari** [comment]
Nope.. i live in north italy

**Comment by windkh** [comment]
Hm strange, when I attempted to download your file that page opened. Never mind.

**Comment by ivanvaccari** [comment]
> @ivanvaccari just a wild idea, also try having a https certificate enabled in nodered (if not). May be that helps, otherwise its connectivity (Perhaps also manually test the relation of duration of disconnection with failure)

mmh.. my nodered intance is not public, i can access it only via lan (or via vpn to my router). I particularly don't like having stuff on public ports, that's why i prefer polling.. Without a public domain https is out of question.

I'll check for dropout duration but i mostly see some minutes a couple of times at week. Most of the times it don't even change the connection ip.

**Comment by windkh** [comment]
@ivanvaccari any news?

**Comment by ivanvaccari** [comment]
Ended up using webhooks, the polling was broken most of the times i needed it.
