### ISSUE TITLE
receiver not receiving when bot is in a group with telegram topics turned on

### ISSUE THREAD

**Issue by cryptobugbear** [windkh/node-red-contrib-telegrambot#318]
I was using node-red-contrin-telegrambot albeit an older version, now upgraded to 15.1.4 and node-red 2.1.3 on raspberry pi 4 within a group. Recently, I enabled topics and now the bot is not able to receive messages. 

Is this a bug or some missing setting?

**Comment by windkh** [comment]
you must allow the bot to receive messages from chats using botfather

and inside groups or channels you must configure what the bot is allowed to. But that can only be done by adminstrators of groups and channels. Not that there are differences betwenn what is allowed inside groups and supergroups and channels. In general bots can not receive messages from other bots.... please read the details in the telegram bot documentation

**Comment by windkh** [comment]
@cryptobugbear any news?

**Comment by cryptobugbear** [comment]
Hey there, in the end, I had just reconfigured using my own api calls. But along the way, i realised that for this library, i might have misconfigured it. Although,  I will need to debug it again to see what i missed. I think can close first.

**Comment by windkh** [comment]
Ok thanks
