### ISSUE TITLE
NPM install > 404 error

### ISSUE THREAD

**Issue by Marmachine** [windkh/node-red-contrib-telegrambot#319]
Apart from several warnings, the NPM install method ends in a 404 error on Node-Red v3.0.2 ;

`$ npm install node-red-contrib-telegrambot --save`

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-red-contrib-oauth2/-/node-red-contrib-oauth2-2.0.0.tgz - Not found
npm ERR! 404
npm ERR! 404  'node-red-contrib-oauth2@https://registry.npmjs.org/node-red-contrib-oauth2/-/node-red-contrib-oauth2-2.0.0.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

>> seems that oauth2 is a dependency, thus this needs to be installed before running the above command;
`$ npm install node-red-contrib-oauth2`

**Comment by windkh** [comment]
All I can see is that oauth2 can not be installed... ???
Are you sure that that output results from that commandline?

**Comment by Marmachine** [comment]
Yes, you are right... installing oauth is the fix, but it wasn't mentioned.
Thanks for your quick response!
Cheers

**Comment by windkh** [comment]
My package does not reference anything related to oauth ...

**Comment by Marmachine** [comment]
Ohh, my bad... i think this might come from some other flow that was still in NPM's scope... i'm currently moving from v 1.2.7 to Node-Red v3.0.2
Sorry to bother you
