### ISSUE TITLE
Read confirmation

### ISSUE THREAD

**Issue by anthoferd** [windkh/node-red-contrib-telegrambot#32]
Hello,

is it possible to get a read confirmation after sending a message?

Thanks a lot.

**Comment by windkh** [comment]
Right now you get the result from the sendrequest. What you mean is some indicator that the user read your message, like in Whatsapp, or?

**Comment by anthoferd** [comment]
Yes. In the telegram app (e.g. on iPhone) I get:
1 hook -> messages sent to user
2 hooks -> message read by the user

**Comment by windkh** [comment]
I will try to find a solution

**Comment by windkh** [comment]
The bot api does not support this, only the client api. As this project only makes use of the bot api, there is no way for realizing this right now. As soon as the bot api supports this I will integrate it.
