### ISSUE TITLE
Infinite polling 

### ISSUE THREAD

**Issue by zozo2905** [windkh/node-red-contrib-telegrambot#323]
Hello, i am trying to receive message on Node Red from telegram with the receiver node. 
But I have an infinite polling on this node with this warning : "
EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443"
"Timeout connecting to server. Maybe proxy blocked polling. Trying again."
Do you know more about my issue ?

**Comment by windkh** [comment]
The IP is correct. Timeout indicates that there is a network problem
 can you ping this IP?

**Comment by zozo2905** [comment]
Indeed, i can't ping this address correctly, I have a timed out. 
Is it possible that my network block this connection ?

**Comment by windkh** [comment]
I think that the problem is in your network configuration
