### ISSUE TITLE
Get File name from sent document

### ISSUE THREAD

**Issue by SimoneGuido04** [windkh/node-red-contrib-telegrambot#324]
Hi, i was wondering if i can get filename of sent document instead of file_id.

![Screenshot 2023-08-01 222905](https://github.com/windkh/node-red-contrib-telegrambot/assets/44775558/ac5f6d91-ca50-495a-918b-28b7325c7ac6)

**Comment by windkh** [comment]
If you are lucky then you will find it in msg.originalMessage

**Comment by SimoneGuido04** [comment]
Thanks very much! <3
