### ISSUE TITLE
How to editForumTopic (2)

### ISSUE THREAD

**Issue by PeterHunt** [windkh/node-red-contrib-telegrambot#325]
Hello Karl,

In #305 I already addressed this issue, but the issue is closed as completed. You fixed the chatId / chat_id issue, but my BOT is still not able to edit a forum topic.

As for my use case, I have a group, divided into threads. Some threads can contain warnings or alarms. If so, I would like the BOT to add an icon to the topic, so when someone opens the thread list, one can easily see if there are any open issues.

Could you please try this as well? In #305 I pasted some code which I've tried (as well as the Senders output), but without any luck..

**Comment by windkh** [comment]
Hi Peter,
maybe you can show this to me in a teams meeting... after my vacation (21.8.)?
Br kh

**Comment by PeterHunt** [comment]
> Hi Peter, maybe you can show this to me in a teams meeting... after my vacation (21.8.)? Br kh

Yes, sure can. You message me via @peter_p2kflex on Telegram

**Comment by windkh** [comment]
@PeterHunt 
thanks for the nice meeting.
