### ISSUE TITLE
ReplyKeyboardRemove

### ISSUE THREAD

**Issue by SimoneGuido04** [windkh/node-red-contrib-telegrambot#326]
Hi, I was wondering if there is an option to remove the custom keyboard, I found out that on the telegram APIs there is an option called "ReplyKeyboardRemove" that can force remove the custom keyboard, how can implement that? any suggestions?

**Comment by windkh** [comment]
I will add this for you in the next version if possible

**Comment by SimoneGuido04** [comment]
Thank you vary much!

**Comment by windkh** [comment]
Please reopen it. I will close it when the feature is implemented

**Comment by SimoneGuido04** [comment]
Sure Man! Do you know when u gonna release new version?

**Comment by SimoneGuido04** [comment]
If someone was wondering how to overcome to that issue (until new version came out) there is a workaround:
```
const token = 'BOT TOKEN';
    const chatId = msg.payload.chatId;
    const messageText = 'Grazie per aver consultato gli appunti';

    const keyboardRemove = {
        remove_keyboard: true
    };

    axios.post(`https://api.telegram.org/bot${token}/sendMessage`, {
        chat_id: chatId,
        text: messageText,
        reply_markup: JSON.stringify(keyboardRemove)
    })
        .then(response => {
            console.log(response.data);
        })
        .catch(error => {
            console.error(error);
        });
```
you need to include "axios" module in Setup Tab.

**Comment by windkh** [comment]
@SimoneGuido04 
looking at the api doc I recognized that ReplyKeyboardRemove is just an object like 
[InlineKeyboardMarkup](https://core.telegram.org/bots/api#inlinekeyboardmarkup) or [ReplyKeyboardMarkup](https://core.telegram.org/bots/api#replykeyboardmarkup) or [ReplyKeyboardRemove](https://core.telegram.org/bots/api#replykeyboardremove) or [ForceReply](https://core.telegram.org/bots/api#forcereply)

which can be passed as optional parameter named reply_markup.

So there is no need for any changes in the code: just add reply_markup property to the options of your message.
Just have a look at the keyboard examples and look for InlineKeyboardMarkup.... just do it the same way but with ReplyKeyboardRemove. 

I just do not have the time to test this, but if you fail, then let me know.

**Comment by vsubbotskyy** [comment]
I just tested it and it worked. Only I can't sent control message without the text. Here's the content of my function node:
```
var opts = {
    reply_to_message_id: 0,
    reply_markup: JSON.stringify({
        "remove_keyboard" : true
    })
};

var payload = {
    chatId: chatId,
    type: 'message',
    content: 'Non empty string is required',
    options: opts,
};

msg.payload = payload;

return msg;
```
