### ISSUE TITLE
Receive other BOTs post in groups

### ISSUE THREAD

**Issue by PeterHunt** [windkh/node-red-contrib-telegrambot#328]
Hi Karl,

Maybe I'm making a mistake somewhere, but I'm using 2 different BOTs. Both have their own porpose, but they happen to share one group. When I use the receiver node, I can see all messages sent in the group, but not from the other BOT...?

As far as I can think of, there are 3 options;

1. I have a misconfiguration in my group settings
2. It's a bug in your Telegram BOT
3. Telegram does not allow this?

Please help me. My BOT#1 wants to fetch BOT#2 alarm messages

Kind regards,

Peter Hunt

**Comment by windkh** [comment]
Answer is 3

**Comment by PeterHunt** [comment]
So telegram does not allow this. Did not expect that, too bad. Have to find another solution.

Thanks for the prompt reply :)
