### ISSUE TITLE
 I want to replace photo it with a document that is located locally

### ISSUE THREAD

**Issue by temkagordin** [windkh/node-red-contrib-telegrambot#330]
I send a photo with caption to telegram, after i want replace it as pdf file
```javascript

var options = {
    chat_id: CHAT_ID,
    message_id: MESSAGE_ID
};

var inputMediaPhoto = {
    type: "document",
    media: msg.filepath // document path like /var/www/aaa/test.pdf
}

msg.payload = {
    type: 'editMessageMedia',
    content: inputMediaPhoto,
    options: options,

}
return msg;
```

after send from telegram node not have response, and image was not replaced

**Comment by windkh** [comment]
Please add a debug node to the sender: what is the output?

**Comment by temkagordin** [comment]
@windkh nothing 
<img width="716" alt="image" src="https://github.com/windkh/node-red-contrib-telegrambot/assets/12200392/6c25fce8-d7fe-420e-96a5-369174514c20">
last was when sent 
<img width="270" alt="image" src="https://github.com/windkh/node-red-contrib-telegrambot/assets/12200392/207bcc23-9443-4e76-9182-1b263c64f77a">

**Comment by windkh** [comment]
Please send me the flow

**Comment by temkagordin** [comment]
I found explanation of my problem 

https://core.telegram.org/bots/api#editmessagemedia

Use this method to edit animation, audio, document, photo, or video messages. If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise.
