### ISSUE TITLE
Can't install  15.1.6

### ISSUE THREAD

**Issue by manri-CNC** [windkh/node-red-contrib-telegrambot#333]
Error:cannot enable cancellation after promise are in use (line:15)

node red version 3.0.2 

node.js version 18

**Comment by windkh** [comment]
@manri-CNC don't know why. Here it works correctly. Can you provide more information?

**Comment by manri-CNC** [comment]
Hallo Herr Wind,
 node red is istalled on a Ubuntu 20.04 Server and here the versions which are installed

30 Aug 22:49:58 - [info] 

Willkommen bei Node-RED
===================

30 Aug 22:49:58 - [info] Node-RED Version: v3.0.2
30 Aug 22:49:58 - [info] Node.js  Version: v18.17.1
30 Aug 22:49:58 - [info] Linux 5.4.0-156-generic x64 LE
30 Aug 22:49:58 - [info] Paletten-Nodes werden geladen
30 Aug 22:49:59 - [info] node-red-contrib-ccu version: 3.4.2
30 Aug 22:50:00 - [info] Einstellungsdatei: /home/nextcloud/.node-red/settings.js
30 Aug 22:50:00 - [info] Kontextspeicher: default [module=memory]
30 Aug 22:50:00 - [info] Benutzerverzeichnis: /home/nextcloud/.node-red
30 Aug 22:50:00 - [warn] Projekte deaktiviert: editorTheme.projects.enabled=false
30 Aug 22:50:00 - [info] Flow-Datei: /home/nextcloud/.node-red/flows.json
30 Aug 22:50:00 - [error] Nicht abgefangene Ausnahmebedingung:
30 Aug 22:50:00 - [error] Error: listen EADDRINUSE: address already in use 0.0.0.0:1880
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)


BTW I could install 5.1.4 but 5.1.6 failed.

I can't add a picture here, so I try to discribe. After I installed 5.1.6 it will be shown in the "Installierte Nodes", but under the version the following warning is shown 

    Error: cannot enable cancellation after promises are in use (line:15)

and the nodes are not shown in the lnode list on the left.

If you need more information let me know and may be also where I can find them as I'm not really an expert on Linux :-)

VG Manfred

**Comment by windkh** [comment]
Hm wieso kommt beim start der Fehler dass der port 1880 in Benutzung ist? Läuft da noch eine andere node-red instanz?

**Comment by windkh** [comment]
Btw, die Unterschiede zwischen den beiden Versionen sind wirklich einfach. Ich kann mal schauen ob da was verdächtiges sein kann...

**Comment by manri-CNC** [comment]
Hallo, sorry der Fehler sitzt wie immer vor dem PC ich hatte wohl node red zweimal auf dem Server gestartet. Einmal im terminal und einmal als service. Server neu gestartet und siehe da der Fehler ist verschwunden. Vielen Dank für deine Hilfe meines hausgemachten Problems VG Manfred

**Comment by windkh** [comment]
Ok passt
