### ISSUE TITLE
telegram commands sometimes don't work

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#334]
Hi,
I have a number of commands I do process with the command-node.
Sometimes they get active (and create a result on the connected debug-node), sometimes they don't.

Sometimes all of the don't work, sometimes only some of them don't work.
After some time of wainting, they start working again.

If I change the node, this command then works again where others still don't.

I have for each command a separate command-node!

After updating the configuration node for telegrambot all commands get back working!

Any idea what this could cause?

**Comment by windkh** [comment]
Sounds strange... maybe you must show it to me

**Comment by averlon** [comment]
what do you mean with show me!

There is not very much to show!

I experience at some time, that some commands (or even all commands) don't work anymore. Simply no reply as it was setup in the related flow. Not even a reply from the attached debug-node. So there is simply nothing so !see!.

Once I update the telegram configuration node of the related bot, all works again!

I also experience, if I wait for some time - the period is different - it also comes back to working. But this might be some accidential case - since I did not verify this in the way of a logbook.

So, there is nothing to !show!, except you tell me what you want to !see!.

**Comment by windkh** [comment]
Well, all I can tell you is that I have bots running for months and years without having ever discovered what you describe. Hence I ask myself: where is the difference in your setup?
We can arrange a teams meeting where you can show me your configuration

**Comment by averlon** [comment]
Very welcome. I am busy for an hour but will come back then!

**Comment by windkh** [comment]
I am at work... maybe in the afternoon

**Comment by averlon** [comment]
what time do you recommend?

**Comment by windkh** [comment]
Sorry today is too late let's try tomorrow

**Comment by averlon** [comment]
The problem seems to be created if I use "deplay only changed flows" (Geänderte Flows).
If I deploy the whole workspace - which I normally don't do - all bot-commands stay active.

"changed flows" my expectation was to be the whole "Flow" - means the TAB I am working in. But it looks like "flow" in this context is really only the flow (workflow with several nodes, but not the whole page(flow)) I made some changes is deployed.

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot#hints

This is a known thing. See link above. So I can close the issue?

**Comment by averlon** [comment]
I am very much sorry I didn't read the HINTS carefully.
Issue can be closed!

**Comment by windkh** [comment]
Kein Problem wenns was gibt einfach melden
