### ISSUE TITLE
what does the control-node tell me

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#335]
I would like to check if connection to the telegram-bot is active.

I have understood, there is the control-node to tell something about this.

Is there an example how to make use of the control-node?

I can install it - but when the connection works, it issues messages. If the connection is lost - what does it do then or how can I find out the connection is lost?

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/control.json

**Comment by averlon** [comment]
I have already seen this.
But what does it tell me!

As I understand I can push in some commands - fine. I assume, I will get a result.

But I also read somewhere that I could control if the internet (connection to the bot) is available.

If I activate the "check network connection" and configure some host on the net, something like "github.com", node red crashes!
I had some trouble to geht node red back working.

So, what does the use of the control-node (without an input of a command) tell me?

**Comment by windkh** [comment]
check network connection tries to reach the host via internet. Usually you would try to reach your telegram server.
After every poll cycle the output can tell you if the network is down or not. Sorry I thought that is self explaining when creating the example...

**Comment by windkh** [comment]
If it crashes, then this is worth an extra issue.
