### ISSUE TITLE
API Changes at telegram

### ISSUE THREAD

**Issue by kolbenhans** [windkh/node-red-contrib-telegrambot#336]
@windkh Seems like API Changes at telegram 18.09.2023 stopped the functionality of the node red pallet.

**Comment by windkh** [comment]
? What happened ?

**Comment by kolbenhans** [comment]
chats are not chats anymore, now you have "supergroup chats" ...whatever that means....
 
issue in node red:
Caught exception in sender node:
Error: ETELEGRAM: 400 Bad Request: group chat was upgraded to a supergroup chat
when processing message: 
{"_msgid":"c85e50c3d353a782","payload":{"chatId":-<myid>,"type":"message","content":"my text","options":{"chat_id":<myChatID>,"text":"my text"}},"topic":"aaaa","_event":"node:d0039967c9a81489"}

**Comment by windkh** [comment]
Oups! Was there an official announcement?

**Comment by kolbenhans** [comment]
got this link this morning (https://core.telegram.org/bots/api) and  got the issue above since today.



Also there is the option to activate "Topics" in channels now. (at least i havn't seen that before)

**Comment by windkh** [comment]
I am working with my old groups without issues. I can not reproduce that problem. Sorry.
