### ISSUE TITLE
examples/basiccustomkeyboard.json läuft nicht

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#337]
Hallo,
bitte mal das Beispiel examples/basiccustomkeyboard.json prüfen.
Ich bekomme Fehler:
```
Caught exception in sender node:
Error: ETELEGRAM: 400 Bad Request: inline keyboard expected
when processing message: 
{"_msgid":"7cbd8ff5c7986912","payload":{"content":"Selection?","options":{"reply_markup":"{\"keyboard\":[[\"A1\"],[\"A2\"]],\"resize_keyboard\":true,\"one_time_keyboard\":true}","chat_id":-1001509670149,"text":"Selection?"},"chatId":xxx,"messageId":99,"sentMessageId":99,"type":"message"},"error":false}
``` 

Ich habe
```
node-red 3.1.0
node-red-contrib-telegrambot 15.1.6
node.js 14.16.0
``` 

Ich habe das mit dem original Beispiel probiert und das dann aber auch noch einmal in einen change-node portiert. Mit JAVASCRIPT bin ich nicht so firm.
```
[
    {
        "id": "2cebda8cf198719a",
        "type": "change",
        "z": "33667947.7eff86",
        "name": "CustomButton",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{}",
                "tot": "json"
            },
            {
                "t": "set",
                "p": "payload.type",
                "pt": "msg",
                "to": "message",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload.chatId",
                "pt": "msg",
                "to": "xxx",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload.content",
                "pt": "msg",
                "to": "Selections?",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload.options.reply_markup",
                "pt": "msg",
                "to": "$string(\t   {\t       \"keyboard\":[[\"Yes\",\"No\"]],\t       \"resize_keyboard\":true,\t       \"one_time_keyboard\":true\t   }\t)",
                "tot": "jsonata"
            },
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 300,
        "y": 2340,
        "wires": [
            [
                "60218a44b83f18ac",
                "6714a738e84a504d"
            ]
        ]
    }
]
```

**Comment by windkh** [comment]
will check it

**Comment by averlon** [comment]
found the error!
I only can send the custom keyboard with my own users chat-id. Not to any chat!
Inline Keyboards can obvieously be sent to any chat-id!

**Comment by averlon** [comment]
ich habe gesehen, dass es doch ein Beispiel gibt, wo ein Custom Keyboard an einen Chat geschickt wird.
examples/sendkeyboardtochat.json
Das läuft bei mir auf Fehler.

```
Caught exception in sender node:
Error: ETELEGRAM: 400 Bad Request: inline keyboard expected
when processing message: 
{"_msgid":"3fd483c97a684e56","payload":{"chatId":xxx,"type":"message","content":"Really?","options":{"reply_to_message_id":0,"reply_markup":"{\"keyboard\":[[\"Yes\"],[\"No\"]],\"resize_keyboard\":true,\"one_time_keyboard\":true}","chat_id":xxx,"text":"Really?"}},"topic":""}
``` 

Wie oben geschrieben, wenn ich als chat-id den des bot angebe, dann geht es!

**Comment by windkh** [comment]
@averlon In allen Beispielen muss man die chatId selber setzen, und zwar auf den chat in dem das kayboard aufgehen soll. Das kann eine group sein, ein privater chat (vor deinem account zum Beispiel) o.ä. Was keinen Sinn macht ist die chatId des bot selbs anzugeben. was soll der bot sich selbst ein keyboard schicken?

**Comment by averlon** [comment]
Wenn ich das richtig verstanden habe, dann wird das doch in irgendeinem Chat mit "@botname" gestartet - oder?
Bei mir funktionieren die Beispiele nur, wenn ich die Chat-ID von dem Account angebe, der "@botname" geschrieben hat.
Wenn ich eine Chat-ID von einem beliegibt Chat angebe wo das Menü erscheinen soll, dann kommt der Fehler.
Das Menü erscheint immer dort wo der User das "@botname" eingegeben hat. Die Chat-ID muss aber die des Users selbst sein.

Vielleicht drücke ich mich kompliziert aus. Ich habe es mit einem Inline Keyboard hinbekommen. Mit einem Custom Keyboard bisher noch nicht.
