### ISSUE TITLE
answerCallbackQuery without alert

### ISSUE THREAD

**Issue by YuriiMaiboroda** [windkh/node-red-contrib-telegrambot#339]
In [documentation of Telegram](https://core.telegram.org/bots/api#answercallbackquery), it is written that if you call `answerCallbackQuery` with empty `text`, then Telegram will not show any alert to the user.
This can be used so that Telegram stops highlighting the inline keyboard button when you need to respond not with an alert, but with a new message.

But now, if I specify empty `content`, the message is not sent, instead, a warning is written in the log: `"msg.payload.content is empty"`.

I believe that `answerCallbackQuery` does not need to check for empty content.

**Comment by windkh** [comment]
Thanks for reporting. I will check this.

**Comment by windkh** [comment]
@YuriiMaiboroda can you try it out in the next version?

**Comment by YuriiMaiboroda** [comment]
The [node page](https://flows.nodered.org/node/node-red-contrib-telegrambot) in node-red is still the previous version. Do you know how often the data is updated there?

**Comment by YuriiMaiboroda** [comment]
Updated manually via npm.
Now it works. It works both in the case when the content is an empty string, and in the case when the content is removed

Thank you.
