### ISSUE TITLE
inline_keyboard dynamic

### ISSUE THREAD

**Issue by kuradi** [windkh/node-red-contrib-telegrambot#350]
its not an issue, more like a cry for help :)

is there any way to make inline_keyboard dynamic, sort of

if a=b
show {"text": "Yes","callback_data": "FOO YES"}
if a=c
{"text": "No","callback_data": "FOO NO"}]

?

**Comment by windkh** [comment]
I would put that code in a function node

**Comment by kuradi** [comment]
> I would put that code in a function node

do you have any working example?

**Comment by windkh** [comment]
No, but you can also use a switch  node
https://flowfuse.com/node-red/core-nodes/switch/
