### ISSUE TITLE
setChatAdministratorCustomTitle

### ISSUE THREAD

**Issue by ptath** [windkh/node-red-contrib-telegrambot#351]
Please implement this [API](https://core.telegram.org/bots/api#setchatadministratorcustomtitle)

**Comment by windkh** [comment]
As soon as I find some time

**Comment by ptath** [comment]
thanks

literally one string https://github.com/windkh/node-red-contrib-telegrambot/pull/352

tested, works

**Comment by windkh** [comment]
thanks alot, will add you to the credits list
