### ISSUE TITLE
Event Node - Callback Query behaviour

### ISSUE THREAD

**Issue by pke3** [windkh/node-red-contrib-telegrambot#355]
I'm trying to use in 2 different flow the event node with the callback query option, is it normal that only 1 of the 2 receive the callback ?

**Comment by windkh** [comment]
Hm.. I would expect that both would receive the same event. However I will better try to reproduce it

**Comment by pke3** [comment]
Right now I've only one event node configured with the callback query in one flow, not the best option..but i do not have any other way.

btw, if I put 2 event node in the same flow it's works , every node receive the event.

**Comment by pke3** [comment]
Maybe I found the solution , it is related to the "Deploy" option in node red ... If I click on "Modified Flows" I have the issue , instead if I trigger the Full option everything works as expect.

**Comment by windkh** [comment]
@pke3 Yes this is mentioned in the readme. You always need to do full depoly

**Comment by windkh** [comment]
Can I close this issue then?

**Comment by pke3** [comment]
Yes ofc and sorry but I miss that specific detail.

Ciao!

**Comment by windkh** [comment]
ok nice
