### ISSUE TITLE
stuck with ReplyParameters

### ISSUE THREAD

**Issue by ptath** [windkh/node-red-contrib-telegrambot#359]
> Added the class [ReplyParameters](https://core.telegram.org/bots/api#replyparameters) and replaced parameters reply_to_message_id

so trying to

```
var opts = {
    parse_mode: 'Markdown',
    disable_notification: false,
    reply_parameters: {
        "message_id": messageId
    }
};

newpayload.type = "message";
newpayload.chatId = chatId;
newpayload.options = opts;
```

and it doesn't works, receiving only clean message, no errors

any ideas?

**Comment by windkh** [comment]
@ptath first of all I do not understand what you want to achieve?
You want to reply to an existing message in a chat?

If yes:
What does not work? What do you mean with clean message, no errors?

**Comment by ptath** [comment]
> @ptath first of all I do not understand what you want to achieve? You want to reply to an existing message in a chat?

yes

> If yes: What does not work? What do you mean with clean message, no errors?

It sends simple message, without reply mark. No errors in debug node.

**Comment by windkh** [comment]
@ptath 
There is an example: 
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/replytomessage.json

Did you already try that?

**Comment by windkh** [comment]
@ptath you refer to Bot API 7.0 which was released at the end of december:
https://core.telegram.org/bots/api#december-29-2023

This is not supported yet.
