### ISSUE TITLE
Errors on update and some malfunctions

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#361]
Hi mate, I'm posting here trying to help you improving, the module works and there is no requests to fix it, just let you now what is happening here. I have a RB3b with Linux 5.10.48, node v14.21.2, npm 6.14.17, NR 3.0.2

The node stopped to receive messages, so as first I updated it from 15.1.17 to 15.1.19, it took a while and have different errors, after complete I restarted NR and now it receive fine. All is ok?
Also, I still have no chance to use the button function, sorry I don't remember the name of this feature, it's about prompting a question on the Telegram app on my phne and give buttons to answer. I see this buttons coming without prompting anything, and persist even if I press them, qthe qyery still pending and I can't exit from it. I was reporting this problem alrteady 2 years ago.
Maybe something corrupt on my files so the module behaving bad for this reason? 

https://pastebin.com/iEmA9NsE

**Comment by windkh** [comment]
@Barabba11  what did you change before that problem occured?

**Comment by Barabba11** [comment]
As I remember the problema is old, I don't use so much the receiving node so I can't tell, but I could say it worked from long periods, now with recent versions of node seams it stops receiving after some hours. Yesterday I restarted, today it doesn't receive. On flow nothing I changes, as well as NR version, nodes and so on. I still have the problem with the keyboard:
Do you think it's possibile I have some dirty staff into this node files/config? can it worth to clean it and reinstall? Do you see something wrong into the log when I updated?
Thanks

**Comment by windkh** [comment]
please try with new version 16.0.0
