### ISSUE TITLE
Sending Photos - payload.type is empty error

### ISSUE THREAD

**Issue by MatterSec** [windkh/node-red-contrib-telegrambot#363]
Currently unable to get Telegram Sender to send a photo. I have a function with it's content below, but the telegram sender is displaying an error of "msg.payload.type is empty".  Currently unable to figure out where this error is coming from as the payload.type is there and double checked..  

The .jpg in the URL path works when browsing and tried without the IP and just /www/...

Thanks

![image](https://github.com/windkh/node-red-contrib-telegrambot/assets/58089028/21dfece1-f6ca-4e3d-965b-9cfc1768f8e0)

**Function:**
msg.payload.content = 'http://<HA-IP>/local/notifications/doorbellpress.jpg';
msg.payload.type = 'photo';
msg.payload.caption = "Someone is at the front door"
return msg;

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/sendphoto.json
