### ISSUE TITLE
Unhandled rejection RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Bobo-amg** [windkh/node-red-contrib-telegrambot#372]
Occasionally I am seeing the above error in the console. I tracked it back to an issue (somewhere) with Telegram. All my telegram nodes switch from Connected to Polling after the event. I'm not sure how long they stay in the Polling mode for?

Just wondering if anyone had seen this before? Possibly a problem on the Telegram end, with intermittent timeouts with their servers/connections?

Cheers
Bob

**Comment by windkh** [comment]
Hm do you have a log file or a screenshot of that error?

**Comment by Bobo-amg** [comment]
Unfortunately I didn't keep the whole error message, mainly because I thought it was comms issue at the Telegram end, but just wanted to see if anyone could confirm this.

It hasn't happened since, so I'm happy to close for now.
