### ISSUE TITLE
Problems with commands

### ISSUE THREAD

**Issue by nusserer** [windkh/node-red-contrib-telegrambot#375]
Hello,

I have problems with the command nodes. I have 3 commands in 3 flows and a central Telegram sender. Unfortunately after some time only 1 command is received. If I save the config of the bot again, all 3 commands work. After a certain time, only one works again.  I have registered the commands on the server.

**Comment by windkh** [comment]
Hm strange. How long does it usually take until the error occurs?

**Comment by nusserer** [comment]
between 5 minutes and several hours. It varies greatly.
It then says “Polling” under all Telegram nodes. If I send all 3 commands via telegram, it changes to “connected” for one and this command works. The other two remain “polling”.

**Comment by windkh** [comment]
Ah you create three nodes with the same command e.g. /foo

Is that correct?

**Comment by nusserer** [comment]
no, 3 different commands

**Comment by windkh** [comment]
hm... can you provide the flow or as an alternative we have a teams meeting where you can show me that

**Comment by nusserer** [comment]
[flows.json](https://github.com/windkh/node-red-contrib-telegrambot/files/15386935/flows.json)
Here is my flow. The Telegram nodes are under “Fenster”, “Lüfter” and “Shelly”

**Comment by nusserer** [comment]
ohh, that could be the problem. Thank you! I will watch it again
