### ISSUE TITLE
Unable to install the most updated version

### ISSUE THREAD

**Issue by yychu2** [windkh/node-red-contrib-telegrambot#379]
Hi, I'm downloading the node-red-contrib-telegrambot, but the installation keeps fail.
Here is the error in log, may I know how can I fix this? Thank you.

2024-05-30T06:39:03.763Z [err] config
2024-05-30T06:39:03.764Z [err]  production Use `--omit=dev` instead.

**Comment by windkh** [comment]
no idea

**Comment by windkh** [comment]
what version of node red do you have? npm and nodejs version?

**Comment by windkh** [comment]
please try with new version 16.0.0
