### ISSUE TITLE
Telegram getFile Method - Only Thumbnail picture File-id from Telegram Receiver

### ISSUE THREAD

**Issue by hanneshoettinger** [windkh/node-red-contrib-telegrambot#38]
Hey,

thanks for the work, it really helped me setting up a bot as fast as possible.

I am trying to get a sent Photo from the user. This works by using the file-id, however, from the telegram receiver node I do only get one file-id which corresponds to the thumbnail. I would like to download the full-res photo from telegram like described here: https://stackoverflow.com/questions/38106191/how-to-get-photo-in-real-size-not-thumb-from-telegram

Is there a possibility to update the receiver node, if a photo message is incoming, to return multiple file-ids for the corresponding resolutions?

Thanks a lot
Hannes

**Comment by windkh** [comment]
Maybe you can try to send it as document.

**Comment by hanneshoettinger** [comment]
thanks for the fast response, will try it, thx!
but in the code I see the line: botMsg.photo[0].file_id -> do you access only the first resolution maybe here?

**Comment by windkh** [comment]
I don't have it in mind, but I will have a look at it.

**Comment by windkh** [comment]
Well, there are several possibilities:
- add a fileIds array property to the message payload
- only add the fileId of the image with the highest resultion

Should I download all resolutions to the local harddisc or only one?
(BTW: Note that the message also contains the original message that contains the photo array.)

**Comment by hanneshoettinger** [comment]
Hey,

first of all, thanks for the idea with the document, that worked great, but of course having the possibility to grab the image when sent as photo would be the ideal solution.

I think it would be best to make it work like in the Stackoverflow post:
[{
    "file_id":"AgADBAADxxxx",
    "file_size":19374,
    "width":253,
    "height":320
},{
    "file_id":"AgADBAACxxxx",
    "file_size":75657,
    "width":632,
    "height":800
}]

return an array of the different images, so it is possible to check in Node-Red which image to download...what do you think?

**Comment by dvv** [comment]
I'd leave array in original message and the last array element as payload. The latter is downloaded automatically (if said so), the former processed by user on per-application basis.

**Comment by dvv** [comment]
@windkh \o/
I believe we should expose _the last_ array element as the best quality one (I presume)

**Comment by windkh** [comment]
I already finished the code for it

**Comment by windkh** [comment]
version 2.9.1 puts the photo with the highest resolution into the message.
An additional property photos in put into the message payload so that the flow can also have access to those.
