### ISSUE TITLE
Cannot set up server URL to official telegram's test environment

### ISSUE THREAD

**Issue by TwilightOwl** [windkh/node-red-contrib-telegrambot#380]
For Telegram Mini App development I have to use telegram test development described here https://core.telegram.org/bots/features#creating-a-bot-in-the-test-environment

But I can't set up sever URL in your component to be like this https://api.telegram.org/bot<token>/test/METHOD_NAME

Is it possible? I didn't find anything in readme and issues about telegram's test environment.

**Comment by windkh** [comment]
@TwilightOwl 
right now it is not but I can add this if you want. Should be not a big deal to add this ....

If you set up your own telegram server at home for testing then you can change the url in the bot config
from https://api.telegram.org to your own one. This is already possible today.

**Comment by TwilightOwl** [comment]
It would be great if your component can connect to telegram's test environment. Mini App requires public URL with SSL and telegram's test environment allows you to use http and localhost\IP for Mini App development. Thank you for your great package!
