### ISSUE TITLE
Iphone, inline menu working just one time.

### ISSUE THREAD

**Issue by TagorePde** [windkh/node-red-contrib-telegrambot#383]
Hi, thanks for this module for node red, is great.

I'm having the issue on Iphones, using the bot under a channel group, the menu jst work one time, i have to recreate the inline keyboard using a /command to fire the menu again, so i can use again.

```javascript
var opts = {
  reply_markup: JSON.stringify({
    keyboard: [
      ['EDFA PDE ESTADO'],
      ['APAGAR PDE','PRENDER PDE'],
      ['EDFA Maldonado ESTADO'],
      ['APAGAR MLD', 'PRENDER MLD'],
      ['PING - El robot esta vivo?']],
      'resize_keyboard' : false,
      'one_time_keyboard' : false,
      'is_persistent' : true,
      'remove_keyboard' : false,     
  })
};


msg.error = false;
msg.payload.content = 'Selection?';
msg.payload.options = opts;


msg.payload.chatId = -1234567890;
msg.payload.messageId = 99;
msg.payload.sentMessageId = 99;
msg.payload.type = "message";

return [ msg ];
```

just happen only in iphone, under android is working as intended.
i m doing something worng? or is working as expected?
Regards.

**Comment by windkh** [comment]
@TagorePde 
Hm never tried that, just one short question:
msg.payload.chatId = -1234567890;
msg.payload.messageId = 99;
msg.payload.sentMessageId = 99;

Do you update these IDs or do you always send 99?

**Comment by TagorePde** [comment]
No, i dont update, i need to update?
Regards.

**Comment by windkh** [comment]
@TagorePde can you send me a complete flow so that I can reproduce it?

**Comment by windkh** [comment]
closed du to no response
