### ISSUE TITLE
Inline Keyboard show_alert appears to be broken?

### ISSUE THREAD

**Issue by Bobo-amg** [windkh/node-red-contrib-telegrambot#384]
I'm having trouble using the show_alert option when editing an inline keyboard. Regardless of either true/false, the dialog answer still appears in the client.

This is shown when using your "examples/editinlinekeyboard.json" example. Along with this is an error message relating to msg.payload.content.text with the following error message "TypeError: Cannot create property 'text' on boolean 'false'"

Cheers
Bob

**Comment by windkh** [comment]
Thanks for reporting. I guess the callback_query message was somehow changed by telegram in the passt.
I adapted the example

**Comment by Bobo-amg** [comment]
Thanks, the error is fixed. However I'm still not seeing a difference using show_alert in your example. True or False, the reply still gets returned to the client (ie FOO NO).

**Comment by windkh** [comment]
That depends on your client app. On my desktop telegram program a popup shows up in the middle of the screen with the text in it.

**Comment by Bobo-amg** [comment]
But shouldn't you be able to turn off ALL replies from the bot using show_alert? I thought that is what its for.

**Comment by windkh** [comment]
Well, please read the offcial documentation about show_alert. The behaviour is all up to telegram
