### ISSUE TITLE
Custom baseApiUrl for underlying bot

### ISSUE THREAD

**Issue by dvv** [windkh/node-red-contrib-telegrambot#39]
I'd like to have https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L173 configured. The rationale is to allow for VPN, proxy, etc.
Wonder if you could expose it via either a html edit or environment variable or whatever.
TIA

**Comment by windkh** [comment]
We can integrate this, but I guess that I didn‘t got the use case for this right now.... I will have a look at it. Wanted to test with the latest nodered version anyway, so I could check this out on the fly.

**Comment by dvv** [comment]
E.g. if `TCP api.telegram.org port 443` is blocked, there is no way to work around.

**Comment by windkh** [comment]
2.9.0 support baseApiUrls now
