### ISSUE TITLE
exampleflows/example use first_name instead of username

### ISSUE THREAD

**Issue by aniston** [windkh/node-red-contrib-telegrambot#4]
First thanks for sharing your work !

i noticed that you used the tag 'username' in your example flows, which will often result in "Undefined" if no Username is set, I find it better to use 'first_name' and you will alwalys get a response, except for Bots talking to Bots.

eg:
helpMessage += "You are welcome: "+msg.originalMessage.from.first_name;

**Comment by windkh** [comment]
Hi, I thought username is always a valid string. Under which circumstances did you discover this value being "undefined"?
I could introduce a new value username in msg (to avoid taking values from the originalMessage) and make sure that this one is always valid.

**Comment by windkh** [comment]
not reproducable
