### ISSUE TITLE
Way rigid condition on msg.payload.content in sender

### ISSUE THREAD

**Issue by dvv** [windkh/node-red-contrib-telegrambot#40]
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/telegrambot/99-telegrambot.js#L458 does require truthy `msg.payload.content` while it's not required for at least `deleteMessage` and https://github.com/windkh/node-red-contrib-telegrambot/blob/master/telegrambot/99-telegrambot.js#L505.
Am I right?

**Comment by windkh** [comment]
Yes indeed...

**Comment by windkh** [comment]
fixed in 2.8.2
