### ISSUE TITLE
Configurable auto-answer on callbackQuery

### ISSUE THREAD

**Issue by dvv** [windkh/node-red-contrib-telegrambot#41]
For discussion:

Do we want to auto-answer to callback_query message to fulfil requirement in "Note" for https://core.telegram.org/bots/api#callbackquery?

For this it's sufficient to append
```
node.telegramBot.answerCallbackQuery(botMsg.id);
```
below https://github.com/windkh/node-red-contrib-telegrambot/blob/master/telegrambot/99-telegrambot.js#L394

**Comment by windkh** [comment]
Hm should that be configurable for the node itself or a global setting?

**Comment by dvv** [comment]
I'd vote pro node

**Comment by windkh** [comment]
Ok

**Comment by windkh** [comment]
version 2.9.2 contains the feature: Auto-Answer option is now available in the callback query node

**Comment by dvv** [comment]
\o/
