### ISSUE TITLE
key lost each restart

### ISSUE THREAD

**Issue by davidcgu** [windkh/node-red-contrib-telegrambot#47]
Good afternoon

I'm using latest version and every time y restart node red service or restart the raspberry pi 3 I have to go to config on node red and enter again the key, the user oof the boot is still there but the key appears blank.

Any advice?

Thanks in advance

**Comment by windkh** [comment]
Hm maybe you should have a look into the configuration nodes on the right sidebar. Ate there more than one nodes with the same name?
Well nevertheless it should work for you without having to enter the token every time.
What version are you using? The latest one 4.x or a 3.x?

**Comment by windkh** [comment]
Hi @davidcgu 
I played around with this on my local laptop and the token is saved correctly into the credentials file.
Maybe your pi has a problem with encrypting this. So you should find out if the credentials file is written to our disc.
see also 
https://github.com/node-red/node-red/wiki/Design%3A-Encryption-of-credentials
https://nodered.org/docs/creating-nodes/credentials

What node and node-red version are you using?

**Comment by davidcgu** [comment]
Thanks Wind, just get it solved, was an issue with the config.json configuration that was forcing me to reload the credetials every restart.

Thanks again for your interest, much apreciated

**Comment by windkh** [comment]
ok fine! bye!
