### ISSUE TITLE
'get reply'-node not working

### ISSUE THREAD

**Issue by baaswietse** [windkh/node-red-contrib-telegrambot#48]
When trying the onreplymessage, after answering to the question, the 'get reply'-node doesn't output anything.

Anyone knows this issue?

**Comment by windkh** [comment]
Did you test one of the examples? Or did you create your own flow?

**Comment by baaswietse** [comment]
I tried this example: [](https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/onreplymessage.json)
Just used my own bot, but all other nodes are working fine with my bot.

**Comment by windkh** [comment]
Please paste your flow here and I will have a look at it.... as soon as I find some time

**Comment by baaswietse** [comment]
[{"id":"5e882073.2e31b","type":"function","z":"336f4c0f.c3cd14","name":"create question","func":"msg.payload.type = 'message';\nmsg.payload.content = 'Really?';\nmsg.payload.options = {reply_to_message_id : msg.payload.messageId}\nreturn [ msg ];\n","outputs":"1","noerr":0,"x":320,"y":680,"wires":[["35fcc8b5.54fed8"]]},{"id":"2f780360.280acc","type":"telegram command","z":"336f4c0f.c3cd14","name":"/foo","command":"/foo","bot":"7767b2fd.13743c","x":148,"y":686,"wires":[["5e882073.2e31b"],[]]},{"id":"35fcc8b5.54fed8","type":"telegram sender","z":"336f4c0f.c3cd14","name":"send question","bot":"7767b2fd.13743c","x":510,"y":680,"wires":[["6dfe1631.d384a8"]]},{"id":"6dfe1631.d384a8","type":"telegram reply","z":"336f4c0f.c3cd14","name":"get reply","bot":"7767b2fd.13743c","x":705,"y":680,"wires":[["7c3b7775.7b7c18","c856a423.3e3708"]]},{"id":"7c3b7775.7b7c18","type":"function","z":"336f4c0f.c3cd14","name":"switch answer","func":"if(msg.payload.content === 'Yes')\n{\n    return [msg, null];   \n}\nelse\n{\n    return [null, msg];   \n}\n","outputs":"2","noerr":0,"x":877,"y":680,"wires":[["f49f003a.c0a0d"],["a00df23.e6eff1"]]},{"id":"f49f003a.c0a0d","type":"debug","z":"336f4c0f.c3cd14","name":"Yes","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":1079,"y":664,"wires":[]},{"id":"a00df23.e6eff1","type":"debug","z":"336f4c0f.c3cd14","name":"No","active":true,"console":"false","complete":"payload","x":1079,"y":711,"wires":[]},{"id":"c856a423.3e3708","type":"debug","z":"336f4c0f.c3cd14","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":820,"y":520,"wires":[]},{"id":"7767b2fd.13743c","type":"telegram bot","z":"","botname":"baaswietse_bot","usernames":"","chatids":"","baseapiurl":"","pollinterval":"300"}]

here you go sir.

**Comment by windkh** [comment]
The example works, but maybe you did a common mistake:
When the question shows up in your client. Then you should not just enter a new message in the next line, but respond to the one the bot sent to you. This depends on the client you use, but try to click on the message of the bot and select "respond" or "answer" or something like that. In this case your response message contains the id of the original one that was previously sent by the bot... and then everything should work.
