### ISSUE TITLE
Bot ignoring messages from other bots

### ISSUE THREAD

**Issue by Delivator** [windkh/node-red-contrib-telegrambot#49]
My current setup is that I have the IFTTT bot and my Node-RED bot in a group.
When I trigger a applet in IFTTT the IFTTT bot sends a message in the group.
My Node-RED flow is configured that whenever the bot recives a message it prints the message in the debugger, which works perfectly when I send a message in the group, but not when the IFTTT bot sends a message in the group.

(How) Can I fix that?
If not, is there a workaround?

**Comment by Delivator** [comment]
https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

So there is that answer.

Is there a known workaround?

**Comment by windkh** [comment]
Hm ... that sounds strange. I wonder how I can reproduce that scenario. Did you configure your bot to receive everything from a group via /serprivacy?

**Comment by Delivator** [comment]
Yeah privacy is disabled, but the Telegram FAQ says that bots only recive messages from non-bot-users :(
So my next question is if there is a workaround.

**Comment by windkh** [comment]
Oh I did not know of that limitation. As this is not allowed by the telegram server there is nothing I can do from the client side

**Comment by ozett** [comment]
very old, but still helpful information. thanks

![image](https://user-images.githubusercontent.com/5937811/155340118-87bc72f0-bcbb-4621-a1c1-9b842e8907b4.png)
