### ISSUE TITLE
create help text - code not up-to-date

### ISSUE THREAD

**Issue by 1302580MK** [windkh/node-red-contrib-telegrambot#52]
Concerning: TelegramBotHelp2.png

the old version is: 
+ msg.originalMessage.from.username;

this is not working anymore.

the right line of code should be:
+ msg.originalMessage.from.first_name;
+ adding "\r\n" for a nicer output.

I would fix it myself - but can't edit the readme

**Comment by windkh** [comment]
Thanks for reporting this, I will update this.

**Comment by windkh** [comment]
I had a look at the bot example and in my eyes it provides the correct output.
The username is always valid while the first_name is optional and can be empty on my machine.

Anyway it is only an example....
