### ISSUE TITLE
Bot requires an extra space at the end of the command when in groups

### ISSUE THREAD

**Issue by MrMauro** [windkh/node-red-contrib-telegrambot#55]
I have been able to get a response from a bot when issuing a /command when having a "direct chat" with it.

However, doing the very same on a group where that bot is a participant (even with privacy on/off) it won't yield any result. Still, I have confirmed with an echo response that the bot is receiving the message.

I've noted that if an extra space is appended at the end of the command (ie: "/command ") the bot in the group chat will execute the request command.

**Comment by windkh** [comment]
Did you configure the config node in a way that it only accepts commands sent by your id? I am 100% sure that the bot works in chats. Or did you activate the strict mode?
In chats you should write /command@bot ...

The command can have an extra space as some commands require arguments that are separated through spaces.

**Comment by windkh** [comment]
I will try to reproduce the problem, thanks!

**Comment by MrMauro** [comment]
Hi!
Thank you for your prompt response. 

I have checked that I haven't set any list of authorized Users/ChatsIDs, also that I write the command in the form:  /command@bot in the chats... and I have tried setting the strict mode on and off.

This is what I have done so far after I posted this Issue:

- I have created two more bots and used them in the same Flow in Node Red. Those worked perfectly without requiring that extra space.
- I have double checked the configuration of the "Offending Bot" comparing its settings to the ones of the newly created bots. I did the same for their Group Chats to check for any discrepancies.
- I revoked and got a new Api Key for the Offending Bot.
- As neither of those things worked I deleted the Bot, created a new one with the same name of the original and replaced its Key on the previous Flows....And it didn't worked.

I'm doubting this is something related to your code, as the only things different here are the bot names and their api keys...

I appreciate your help. And by the way, thank you for the code. It's really nice.

**Comment by windkh** [comment]
Can you export the flow and send it to me?

Gesendet mit der WEB.DE iPad App

Am 10.10.18 um 01:07 schrieb Mauricio Vidal

**Comment by windkh** [comment]
The flow contained a configuration node where the name of the bot did not match the token: 
--> problem solved.

**Comment by tjunussov** [comment]
I Have same abnormal behaviour, my command never executed, if I check  `Strict in group chats`, and sending via group to bot

My debug message looks like this

```
chatId: -378814751
messageId: 2462
type: "message"
content: "/register@ConnectedBot"
date: 1606503482
```

**Comment by windkh** [comment]
I will check

**Comment by tjunussov** [comment]
Thnx, I have some more info, I think it is due to lack of examples in manual
**Command Node**
1) command must start with /help - with slash, and it will work only in Personal Chats, not group chats; Ex: /help 
2) if you willing to use commands inside group chats, you need to specify full length command ( it is command @ botUserName )  Ex: /help@mybot
3) if check `Strict in group chats` it will filter only groups ? if so why need this ?

**Comment by windkh** [comment]
@tjunussov 
thanks for your improvements.

Well about 3:
If you would have two bots in a chat group both implementing /help you would trigger both bots if not using strict. If there would only be one bot in a group the strict mode is annoying because you would have to type more

**Comment by windkh** [comment]
I can not reproduce that problem. Can you send me a flow?
