### ISSUE TITLE
Authorized users

### ISSUE THREAD

**Issue by markpeo** [windkh/node-red-contrib-telegrambot#57]
Hi,

I have noticed that if I remover a user form the authorized user field that user still stays as authorized.
Is there a way to purge the previously authorized users?

Using v 4.4.0 of the package and am running v0.19.5 of node-red using offical docker.

**Comment by markpeo** [comment]
Apologies, I realised my mistake. I did not realsie that when the username or chatid fields are blank, it defaults to everybody being authorized.
Sorry about that, is working as it should.

**Comment by windkh** [comment]
ok!
