### ISSUE TITLE
Telegrambot produces thousands of getaddrinfo errors when not connected to internet

### ISSUE THREAD

**Issue by sdavidst** [windkh/node-red-contrib-telegrambot#58]
When I disconnect the internet to my raspberry Pi my daemon.log file grows to hundreds of MB with every second a lot of errors:

Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:07 raspberrypi Node-RED[14614]: 9 Dec 06:25:07 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
Dec  9 06:25:08 raspberrypi Node-RED[14614]: 9 Dec 06:25:08 - [warn] [telegram bot:8c5c442.f8391b8] Unknown error. Trying again.

[daemon-error-log.txt](https://github.com/windkh/node-red-contrib-telegrambot/files/2665171/daemon-error-log.txt)

**Comment by windkh** [comment]
Hm ... what do you suggest? Stop polling for an upcoming internet connection?
Removing the log line?
Any suggestions?

**Comment by sdavidst** [comment]
Hm, have to think about that....
Maybe polling less frequent ? 
Or polling less on the DNS lookup?
It is just that I have the node-red machine running 24 hours a day and only have mobile internet sometimes so my log grows out of control. For me it would help removing log lines, but other people might find it useful..
Thanks for responding so fast!!

**Comment by windkh** [comment]
I guess it will be best if this is configurable. You could turn off logging and others can still see what is going on. The node will turn red anyway when the connection is lost. 
I will implement this the next days... stay tuned

**Comment by sdavidst** [comment]
Thank you again for responding.

I managed to find out that the logging to the daemon.log ( I run node-red as a system service) is configurable in the settings.js file in the node-red directory.
I changed the logging level from "warn" to "error".
Now the warnings are not shown anymore and the size of the log stays normal.
 
The bottom part of the settings.js file look like this: 
` // Configure the logging output
    logging: {
        // Only console logging is currently supported
        console: {
            // Level of logging to be recorded. Options are:
            // fatal - only those errors which make the application unusable should be recorded
            // error - record errors which are deemed fatal for a particular request + fatal errors
            // warn - record problems which are non fatal + errors + fatal errors
            // info - record information about the general running of the application + warn + error + fatal errors
            // debug - record information which is more verbose than info + info + warn + error + fatal errors
            // trace - record very detailed logging + debug + info + warn + error + fatal errors
            // off - turn off all logging (doesn't affect metrics or audit)
            level: "error",
            // Whether or not to include metric events in the log output
            metrics: false,
            // Whether or not to include audit events in the log output
            audit: false
`

I am curious about your solution as well.
Thanks again.

**Comment by windkh** [comment]
fixed in 4.4.2
The configuration node now has a "Verbose Logging" flag which is false by default.

**Comment by sdavidst** [comment]
great work!
I want to test it but I am still trying to find the proper way to update.
Thank you so much!
