### ISSUE TITLE
no message arrvies

### ISSUE THREAD

**Issue by wuppergit** [windkh/node-red-contrib-telegrambot#59]
There are no incomming messanges at the receive node. The node says that he is connected.  There are no outouts at the node-red console.
What am I doing wrong? Do you need more information (NR V = 19.5)
Thanks

**Comment by windkh** [comment]
Please send me the flow. Make sure that the config node is configured properly. Connect an extra debug node to every of both outputs

**Comment by windkh** [comment]
What version of the lib do you use?

**Comment by windkh** [comment]
Connect a sender node directly to the receiver and check if the bot echoes to the initiating chat

**Comment by wuppergit** [comment]
telegram-bot is 4.4.2; there is no debug output after deploy

**Comment by wuppergit** [comment]
I've fixed it. Thx

**Comment by windkh** [comment]
What was the problem?

**Comment by Barabba11** [comment]
@wuppergit I have the sampe problem, it would be lovely to know how you did fix it..
