### ISSUE TITLE
Wrong required fields when in poll mode

### ISSUE THREAD

**Issue by xoseperez** [windkh/node-red-contrib-telegrambot#61]
The config node complains (but works fine) when deploying if you have not defined the webhook public bot port and local bot port, even if you set the node in poll update mode (which does not require those fields). Setting them to a random number fixed the problem, but still, a nicer solution should be provided.

**Comment by windkh** [comment]
Hi, you are completely right. 
I will make those fields optional in future.
Thanks for reporting this.

**Comment by windkh** [comment]
Fixed in version 5.1.5
