### ISSUE TITLE
How to send text message to username not chatId?

### ISSUE THREAD

**Issue by Osrx** [windkh/node-red-contrib-telegrambot#64]
Hello!

May be I want something strange, but how I can send a message to a User without having previous interactions with him?

Simple message to Username not to ChatId!

**Comment by windkh** [comment]
Hm ... unfortunately there is no lookup funktion available through the telegram bot api to get the user‘s chatId by passing the username. Indeed a user must always contact a bot first triggering /start. Maybe that is by design to avoid spam bots and unwanted messages.
