### ISSUE TITLE
Node-Red only sends Telegram-messages but not receiving

### ISSUE THREAD

**Issue by sdavidst** [windkh/node-red-contrib-telegrambot#65]
Hello again,

After helping me so well the last time I still have some issues with the reliability of the telegram input nodes.
I am running Node-red on a Raspberry Pi which is connected to a public wifi hotspot in my village.
The wifi connection is not always there and I encounter connection problems after some time:

The telegram nodes can sent messages to a bot (triggered by events in node-red) but can't receive any messages from the bot.  If I restart the nodered service everything works fine again.

I don't know how to find out what is going on. At the moment I am trying to work around the problem by creating some sort of watchdog and restart the nodered service if no new messages are detected but I am stuck on automatically sending telegram messages from an external location.

I hope you can shine some light on this. Thank you.
David

**Comment by windkh** [comment]
Hm, that sounds strange. The bot normally polls every 300ms for new messages available on the server. Even when the connection is lost somehow the next poll cycle should fetch the missed messages later on. You can enable verbose logging in the configuration node and you can have a look at the console window for warnings.

**Comment by sdavidst** [comment]
Yes, it is strange. After restarting the nodered service all the old messages suddenly come in..
I will enable verbose logging for a while although it fills up my log with thousands off messages when the wifi connection gets lost. Thanks so far!

**Comment by sdavidst** [comment]
I am sorry to say that I still have this problem and now on more Raspberry Pi's in the same network.
I managed to narrow the problem a bit down:
   The status of the nodes that don't work are "disconnected" in the webinterface, they don't reconnect 
   when the network connection comes back.
   I can have nodes that are connected and disconnected in the same flow (screenshot)
  They are all connected to the same bot . If I restart the node-red service it will work for a while again.
HELP PLEASE!
![nr](https://user-images.githubusercontent.com/28732484/53650137-2522ef80-3c44-11e9-88b7-a252fcbeb8c2.jpg)

**Comment by windkh** [comment]
Do you use the polling mode or the webhook?

**Comment by sdavidst** [comment]
I use polling mode.
I also noticed that the telegram sender nodes on different flows can have
different statuses: on one flow it can be connected and on another it can
have polling error-

>

**Comment by pioioTwo** [comment]
you solved?

**Comment by jara129** [comment]
Pudiste solucionarlo1?
