### ISSUE TITLE
Node registered twice at the configuration node

### ISSUE THREAD

**Issue by douvers** [windkh/node-red-contrib-telegrambot#67]
After using the telegrambot node for many months without any issues I have started getting the following error:

"Node 136c53f8.35a46c registered twice at the configuration node: ignoring."

The issue appears to only be caused by the Telegram Sender nodes. I have five flows which each use a Telegram Sender node. I have deleted each of these nodes in turn and recreated them however I still get the same error for each new node.

I have only recently updated to node-red-contrib-telegrambot 5.3.0 and have jumped a few versions.

Node-RED version: v0.20.2
Node.js version: v10.15.3
Dashboard version: 2.14.0

Can you suggest how I can resolve this issue?

Thanks....

**Comment by windkh** [comment]
Hi @douvers, 
Can you send the flow to me and check if there is only one configuration node that makes use of your bot token?

**Comment by windkh** [comment]
And please check if you do a full deploy or only a partial one

**Comment by windkh** [comment]
I tried to reproduce your problem without any success so far.
BTW the log message is a warning which can be safely ignored. I will probably remove this one in a future upgrade.

**Comment by douvers** [comment]
A couple of weeks ago I started getting duplicate messages from my Telegram bot from the same alert, usually two duplicates but sometimes up to five at the same time. It was then that I noticed the 'registered twice at the config node error'. 

I'm still trying to find the cause of these duplicate messages and I'd like to eliminate the registered twice error as the source of the problem. 

For the last two years of using nodered I have always only performed a deploy of modified flows, never a full. 

![flow](https://user-images.githubusercontent.com/37212207/54885914-a2e9bc00-4ecd-11e9-966c-e9d7a94ac803.jpg)
![node](https://user-images.githubusercontent.com/37212207/54885923-bd239a00-4ecd-11e9-8de3-c55de351894c.jpg)
![config](https://user-images.githubusercontent.com/37212207/54885927-ca408900-4ecd-11e9-81fa-1e6ce83358da.jpg)

[flow.zip](https://github.com/windkh/node-red-contrib-telegrambot/files/3000859/flow.zip)

I'm certain there is only one config node setup with my bot token. 

Thank you.
Max

**Comment by bakman2** [comment]
Note sure if this is related but since I upgraded node to the latest version (v11.12.0) I get:

`ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

**Comment by windkh** [comment]
Check the configuration nodes. Is the same token usef twice?

**Comment by windkh** [comment]
Or is the token used in another process?

**Comment by bakman2** [comment]
I only use it in node red, token only used once. I have removed all nodes, rebooted and added 1 notification node.

**Comment by windkh** [comment]
Can you check if it works with another token?

**Comment by windkh** [comment]
@bakman2 well of course this should not happen. The only thing I can imagine is, as I already pointed out, another running instance using the same bot token. This could also be on another machine if you for example leaked the token to someone else....
Right now I do not have any other explanation for that effect.

**Comment by douvers** [comment]
I still don't know why I was getting the registered twice errors however after a reinstall of raspbian and nodered they have ceased. My alerts from telegram are also not duplicated any more.

**Comment by windkh** [comment]
Maybe some zombie process making use of the token...
