### ISSUE TITLE
Inline Keyboard as sent message

### ISSUE THREAD

**Issue by inputd** [windkh/node-red-contrib-telegrambot#69]
This is a suggestion/request, not a bug report.

I've tried to adapt the example nodes to send a message to a chat ID with an inline keyboard. The idea is for actionable notifications to be sent without being prompted (Entry Delay! [Sound Siren] [Disarm Alarm]).

I've tried to modify the example shown in "Sending messages to a specified chat", as well as combining it with above examples, but while I can get the messages to send, I can't get the keyboard to go with it.

EDIT: I barely posted this and figured it out. It looks like the solution is:

msg.payload = {chatId : [your chatId], type : 'message', content : [text to message], options : opts}

....where "opts" is the variable defined in the inline keyboard example. I'm not sure if this was the best way / actually works, but I think it's a common enough use case that it should be in the examples?

**Comment by windkh** [comment]
Hi ... I will add an example wirh your idea. I hope that I got it right...

**Comment by inputd** [comment]
Wow, tyvm! And thank you for the fast reply!

I tried reading documentation to figure it out on my own, but it was luck that I ultimately got it to work. I noticed in the Telegram API there was a "sendmessage" method, and one of its options was "reply_markup" and "inlinekeyboardmarkup".

I'm not sure why in the API docs its "sendMessage" and in the node-red node its "message". But throwing in an "options" after the chatId/type/content was a total guess. Defining the keyboard as a variable and then assigning it to msg.payload.options doesn't work in this case.

Anyway, I'm not a programmer or anything - I definitely rely on your examples (and copy/pasting chunks of code from various examples ;)), and I definitely think a lot of people would benefit from/appreciate an example showing how to send an actionable notification to a known ID, without it being a reply. 

Thank you again!!!

**Comment by windkh** [comment]
Please post your flow here so that I kniw what you did

**Comment by inputd** [comment]
Sure!

Inject Node>Format Node>Telegram Sender.

Format Node is as follows:
`context.global.keyboard = { pending : true };

var opts = {
    reply_markup: JSON.stringify({
        "inline_keyboard": [[
            {
                "text": "Sound the siren!",
                "callback_data" : "siren"
            },
            {
                "text" : "Oops! That was me",
                "callback_data": "disarm"
            }]
        ]
    })
};

var reply = "ENTRY DELAY! Alarm will arm in 45 seconds!!!"

msg.payload = {chatId : [YOUR CHAT ID], type : 'message', content : reply, options : opts}
return [ msg ];`
