### ISSUE TITLE
Command Node never receives

### ISSUE THREAD

**Issue by stevenhorner** [windkh/node-red-contrib-telegrambot#7]
Not sure what I'm doing wrong, but the Command node never receives anything, i've tried a debug node on both outputs.

The sender and receiver nodes both work OK with my bot.

I tried to look  at node-telegram-bot-api and it talked about either polling or webhooks, but it looks like the node-red wrapper only does polling which should make it simpler rather than having to deal with certificates. 

If the receiver node works, is there any reason the command node wouldn't?

**Comment by MrkWkngr** [comment]
Have you checked the users and chatIds properties? There's bug with the default setting of []. I think it's worth a try with those fields completely empty.

**Comment by windkh** [comment]
Could you send a screenshot of the settings of this node?

**Comment by MrkWkngr** [comment]
This is the default setting when creating a new node:
![wrong](https://cloud.githubusercontent.com/assets/22226859/19218530/9f1e2be0-8dfc-11e6-9b7d-b81457c824f1.png)

This works for me:
![right](https://cloud.githubusercontent.com/assets/22226859/19218529/9f175cfc-8dfc-11e6-87f3-a00e46d1fe55.png)

also see this the issue  #5

**Comment by windkh** [comment]
Ok that is a known issue. Sorry for nit having fixed it so far. Yes the name can be different from the comand.

**Comment by stevenhorner** [comment]
I can confirm if I remove the Square brackets it works, thanks @MrkWkngr

**Comment by windkh** [comment]
Fixed in Version 1.11.0
