### ISSUE TITLE
Issues with 'restrictChatMember'?

### ISSUE THREAD

**Issue by Swiftnesses** [windkh/node-red-contrib-telegrambot#71]
I'm using this but it results in a 'forever' ban:

```
var options = {
    until_date: Math.round(((new Date()).getTime() + 60000) / 1000),
    //can_send_message: false,
    //can_send_media_messages: false,
    //can_send_other_messages: false,
    //can_can_add_web_page_previews: false
}

var payload = {
    chatId: -xxxxxxxxxxxxxx,
    type: "restrictChatMember",
    content: xxxxxxxxxx,
    options: options
}

msg.payload = payload

return msg
```

I've tried multiple times in the future, but no luck. Any ideas?

**Comment by windkh** [comment]
Well, I guess the until_date could be causing this
See https://core.telegram.org/bots/api#restrictchatmember

Quote:
Date when restrictions will be lifted for the user, unix time. If user is restricted for more than 366 days or less than 30 seconds from the current time, they are considered to be restricted forever

**Comment by Swiftnesses** [comment]
@windkh But my payload matches what the Telegram API expects?

until_date is a valid parameter, sadly it seems it's ignored, but why?

**Comment by windkh** [comment]
Hm I will try to debug that... if the value is passed correctly to the API, then I won‘t be able to help.... stay tuned

**Comment by windkh** [comment]
Well, there is a bug in the node. The options were not passed to the api for 
kickChatMember
unbanChatMember
restrictChatMember
promoteChatMember
it will be fixed in the version 5.5

See also https://github.com/yagop/node-telegram-bot-api/issues/454

**Comment by Swiftnesses** [comment]
Hi @windkh 

Great news, looking forward to this fix! 👍

**Comment by Swiftnesses** [comment]
@windkh Quick off-topic question, it looks like the underlying module now supports polls, can we expect this in Node Red soon too then? Thanks 🥇

**Comment by windkh** [comment]
version 5.5. is published. Please test if those changes fix your problem.

@Swiftnesses I will add poll support as soon as the node-telegram-bot-api is released via npm. The last version was released ago. You can speed this up if you can urge the author to ship a new release ;)

**Comment by Swiftnesses** [comment]
Seems to be working, thanks!

**Comment by windkh** [comment]
Thanks for reporting and sorry for the inconvenience.
