### ISSUE TITLE
Reply node simple code mistake

### ISSUE THREAD

**Issue by mxswat** [windkh/node-red-contrib-telegrambot#72]
I'm using the "reply node" and I noticed that at line 1281 of 99-telegrambot.js.
`if (msg.payload.messageId) {`
Should have been
`if (msg.payload.sentMessageId) {`
And also the node.warn should be updated to reflect this change

**Comment by windkh** [comment]
Thanks for reporting this. I will check this as soon as possible.

**Comment by windkh** [comment]
fixed in version 5.5.1
