### ISSUE TITLE
It is possible "read" what bot say?

### ISSUE THREAD

**Issue by vampywiz17** [windkh/node-red-contrib-telegrambot#73]
Hello, I would like to use the bot to report a motion detector state. The method:

IFTTT webhook --> telegram bot --> node-red.

My problem is that only see if i say something to the bot, but i can not see that if he "ask" something (report the motion state)

It is posssibe to read somehow the bot messages?

**Comment by windkh** [comment]
I am not sure that I really understood your problem.
The bot sends the messages to the telegram server in the internet. From there you can read the messages using any telegram client.

**Comment by vampywiz17** [comment]
> I am not sure that I really understood your problem.
> The bot sends the messages to the telegram server in the internet. From there you can read the messages using any telegram client.

my goal is:

My bot send a message (the source is a webhook that indicate a IFTTT trigger) and i would like to read **with Node-Red,** what the bot say.

**Comment by windkh** [comment]
The reply node is not the right choice.
Hm you mean you want to have a telegram client node that is able to poll message from some other bot in the internet? I guess that kind of use-case is not supported by this library.
