### ISSUE TITLE
deleteMessage not working? 

### ISSUE THREAD

**Issue by azrin1972** [windkh/node-red-contrib-telegrambot#75]
just updated to this 5.5.1 version and deleteMessage which was working before is no longer working

**Comment by windkh** [comment]
From what version did you upgrade to 5.5.1?

**Comment by windkh** [comment]
Msg.payload.content should be the messageId to delete. Maybe that changed somewhere in the past. I can‘t investigate that right now as I am not at home at the moment.

**Comment by azrin1972** [comment]
> Msg.payload.content should be the messageId to delete. Maybe that changed somewhere in the past. I can‘t investigate that right now as I am not at home at the moment.

Can't remember from what version I updated from but setting msg.payload.content with messageId to be deleted works. Thanks
