### ISSUE TITLE
How to implement bold text, within inline keyboard?

### ISSUE THREAD

**Issue by Swiftnesses** [windkh/node-red-contrib-telegrambot#77]
Hello,

I'm trying to implement bold text above the inline keyboard buttons (the content), I've tried adding parse_mode: "HTML" in the options above the "reply_markup" section, but it doesn't seem to work, can you help?

Many thanks in advance.

**Comment by windkh** [comment]
You have to set the parse_mode in the options to "markdown" and then write your text in * like *bold* in the sample below.

context.global.keyboard = { pending : true };

var opts = {
  parse_mode: "Markdown",
  reply_to_message_id: msg.payload.messageId,
  reply_markup: JSON.stringify({
    "inline_keyboard": [[
                {
                    "text": "Yes",
                    "callback_data": "FOO YES"            
                }, 
                {
                    "text": "No",
                    "callback_data": "FOO NO"            
                }]
            ]
  })
};

msg.payload.content = '*bold* Are you sure?';
msg.payload.options = opts;

return [ msg ];

**Comment by Swiftnesses** [comment]
Gitcha, I always use HTML for parse mode, which doesn't seem to work, I'll give the native markdown a shot!
