### ISSUE TITLE
How to detect forwarded message?

### ISSUE THREAD

**Issue by Swiftnesses** [windkh/node-red-contrib-telegrambot#78]
Hi,

I'm trying to prevent forwarded messages, I believe the API provides this info (and possible the underlying Node lib), is this possible via Node Red?

Many thanks.

**Comment by windkh** [comment]
You should have a look at the OriginalMessage property which is provided by the underlying API. Maybe there is a property that indicates if the message is forwarded. But I don‘t know by heart how to discover that case...

**Comment by Swiftnesses** [comment]
Hey @windkh I don't see anything from the receiver (with debug on), only the channel and msg ID... :/

**Comment by Swiftnesses** [comment]
@windkh Dumb moment, sorted.

**Comment by windkh** [comment]
Could you share your findings?

**Comment by Swiftnesses** [comment]
LOL, I'd rather not. I forgot that I only had payload enabled on my receiver node. Once enabled, you can see forward_sender_name and forward_date make a decision from there.

**Comment by windkh** [comment]
Ok perfect
