### ISSUE TITLE
Multiple receiver / command / query etc nodes, a problem?

### ISSUE THREAD

**Issue by Swiftnesses** [windkh/node-red-contrib-telegrambot#79]
Hi @windkh,

Do you know if there's an issue with many nodes of the same type? I know Telegram has restrictions with regards the sender node (throughput of messages), but what about multiple 'connected' incoming / outgoing nodes? Yesterday I got my first "ETELEGRAM: 429 Too Many Requests: retry after 43" and I'm trying to avoid future occurrences (as it never recovered, in fact Node red crashed and needed a restart!).

I'm trying to work out if we're making multiple connections and if there's potential issue with this, i.e. instead of multiple callback nodes, should we use one and a switch for example? Should we use one receiver and a switch too, instead of multiple receiver nodes? Hmmm.

**Comment by windkh** [comment]
Only the configuration node maintains the connection to the telegram server

**Comment by Swiftnesses** [comment]
Well that's superb, it means I don't need to worry about incoming nodes and just need to tweak my rate limiter for the send process (centralise them and throttle)... Thanks @windkh.

**Comment by windkh** [comment]
Yes
