### ISSUE TITLE
Inline keyboard callback and auth by chat id

### ISSUE THREAD

**Issue by AntonioNav** [windkh/node-red-contrib-telegrambot#80]
Hello,

I'm trying the inlinekeyboard flow example, but setting a chat id in my telegram bot node to only allow use my bot from this chat. The command /foo works well and display the two buttons (yes - no), but when I press the buttons, I receive an error: "Unauthorized incoming call from ....". If I add my telegram user as authorized, works well.

I tried to add msg.payload.chatId = -xxxxxxxx; to 'inline keyboard message' (line 21), but no luck. Any idea about what i'm doing wrong?

Regards,

**Comment by windkh** [comment]
Could you send me the flow so that I can have a look on it?

**Comment by AntonioNav** [comment]
Hello,

I use this example flow: https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/inlinekeyboard.json#L1

I only change the telegram bot configuration node to setup my token and the chatid.

**Comment by windkh** [comment]
I will check this

**Comment by windkh** [comment]
I just tested the flow and everything worked well.
First of all I would try to clear the chatids and users fields to make sure that the flow works without authorization checks. Then I would try to add your username to check if there is a spelling problem.
As a cross check you could clear the Users field and anter your userid in the chatis field of the configuration nod (a positive number)... 

I guess there is a spelling error or something like that.
