### ISSUE TITLE
deleteMessage example incorrect?

### ISSUE THREAD

**Issue by andrewdolphin** [windkh/node-red-contrib-telegrambot#81]
Whilst the closed issue 75 gives the fix, the documentation shows msg.payload.options needing to be set to the message id and not msg.payload.content which is the correct data item

https://github.com/windkh/node-red-contrib-telegrambot/issues/75

![](https://raw.githubusercontent.com/windkh/node-red-contrib-telegrambot/master/images/TelegramBotEditInlineKeyboard5.png)

**Comment by windkh** [comment]
Thanks for reporting this ... I will rework this.

**Comment by windkh** [comment]
Fixed in 5.5.2
