### ISSUE TITLE
Callback query answer fails

### ISSUE THREAD

**Issue by inputd** [windkh/node-red-contrib-telegrambot#82]
I think an update to telegram has likely created this issue, since it's been working fine for months.

In this example:
`var show_alert = false; //if true, it opens a dialog`
`// msg.payload.content contains the callback data`
`// you may change this value here:`
`msg.payload.options = show_alert;`
`msg.payload.content = 'Alarm Disarmed!'`
`return [ msg ];`

What used to occur is the text "Alarm Disarmed!" would appear at the top of the chat for a moment. However, now the callback button has a pinwheel that spins forever, and the text never displays. The callback IS received though; the automations that are triggered by the button press still occur

**Comment by windkh** [comment]
ha ha your welcome ;)
