### ISSUE TITLE
Some problems, please help, thanks

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#83]
Hi! Thank you for your kind attention, I've installed this module under Windows and I've the following problems:

1) I don't have any message incoming. I?m in Russia but I'm using a proxy, I've found one in Germany that supports https, I tested it and it works, the flow says connected, I'm sending by my mobile phone but I don't have any input.
PS: seems Telegram API wants https, but no one specified in module that I need to search a proxy supporting HTTPS. If I use one that supports HTTP only the module says iit is "connected", but chances are it can't work. Strange. What this "connected" assure us about? Seems it is not connected.. 
2) I'm not sure if it works, I can't find online a way to test the bot, if it receives messages. I'm in Russia and this is why I wanted to test it from a country where telegrams works. How can I test it?
3) My phone here can connect instead to Telegram and without proxy, how they can if in Russia is banned? SO if the phone can connect, how the module could connect in the same way?
4) The verbose log option doesn't return anything, so I have no logs to check at all.
5) the Deploy button become really slow, Node red shows "Error stopping node: Close timed out"  about the bot name module, probably something wrong there

**Comment by Barabba11** [comment]
I subscribed to a vpn to test it, supposing it *should* work when directly connects to Telegram API. It doesn't. 
I've just the receivet connected to the debug node, on my phone I'm sending /start and other text, but nothing coming out from there, why? 
I removed proxy, it writes connected, the pnone send messages and get the two green VV.. I really don't understand!

**Comment by Barabba11** [comment]
Finally I've found a valid SOCKS5 proxy and it works. To find it I should use the Telegram Windows program which has a nice gui to test the proxy and say if they are available and online. I hope you can improve your module to write "connected" when really the proxy gives the proper service.
Anyway I don't understand why the Telegram program can connect also without proxy, they found a way to bypass the block like in the phone, and as it connects to API I suppose then it may be possible also to use the same way in the module. Of course if it is not their secret..

**Comment by windkh** [comment]
Hi @Barabba11 
I am glad that you got it finally up and running.
I will try to improve the documentation about how to use Socks5 support.
Then I need to reproduce your problems to find out how to improve the logging...
Thanks for the input.
