### ISSUE TITLE
Please add MTProto

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#84]
Hi, I tried hard to make it work with SOCKS5 proxy but I never had a result, that's really strange. I've noticed MTProto become very popular, people just talk about that and not more SOCKS5, can you please implement it? Thank you!

**Comment by windkh** [comment]
MTProto will be available as soon as the underlying lib supports it

**Comment by windkh** [comment]
What did not work with SOCKS5? Should I add a tutorial how to set it up?

**Comment by windkh** [comment]
The Bot API is based on HTTP and JSON and is outside of the MTProto scope:
see also for further explanation: 

https://www.wired.com/story/telegram-bots-tls-encryption/

**Comment by windkh** [comment]
see https://flows.nodered.org/node/node-red-node-telegrambot
