### ISSUE TITLE
sendmediagroup example not working

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#86]
i am experimenting with your telegrambot.
i can send single photos, but do you think the example json for mediagroup is still valid?

looks different: https://core.telegram.org/bots/api#sendmediagroup

you you also give explanation or example for file-path,
or is keyword "media:attach:// " necessary for upload?

thanks a lot,
ozett

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/67639086-dbca9300-f8eb-11e9-843b-b017f3355ccb.png)


maybe this is the new json (got it from the receiver-node after uload of 2 images) 
or is this not a mediagroup?

**Comment by ozett** [comment]
if i dont send "payload.content", i got an error.
but for media-group it is not necessary.

https://github.com/yagop/node-telegram-bot-api/blob/435f06319e92f12fb7ef642f91d031dafe5aff80/src/telegram.js#L1831-L1877

could someone help to show where my error is...?

**Comment by windkh** [comment]
I will check this today

**Comment by ozett** [comment]
thanks, almost for checking and notification... 👍 
tell me , if i should provide more information (versions , platform..)

I'm curious .. 😉

**Comment by ozett** [comment]
just for the record...
![image](https://user-images.githubusercontent.com/5937811/67666123-67cfcf80-f96b-11e9-8ff0-1981b1486848.png)

**Comment by windkh** [comment]
Ah you are using node-red 1.x ...

**Comment by ozett** [comment]
I sonst think that cause the Problem..
How to debug?
I Will Help as much as i can...

Karl-Heinz Wind <notifications@github.com> schrieb am Mo., 28. Okt. 2019,
15:43:

**Comment by windkh** [comment]
Ok I just checked if the example works: it does as expected.

When you receive an album or media group., then you will receive the single items of the album as extra messages (one per item). 

Your first screenshot indicates that you received one single photo of the media group... you should also have received the other ones in the same way. 

Don't get confused about the photos array: You will get the same identical picture with some different resolutions. The one with the highest resolution from that list is put into payload.content.
Don't ask me why but maybe telegram sends images with smaller resolution so you can display thumbnails in the client...

Now about sending. The example works, the only difference is that you did not supply a caption for each photo. I don't know if that could cause your problems but just give it a try: supply a caption like in the example code.

```
msg.payload.type = "mediaGroup";
msg.payload.content = [
    {
        type : "photo",
        media : "c:\\Temp\\1.jpg",
        caption : "Photo 1"
    },
    {
        type : "photo",
        media : "c:\\Temp\\2.jpg",
        caption : "Photo 2"
    }
];

return msg;
```

Well, maybe the version 1.x is causing the problems.... but right now I did not find any time to test that version.

**Comment by windkh** [comment]
I just commited version 6.0.0 that contains a pull request for version 1.x.
Maybe you check if that works for you

**Comment by ozett** [comment]
i tried to upgrade via cli-install, but i failed. 😢 
i do something wrong to update? or is there another way?

![image](https://user-images.githubusercontent.com/5937811/67714530-5c5ec180-f9c8-11e9-865e-e58fe6517ea9.png)

look like i am still on 5.x
```
root@deb8mpd-virt:~/.node-red# npm install node-red-contrib-telegrambot
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ node-red-contrib-telegrambot@5.5.2
updated 1 package and audited 9792 packages in 18.094s
found 59 vulnerabilities (2 low, 13 moderate, 44 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@deb8mpd-virt:~/.node-red#

```

glad, if you can help me out... 😉

**Comment by windkh** [comment]
Hm sorry I have no idea

**Comment by ozett** [comment]
maybe it takes some time to upstream?
on node-red palette there was it also not marked for update...
i will check tomorrow again..

up to now, thx!

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/67716132-82d22c00-f9cb-11e9-94ad-3865afca1b3f.png)

the first step: npm outdated...
looking for the next...

**Comment by ozett** [comment]
https://docs.npmjs.com/cli/update

```npm update [-g] [<pkg>...]```

but did not update on my npm --version 6.12.0...

![image](https://user-images.githubusercontent.com/5937811/67716727-a5b11000-f9cc-11e9-97a5-b5e02d957b9c.png)


still a bug ? something else to try? 🙄

**Comment by windkh** [comment]
Hm I guess I will have to do an update on my machine on my own tomorrow....

**Comment by ozett** [comment]
i did ```npm update`` , but it only updated seletive packages ... 🙄 

![image](https://user-images.githubusercontent.com/5937811/67716933-08a2a700-f9cd-11e9-8c00-65aaa0d4afef.png)

**Comment by ozett** [comment]
i found npn-upgrade,
but irritated results now...
seems something to do with the package.json

still not solved...

![image](https://user-images.githubusercontent.com/5937811/67717498-1e649c00-f9ce-11e9-95d4-90da8de29161.png)

**Comment by ozett** [comment]
strange thing.. i did it explictly...now it run...
i will now check my node-red gui...

![image](https://user-images.githubusercontent.com/5937811/67717782-aea2e100-f9ce-11e9-9fd4-b5d7d71b5e27.png)

**Comment by windkh** [comment]
so did you  manage to finally receive a media group?

**Comment by ozett** [comment]
no sorry, did not work...
i will do it now again and provide my details here...just a second...

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/67842650-da22ea00-fafa-11e9-81f1-12a0958744c4.png)

i dont receive a mediagroup message.
single messages and photos are working fine with the same bot-node.
the log has this message:
```
node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:1006:28
```

**Comment by ozett** [comment]
i did not look into your code,
but the API tell to send an array of/called(?) "media" (2-10 items!),
as my json=node sends an array called "content".
may your sending-code changes this?
but at the moment i cannt see it is send out.

![image](https://user-images.githubusercontent.com/5937811/67843244-e52a4a00-fafb-11e9-967f-33d084bf436a.png)

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/67843349-16a31580-fafc-11e9-8647-8b1739260f65.png)

**Comment by ozett** [comment]
it took a while, than i got this error..
![image](https://user-images.githubusercontent.com/5937811/67845227-6a632e00-faff-11e9-8316-8e748de216c3.png)
```
node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:982:54
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: IMAGE_PROCESS_FAILED
    at request.then.resp (/root/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)


```

**Comment by windkh** [comment]
Maybe we should try to talk via webmeeting ... as I don‘t really get what is going on on your machine.

**Comment by ozett** [comment]
ok, me can webmeet, or i can show you version and package-status.
maybe you know a way to test group-sending on command-line?
as another way to test sending group-messages.

are you shure, the telegrambot-node sends medidagroup settings for the new api-requirements? can i see/debug the send-information in more detail to debug further?

**Comment by ozett** [comment]
my node-red was running the whole day,
just before a second i disabled the telegram echo-node and added a debug-node-output to the telegram-node. nothing more.
i tested group-send again --- and it worked.
dont know why. i investigate tommorow.

![image](https://user-images.githubusercontent.com/5937811/67976936-5e6a8f80-fc17-11e9-829d-28e8bae2bac8.png)

**Comment by windkh** [comment]
Aha und wieso das plötzlich?

**Comment by ozett** [comment]
wenn der echo-loop aus den beispieln mitläuft, dann gehts nicht.
ohne echo-loop läufts! vielleicht kann man das nachstellen?

-

if the echo-loop is active, it wont work,
it runs without problems it echo-loop is disabled.

may you want to check and confirm?

![image](https://user-images.githubusercontent.com/5937811/67986917-78629d00-fc2c-11e9-8e35-1050ee5d879b.png)

**Comment by windkh** [comment]
Ich vermute du hast den gleichen token in zwei config nodes verwendet.

**Comment by ozett** [comment]
> Ich vermute du hast den gleichen token in zwei config nodes verwendet.

das heisst was? 
ach so, den bot-token zweimal? das geht nicht?
ich gucke...

**Comment by windkh** [comment]
Ne da der config node die verbindung hält und zwei mal die gleiche verbindung aufmachen führt zu komischen verhalten

**Comment by ozett** [comment]
kann ich den "config-node" einzeln einstellen?
ich dachte, der ergibt sich aus der auswahl des bots im telegram-sender-node.
da ich mehrere sender-nodes auf einer seite habe, habe ich also darin mehrfach den bot-token ausgewählt. geht ja auch ohne probleme.
wie komme ich dann zu den config-nodes, bzw wie kann ich die bereinigen (wenn das probleme bringt).

![image](https://user-images.githubusercontent.com/5937811/67987332-65040180-fc2d-11e9-9ff9-3a5829596bc5.png)

**Comment by ozett** [comment]
ist das problematisch?

![image](https://user-images.githubusercontent.com/5937811/67987414-9aa8ea80-fc2d-11e9-8005-8f0a536cd4d2.png)

**Comment by windkh** [comment]
Rechts in der sidebar die config nodes einblenden

**Comment by windkh** [comment]
> ist das problematisch?
> 
> ![image](https://user-images.githubusercontent.com/5937811/67987414-9aa8ea80-fc2d-11e9-8005-8f0a536cd4d2.png)

Ne das ist ok

**Comment by ozett** [comment]
wie finde ich dann den "problematischen" doppelten? oder habe ich 13 stück? und das ist doch ok?

**Comment by windkh** [comment]
13 nodes verwenden diesen einen config node was ok ist.
Wenn du bei einer der anderen configs den gleichen token drinstehen hast ist nicht gut

**Comment by ozett** [comment]
> Wenn du bei einer der anderen configs den gleichen token drinstehen hast ist nicht gut

ich verstehe nicht ganz.
"andere config" ? ich habe insgesamt 13x meine bot-id für den telegram-bot gezählt über alle flow-pages.

wo würde ich eine "andere config" noch suchen? den bot-token habe ich natürlich nur in der konfiguration des telegram-bot eingretragen. natürlich nicht bei mqtt oder so, versteht sich.

**Comment by windkh** [comment]
Ne a z.B. In DEINBOTNAME

**Comment by ozett** [comment]
ja, dachte ich mir..das waren für mich dummy-configs...davon hatte ich einige.
hab jetzt gesehen, dass ich die auswählen kann, dann auf edit(bleistift) und dann erst löschen..
bin gerade dabei das zu breinigen..vielleicht habe ich dann die warnung nicht mehr.

das groupsend muss aber mehr mit dem echo-loop des bots zu tun gehabt haben.
wenn ich echo-loop aktiviere gehts nicht, sonst schon..

**Comment by ozett** [comment]
so, gestern gings noch, heute morgen nicht mehr.
der flow ist gleich geblieben, jetzt habe ich eine fehlermeldung:

![image](https://user-images.githubusercontent.com/5937811/68014559-38cd9c80-fc90-11e9-9d75-c63ab2275de9.png)

kann ich das irgenwie debuggen? 
die bilder im pfad sind wie gestern, es muss was anderes sein...
nebenbei: der telegram-bot sender hat einen ausgang, aber im angeschlossenen debug-node sehe ich nix. was mache ich falsch?

**Comment by ozett** [comment]
so erster fehler weg, neuer da:

```Unhandled rejection Error: ETELEGRAM: 400 Bad Request: URL host is empty```

(beim ersten fehler waren die auth-informationen aus den http-request-nodes für die kameras leer. ganz komisch, gestern gings ja noch, vielleicht die config-bereinigung beim telegram-bot? dürfe aber eigenlich nicht auf die config der http-requests auswirken. ganz komisch)

->nachgetragen, das geht wieder. aber jetzt ein neuer fehler ...
Was heisst das nun?

![image](https://user-images.githubusercontent.com/5937811/68016293-906e0700-fc94-11e9-96e0-5ebb3685b8d8.png)

**Comment by ozett** [comment]
gelöst
![image](https://user-images.githubusercontent.com/5937811/68016677-55200800-fc95-11e9-8772-f0e703e0e43c.png)

ich hab den namen geändert um die config des telegram-bot nochmal speicher zu können.
das hat offensichtlich geholfen...
vermutlich hängt das mit dem Hinweis auf die doppelten bot-token zusammen.
das ist ein "falscher-fehler" denn ich habe den bot-token nur einmal eingesetzt, allerding diesen in 13 telegram-nodes.
irgenwie muss die config oder das schreiben der config zu fehlern führen.
wo ist die config abgelegt? kann/soll ich da mal nachgucken?
(ansonsten prüfe ich morgen noch mal, ob sich was über nach ändert 👻  😄 )

**Comment by windkh** [comment]
Jetzt mal eine kurze Frage... geht das mit der media group? Ich würde den issue schliessen wenn es nur auf deinen system spuckt.

**Comment by ozett** [comment]
kann geschlossen werden, media group geht jetzt.
aber erst nachdem ich die config von telegrambot-node neu schreiben liess.
es bleiben die ungereimtheiten mit der meldung der doppelten config.
und die ungereimtheit, warum die config vom telegrambot-node durcheinander geriet.

wenn das wieder auftaucht könnte ich einen neues issue aufmachen.
erstmal vielen dank.

**Comment by ozett** [comment]
geht nicht.  liegt aber sicher nicht an meinem system

nach einiger zeit hört es auf...

![image](https://user-images.githubusercontent.com/5937811/68025852-34b07780-fcae-11e9-8d06-6ed1a8fd8429.png)

**Comment by ozett** [comment]
geht sofort, wenn ich den ganzen node-red restarte.
vielleicht ein memory-problem über die laufzeit?
oder vom polling oder einer netzwerkbibliothek?

detailierteres log zu telegram.js wäre gut...

**Comment by ozett** [comment]
mehr wohl ein problem mit der telegram-bot-api..., vieleicht... 😒 
ich geh jetzt dort mal die issues durch...

vielleicht sowas:
https://github.com/yagop/node-telegram-bot-api/issues/657

**Comment by windkh** [comment]
I will close that issue as the sendmediagroup example works.
