### ISSUE TITLE
node registered twice - misconfig or only informative?

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#87]
i use one telegrambot, but i use one node with the bot-config in the upper half of my flows-page, and another node with the same bot-config further down. gives my flow-page more structure. better readable. but so i have the same bot as two nodes on my flow page. 

and get a notification message. looks like a error-warning. 
can i get rid of this?
is there a better way to configure this?

![image](https://user-images.githubusercontent.com/5937811/67840438-33d4e580-faf6-11e9-8cdb-184835ecff43.png)

**Comment by windkh** [comment]
Normally you should not get this warning. But that could gappen when you do not a full deploy. You can ignore this message

**Comment by ozett** [comment]
i get this "registered twice" notification after importing example-flows from your github (as the links to the examples on npm-site are broken).

i.e. this: https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/inlinekeyboard.json

if i import it, and aply changes, i get "registered twice" notification .
if i than go into the bot-config and change only the name, and save this,
than the message is cleared and goes away.
(i also delete the imported heinzbot and any other bot-config, just leave my own bot-api in)

![image](https://user-images.githubusercontent.com/5937811/68038146-9205f200-fcc9-11e9-9ab8-d97f23529f98.png)

**Comment by ozett** [comment]
it seems to me, that duplicating a command-node has the same effect.
if i change the name and save the one and only bot i have, the duplicate information is gone.
no error anymore

**Comment by ozett** [comment]
unsolved before:
https://github.com/windkh/node-red-contrib-telegrambot/issues/67

**Comment by windkh** [comment]
.... the warning clearly states that this can be ignored. I will remove the log as it only causes confusion

**Comment by ozett** [comment]
cant we find the duplicate?
i will search as much as i can? 😃 

my impression it, it comes from copying telegram-nodes or importing telegram-flows...

**Comment by windkh** [comment]
When a node is created it registers itself at the config node.
The config node issues the warning when a node registers itself twice.
That happens when you do not fully redeploy.

**Comment by windkh** [comment]
removed warning
