### ISSUE TITLE
Send emoji inside content message

### ISSUE THREAD

**Issue by Quentintin** [windkh/node-red-contrib-telegrambot#89]
Hello,
I can't succeed to send emoji inside **Telegram sender** node. I try unicode or byte format, but none works.

https://apps.timwhitlock.info/emoji/tables/unicode

Is it possible ?

**Comment by windkh** [comment]
Send an emoji from your mobile phone to your receiver node and have a look what you received: that should explain it

**Comment by windkh** [comment]
copy the emoji from a character map and paste it into your message:
https://apps.timwhitlock.info/emoji/tables/unicode
like for example:
😁
