### ISSUE TITLE
editMessageLiveLocation not working

### ISSUE THREAD

**Issue by MartinRusk** [windkh/node-red-contrib-telegrambot#90]
Seems there is missing the chatId as first parameter in the call? Same for stopMessageLiveLocation?

**Comment by windkh** [comment]
I will check this

**Comment by MartinRusk** [comment]
Ich checked with my local installation - yes, in line 1145 and 1159 (and maybe more) chatId must be included as first parameter, then it works.

**Comment by windkh** [comment]
It works and I try to explain why:

The signature of "editMessageLiveLocation" is different from the other functions provided by the underlying lib:
`
editMessageLiveLocation(latitude, longitude, form = {}) {
    form.latitude = latitude;
    form.longitude = longitude;
    return this._request('editMessageLiveLocation', { form });
  }
`  
The chat id is passed in the options as follows:

`
var chatId = msg.payload.chatId;
msg.payload.type = 'editMessageLiveLocation';
msg.payload.content = {
    latitude : lat,
    longitude : lng
};
  
msg.payload.options = {
    chat_id : chatId,
    message_id : messageId
};  

return msg;
`

I know that this is confusing and I admit that I am not glad about that. Have a look at the examples in the examples subfolder....

**Comment by windkh** [comment]
@MartinRusk  Falls es noch Probleme gibt werde ich gerne helfen... gerne auch per mail
karl-heinz.wind@web.de.

**Comment by MartinRusk** [comment]
Ok, bin auch so weit. stop geht jetzt. müssen da nicht trotzdem die options _vor_ lat/lon übergeben werden laut Telegram API?

**Comment by windkh** [comment]
Die darunter liegende lib die den Aufruf zu Telegram schickt, definiert die Schnittstelle so... das ist nicht unbedingt identisch mit der Telegram API. Leider. Mich würde noch Ihr Anwendungsfall interessieren... bin immer neugierig ... vielleicht reichts ja mal zu einem Treffen.

**Comment by MartinRusk** [comment]
Mine Fehler, war, dass eine chatId erwartet wird. Im Beispiel kommt diese vom Kommando, ich habe aber eine neue Message zusammengebastelt.
Mein Anwendungfall ist ein Bot zur Übermittlung von Flugzeugpositionen aus einem ADS-B Empfänger.

**Comment by windkh** [comment]
Ja das mit der chat id ist eine Schwäche ... ich werde den bot anpassen so dass die chatId entweder aus den Options oder alternativ direkt aus der Message kommen kann. Danke für das Einlasten des Issues.
