### ISSUE TITLE
how to set reply mode to a message

### ISSUE THREAD

**Issue by alfredolo** [windkh/node-red-contrib-telegrambot#91]
Hi,
i have not found my answare into the instrusctions.
It is possible to set a auto reply ? I seen some bot does it. It is the same function when you drag the message on the left. A reply message appair.
I would like to use inline keyboard, and hitting a button a text like "message to send ?" appairs and the reply mode was set.
Thank you

**Comment by windkh** [comment]
Sorry I did not understand what you want...

**Comment by alfredolo** [comment]
I would like to insert a button in an in-line keyboard which, when pressed, sends the bot a new message like "what do I write?". At this point instead of responding to the new message by dragging it to the left to bring up the reply mask, I wish it was already set. I saw that some bots do it, how do I do it?

**Comment by windkh** [comment]
Can you provide a image or video of this use case?

**Comment by alfredolo** [comment]
No i am wrong. I am testing the bot.
When i click on reply botton on inline keyboard, the bot send a new message :
https://ibb.co/YbhpXvY
This is not a reply, i am wrong. How can i do the blue line on the left ?

**Comment by windkh** [comment]
Ah the bot should send a reply? I will provide an example for this

**Comment by windkh** [comment]
var opts = {
  reply_to_message_id: msg.payload.messageId
};

msg.payload.content = 'I received your message';
msg.payload.options = opts;

**Comment by windkh** [comment]
I also added an example
