### ISSUE TITLE
Key and certificate should be optional for webhook mode

### ISSUE THREAD

**Issue by JokerQyou** [windkh/node-red-contrib-telegrambot#92]
In the config panel there is this tip:

> If any of the host, key, certificate properties is left blank the bot will default to polling mode.

I think the key and certificate should be optional here if the bot is reverse-proxied. For example: I could have set up node-red on my home computer, and the bot runs in LAN network; For webhook to work, I could set up a localtunnel service to expose the bot port (8443) to one of my cloud servers in the Internet. And if SSL is enabled on my cloud server, the key and certificate is not necessary anymore on my home computer.

This might be an advanced usage, but I think it's valid. Please let me know how you think.

**Comment by windkh** [comment]
Yes you are right.
There are many ways how a tunnel or connection can be set up. I did not try to document everything as the advanced users knows how to deal with the options....

**Comment by JokerQyou** [comment]
But currently these are required fields, without them the bot will fallback to polling mode. The only way to go with webhook in my scenario is to setup another layer of SSL like this:

```
Telegram server =HTTPS(1)=> Cloud server =HTTPS(2)=> Tunnel server =tunnel=> Tunnel client =HTTPS(2)=> Node-Red server
```
This seem to be redundant to me. Maybe we could leave these fields as optional in an "advanced mode"?

**Comment by windkh** [comment]
Ah ok ... I will take care of that
