### ISSUE TITLE
Sender Node with message option disable_notification

### ISSUE THREAD

**Issue by averlon** [windkh/node-red-contrib-telegrambot#94]
Hi,
I am quite new to this topic. Anyhow. I have managed to send some messages to a telegram bot.

For some of the messages I would like to add the option "disable_notification", but I was not able to manage.

Where I had success, I created the message by a "change" by deleting msg.payload first and then setting msg.payload.type, msg.payload.content and msg.payload.chatId.
As I said, this works for me.

Now I tried to add the msg.payload.options simply with a string "disable_notification:true" - which did not work.

I looked at the examples and they were done by a function. So I tried to do it this way:

`msg.payload.type = 'message';
msg.payload.chatId ='123456';
var chatId = msg.payload.chatId;
msg.payload.content = 'Test';
var av_options = {
    chat_id: msg.payload.chatId,
    text: msg.payload.content,
    disable_notification: true,
}
msg.payload.options = av_options;
return msg;`

Return was: chatId missing.

I wonder if you could give me a hint what I am doing wrong.

Regards
Kallewirsch

**Comment by windkh** [comment]
Ich habs nicht kapiert... vielleicht versuchst es auf deutsch?

**Comment by averlon** [comment]
mmh!

ich würde gerne über ein Change-Objekt die Option "disable_notification" aus dem telegram api setzen.

Über ein Function-Objekt ist es mir eben auch nicht gelungen.

Mittlerweile habe ich was gefunden - mit viel probieren:
Im Change-Objekt:
festlegen: msg.payload.options
JSON: {"disable_notification":true}
Das scheint zu funktionieren.
Danke Kallewirsch
Issue:solved

**Comment by windkh** [comment]
Ja grundsätzlich lässt sich alles mögliche über die options steuern.... dann schliesse ich den issue.
Vg

**Comment by ozett** [comment]
@averlon 
"disable-notification" kann im change-node auch als jsonata (!! nicht verwechseln mit json !!)  gesendet werden. Vollständig mit allen anderen option. HIer mal ein funktionierendes Beispiel:

![image](https://user-images.githubusercontent.com/5937811/72216539-9dc03100-3522-11ea-9dcc-7d4a8ff00220.png)
