### ISSUE TITLE
howto send animated gif? possible? - api: sendanimation implented

### ISSUE THREAD

**Issue by ozett** [windkh/node-red-contrib-telegrambot#95]
hi,
as i read in the API that  animated gif is not a photo - How to use sendanimation from API?
Is this implemented in your wrapper?

https://core.telegram.org/bots/api#sendanimation

i cannot find example - or did i miss it?

thax for help

**Comment by ozett** [comment]
try and error: i changed the type "photo" to "video" and it was send.
is this the correct  way to do this?

![image](https://user-images.githubusercontent.com/5937811/72428386-dadc2b80-378d-11ea-98f2-010f0ad69e39.png)

**Comment by windkh** [comment]
I will add this soon

**Comment by ozett** [comment]
👍 
i will wait as the workaround works so far...

**Comment by ozett** [comment]
actually there must be somethin wrong with the workaround.
i wanted to forward this animated gif (send as video) from telegram on my android phone to whatsapp.
that normally works without an error. in case of the animated gif the application (WA) had died.
never had seen this before.

**Comment by ozett** [comment]
yes. runs today the first day. 
will never go without!
😃

**Comment by ozett** [comment]
sending a  gif as  a video raises an error with **wrong file.extension**.

(as i actually downloaded the animated gif i  send as video this error became  visible)

![image](https://user-images.githubusercontent.com/5937811/72507104-87c4b000-3843-11ea-91d6-ddeb6c2b6880.png)

**Comment by ozett** [comment]
would be helpful to know if sending of animated gif (old type photo/mp4/-> anigif..??) is possible within a mediagroup?

![image](https://user-images.githubusercontent.com/5937811/72553033-51655000-3898-11ea-890f-6f60bcdac118.png)

**Comment by windkh** [comment]
7.1.3 supports animation type

**Comment by ozett** [comment]
great news, thanks a lot!
👍
