### ISSUE TITLE
Dynamic Authorization/Deauthorization

### ISSUE THREAD

**Issue by bonastreyair** [windkh/node-red-contrib-telegrambot#99]
Hi! 

Is there a way to dynamically authorise/deauthorise users from the configuration node of a TelegramBot or it is just static configuration that can only be modified manually?

I tried to add `{{context.global.authorised_telegram_users}}` (which is a list of the usernames that I set before in the Node-RED global context) but I can't make it work...
<img width="318" alt="Screenshot 2020-02-11 at 19 33 33" src="https://user-images.githubusercontent.com/37800834/74266911-669d9500-4d05-11ea-9d0e-78ac73cd1259.png">
<img width="611" alt="Screenshot 2020-02-11 at 19 32 02" src="https://user-images.githubusercontent.com/37800834/74266791-2fc77f00-4d05-11ea-914b-9ec80cb3e51c.png">

If there is no way to do it right now, I think it would be awesome to add this functionality. 
I'm using version 7.1.1 in Node-RED 1.0.3.

Thanks!

**Comment by windkh** [comment]
Hi @bonastreyair right now this configuration is a static one. I can add this dynamic thing if you want to, but I don‘t really understand the use case behind that. Can you give me a little hint ?

**Comment by bonastreyair** [comment]
Hi, thanks for your quick response!

Imagine you create an aplication for a little company, they want to be able to add or revoke the authorised users to have access to the commands (for checking the temperature in a room for example) but you can't let them modify the Node-RED application.

So I think (for example) sending a configuration email (or whatever other comunication mean), recieved in Node-RED and treated in a way, so that automatically changes the Telegram configuration node to add or remove a "user_name" from the authorised list. Doing so the little company could handle the authorisation of the access of the commands without entering the Node-RED application. In this case I understand that Node-RED should catch the new configuration without the need to "redeploy" anything.

I hope I could explain the "case" I have in mind. What do you think? :)

Thanks!

**Comment by windkh** [comment]
That is understood. I wonder how that can be implemented... give me some hours to rethink that. Thanks for providing that idea...

**Comment by Swiftnesses** [comment]
This sounds awesome, would love to see it implemented ;-)

**Comment by windkh** [comment]
version 7.2.0 support that feature

**Comment by windkh** [comment]
hope it works guys

**Comment by bonastreyair** [comment]
I will check it out as soon as I can! You are awesome! Thanks!

**Comment by windkh** [comment]
de nada
